### ISSUE TITLE
Infinite zoom when using addTiledImage

### ISSUE THREAD

**Issue by edsilv** [openseadragon/openseadragon#1003]
http://edsilv.github.io/openseadragon-tests/

It seems that `maxZoomLevel` isn't being respected when using `addTiledImage`?

If you switch to the .dzi it works as expected.

**Comment by edsilv** [comment]
I added `open` and `add-item` handlers to http://edsilv.github.io/openseadragon-tests/ but they aren't getting called?

https://github.com/edsilv/openseadragon-tests/blob/gh-pages/index.html#L24

**Comment by iangilman** [comment]
You don't get an `open` event because you're using `addTiledImage` instead of `open` or including the image in the initial options.

You don't get `add-item` because you attached the handler to the viewer, but that's a World event (sorry for the confusion there!). This would work:

```
    osd.world.addHandler('add-item', function() {
        osd.viewport.maxZoomLevel = osd.viewport.getZoom(true) * 8;
    });
```

This would also work:

```
osd.addTiledImage({
    tileSource: resource,
    x: resource.x,
    y: resource.y,
    width: resource.width,
    success: function() {
        osd.viewport.maxZoomLevel = osd.viewport.getZoom(true) * 8;
    }
});
```

**Comment by edsilv** [comment]
The `success` handler works, but the `add-item` handler doesn't when added to `world`. Will use the `success` method - many thanks!

**Comment by iangilman** [comment]
Hmm... odd that `add-item` wasn't working. Glad you found something that works though!
