### ISSUE TITLE
Tile loading event

### ISSUE THREAD

**Issue by mkoesem** [openseadragon/openseadragon#1111]
In OSD exists the event `tile-loaded` or `tile-load-failed`, but there is no event like `tile-loading`. I want to show a waiting indicator, while a tile is loading. Is there an other way to handle this?

**Comment by iangilman** [comment]
You might like the getFullyLoaded function and the fully-loaded-change event (both part of TiledImage) introduced with #837. This change hasn't been released yet (though hopefully it will be within a month), but you can grab the latest master and build that.

**Comment by mkoesem** [comment]
I think that this event doesn't solve my problem. I'm using a list of TileSources to show a multipage image. If the user scrolls or zooms in more tiles are loaded. This event tells me wheather all tiles have been loaded. But i want to know when a tile of a TiledImage starts loading when the user scrolls to show a waiting indicator.

**Comment by iangilman** [comment]
The "fully loaded" flag tells you per TiledImage whether all of its tiles are loaded for the current view. You get `fully-loaded-change` events whenever that flag changes. When an image first appears on the screen, it'll be false; once all of its tiles load for the starting view, it becomes true; if the user zooms or pans, requiring new tiles, it becomes false again; once those new tiles have finished loading, it becomes true again.

Seems to me like that's exactly what you need in order to give the user a waiting indicator when tiles start to load. Let me know if I'm missing something.

**Comment by mkoesem** [comment]
I've tried the latest master version and the event is called when the user scolls or zooms, so that i can show a waiting indicator. Thanks for the quick help.

**Comment by iangilman** [comment]
@makoychan See the discussion in #1262, but yes, it appears to be broken in your case, but you don't need it in your case either.
