### ISSUE TITLE
Wrong overlay position (runtime overlay)

### ISSUE THREAD

**Issue by leesei** [openseadragon/openseadragon#1116]
Clone `overlay` branch of [this repo](https://github.com/leesei/test-osd/tree/overlay) and serve it via HTTP server (e.g. `ecstatic`, `python -m SimpleHTTPServer`).  

These are exposed to `window`:
- viewer
- viewport
- tiledImage

Check [`addOverlay()`](https://github.com/leesei/test-osd/blob/overlay/script.js#L76).

### Fail case

Mouse hover the red rect.

A label is shown:
- on the left of the screen for the very first time (`wrong-pos-1.png`)
- shown with wrong placement (it seems) if I moved the image (`wrong-pos-2.png`)

`wrong-pos-1.png`
![wrong-pos-1](https://cloud.githubusercontent.com/assets/544400/22363679/06068766-e4a7-11e6-8a51-d3a808a87151.png)

`wrong-pos-2.png`
![wrong-pos-2](https://cloud.githubusercontent.com/assets/544400/22363682/07f05214-e4a7-11e6-9662-c0748dcecc30.png)

### Expected case

Mouse hover the red rect.

A label is shown on the middle of the image (and the rectangle) (`expected-pos.png`).

`expected-pos.png`
![expected-pos](https://cloud.githubusercontent.com/assets/544400/22363686/12708538-e4a7-11e6-88dc-70895fa31244.png)

### Hot fix

Call `viewer.updateOverlay(rect.label)` after adding the label.

**Comment by iangilman** [comment]
I'm not seeing a red rectangle when I run the project... have you modified the code?

**Comment by leesei** [comment]
Did you change to `overlay` branch after check out?

**Comment by iangilman** [comment]
Ha! Reading comprehension fail on my part. Okay, now I see it. :)

It looks like what's happening is the size of your overlay is being measured before we apply `position: absolute`, and since your overlay is using `display: block` (the default for divs) its width is the full width of its container. 

To fix this in OSD, we need to move the `position: absolute`: 

https://github.com/openseadragon/openseadragon/blob/master/src/overlay.js#L289

...up above the part where we measure the size: 

https://github.com/openseadragon/openseadragon/blob/master/src/overlay.js#L253

@leesei would you be up for making that fix?

Meanwhile, a workaround is to add `position: absolute` or `display: inline-block` to your `overlay-label` class.

Thank you for catching this issue!

**Comment by leesei** [comment]
I see. Thanks for the investigation.
That would indeed solved the first issue.

However, the second issue (`wrong-pos2.png`) still persists.
See `wrong-pos-3.png` for a better log. I did not pan the view, just moved the mouse on and off the rect.
(927.5, 219.085) is the expected position, the wrong position (960, 253.085) seems to be using `LEFT` as placement.

`wrong-pos-3.png`
![wrong-pos3](https://cloud.githubusercontent.com/assets/544400/22494969/353887c2-e877-11e6-8c20-ee247188155d.png)

I've a fork ready for the PR of the fix of this issue.
https://github.com/leesei/openseadragon

**Comment by iangilman** [comment]
I see. I hadn't noticed that before because it only happens in Chrome and I was testing in Firefox. At any rate, it appears to have something to do with the fact that you're hiding the overlay. Perhaps when it's hidden we can't get its size properly. You're unhiding it before you re-add it, but maybe the browser hasn't updated its info yet or something.

At any rate, rather than hiding it, I think a better approach would be to remove it. This seems to fix the issue: 

```
  rect.addEventListener('mouseenter', function () {
    viewer.addOverlay({
        element: rect.label,
        placement: OpenSeadragon.Placement.BOTTOM,
        rotationMode: OpenSeadragon.OverlayRotationMode.NO_ROTATION,
        location: new OpenSeadragon.Point(0.5, 0.5)
    });
  });
  rect.addEventListener('mouseleave', function () {
    viewer.removeOverlay(rect.label);
  });
```

I'm not sure there's much we can do inside OSD to fix this sort of issue. I suppose we could add some documentation about how hidden elements won't get sized properly. 

Great to hear you have a fix for the other issue! Please file the PR :)

**Comment by leesei** [comment]
I see. Thanks for the info.
I use hiding instead of `[add|remove]Overlay()` in order not to touch the DOM as much. Maybe that's a premature optimization.

And to the point of `display: none`, I changed my `.hidden` to `visibility: hidden` that will not affect the element's layout and the second issue can no longer be reproduced. 

Maybe I can add this as an alternate implementation for `Runtime Overlay` in `openseadragon.github.com/ui-overlays/index.html`?

**Comment by iangilman** [comment]
`visibility: hidden` seems like a fine choice, but I'm hesitant to add it to the overlays example page, since there's already so much stuff there. I think it's good have the add / remove example that's there, as that's likely the easiest way for most people (and I don't think we need to optimize away the DOM manipulation unless you're doing thousands of these).
