### ISSUE TITLE
strange behavior when replace the image

### ISSUE THREAD

**Issue by johnico** [openseadragon/openseadragon#1132]
Hi I have 2 button 
each button replace the image in the viewer on click

my code onclick is: 
``` 
            viewer1.close();

            var tileSource={
                            type: 'image',
                            url:  img . // replaced on click 
           }
                      
           viewer1.open(tileSource);
```

the problem is that when click on the button it show the previous image for 1-2 second and then replace the image 

is there a way ti insure that its will not happen ? to clean the viewer or something 

tried with viewer.close - does not work for me 

thx a lot

**Comment by iangilman** [comment]
So the previous image remains for a few seconds while the new image loads, and you'd prefer the previous image to go away while the new one loads? Strange, I would think that `viewer1.close()` would have accomplished that. 

I tried to reproduce locally, but my sample images load too quickly; it's pretty much instantaneous. Do you have a link or a codepen of your issue I could take a look at?

Another possibility, since you're using the `image` tileSource type and so there's only one tile to load, is to pre-load that image in your browser before the user clicks the button. It should then be cached in memory and OSD will get it right away.
