### ISSUE TITLE
Keep the position and zoom when split the images and compare between  2 images

### ISSUE THREAD

**Issue by johnico** [openseadragon/openseadragon#1141]
Hi ,

**http://codepen.io/anon/pen/RpWoar**
(try to click on show and hide button few times after zooming the first image) and you will see the lost zoom problem(it has to keep the zoom )

**i found that **preserveImageSizeOnResize : true** help and work but only for one image and when i add the sync between the images(the handlers) its makes lot of problems**

I have 1 big image width 100% with fixed height and button that split the screen to 49.5% and 49.5% for each div

I m use  preserveViewport:true   to keep the zoom while I split the image so both images should keep the zoom and position 

the problem is when I close and open the div from split (2 images) to 1 image  I lost the zoom a little bit . and sometimes it just return to home . or move to other position.

I also tried  to save bounds .= viewer1.viewport.getBounds();  on show button 
and on hide button : viewer1.viewport.fitBounds(bounds);  
but afterI print again the  viewer1.viewport.getBounds() . its not took the previous bound 

on the button click I just used : (I have 2 buttons  - show and hide)  
```
                 viewer1.open(tileSource1);
                viewer2.open(tileSource2);
                viewer1.preserveViewport = true;
```

**So what I need is to keep the compare between 2 images that I zoom in the 1 big image and then should keep the zoom when split the images . and  when close it ...etc** 

thx all for helping

**html code**

```
<div id="maincontent" class="fadeClass">
    <div class="images-wrapper" style="height:615px;">
      <div id="main-zoom-container" style="width:100%;height:615px;">
        <div style="width:100%;height:100%;" id="mainImage" >
        </div>

      </div>

        <div id="compareSection" style="display:none;position:relative;">
          <div style="width:100%;height:100%;" id="comparedImage">
          </div>
  
        </div>

    </div>
  </div>
```

**my openseadragon viewers code is:**

````
var viewer1 = OpenSeadragon({
             id: "mainImage",
             maxZoomPixelRatio:6,
           defaultZoomLevel: 	0.75,
           minZoomLevel: 	0.75,
           visibilityRatio: 	1,
             preserveViewport:true,
             prefixUrl: "img url",
   });
var viewer2 = OpenSeadragon({
                id: "comparedImage",
                maxZoomPixelRatio:6,
                defaultZoomLevel: 	0.75,
                minZoomLevel: 	0.75,
                visibilityRatio: 	1,
             preserveViewport:true,
                prefixUrl: "img url",
      });
```


 // this for control the pan and zoom together
      var viewer1Leading = false;
      var viewer2Leading = false;

      var viewer1Handler = function() {
        if (viewer2Leading) {
          return;
        }

        viewer1Leading = true;
        viewer2.viewport.zoomTo(viewer1.viewport.getZoom());
        viewer2.viewport.panTo(viewer1.viewport.getCenter());
        viewer1Leading = false;
      };

      var viewer2Handler = function() {
        if (viewer1Leading) {
          return;
        }

        viewer2Leading = true;
        viewer1.viewport.zoomTo(viewer2.viewport.getZoom());
        viewer1.viewport.panTo(viewer2.viewport.getCenter());
        viewer2Leading = false;
      };

      viewer1.addHandler('zoom', viewer1Handler);
      viewer2.addHandler('zoom', viewer2Handler);
      viewer1.addHandler('pan', viewer1Handler);
      viewer2.addHandler('pan', viewer2Handler);`

**Comment by iangilman** [comment]
Yeah, because you're wanting and taking such control over the pan and zoom, you can't rely on the automatic things like preserveViewport. The trick is to turn off `autoResize` and handle it yourself, like so:

http://codepen.io/iangilman/pen/YZyejG

**Comment by johnico** [comment]
@iangilman  thx  a lot  look like autoResize is engough and I dont need smth else ?
now if i  want to disable the zoom between other buttons ? preserveViewport will return to the home zoom? 

btw can we do something with the gray background until the right image is loading?  

thx a lot again

**Comment by iangilman** [comment]
Wow, lots of questions! I may not be able to answer them all. 

I suppose you noticed that it's not just `autoResize: false`, but also the `maintainZoom` function. In particular, when you have auto-resize off, you need to explicitly call `viewer.viewport.resize`. This is what's causing the stretching whenever you see that. You'll probably want to do something for window resize events and anything else that will cause one of your viewers to resize, such as the "move next" button. 

`preserveViewport` is only for preserving the pan/zoom when opening a new image. Because you're taking control of things, best to leave that off and set the pan/zoom explicitly. 

In fact it might be good for you to always keep a separate copy of the master pan/zoom info so you're not reliant on what's stored in the viewers. 

The gray background when the right image is loading is because we're not resizing it until the fadeIn is complete. I did that because you actually don't know the proper size before the fadeIn starts, because the element is hidden. You could probably figure out how to get it to happen right after the fadeIn starts though. Another option, of course, would be to just show/hide rather than fading it in. 

The timing issue with the fadeIn is also why there's a delay before taking you to the zoom point, which I think might be what you're referring to as an animation.

I hope that helps!

**Comment by johnico** [comment]
@iangilman
thx a lot . You are amazing . Learned a lot from your Answers and support

Promise this is the last question in that issue :) 
I tried what you said about resize and also to keep the Zoom and in variables but I did not mange to fix that wIred thing.
When click on show the divs become white and the images disappear until you click on the mouste
http://codepen.io/anon/pen/dvGbPB

**Comment by iangilman** [comment]
I've taken a whack at it, including using my suggestion to keep master zoom/pan variables. Take a look: 

http://codepen.io/iangilman/pen/BWKKxQ
