### ISSUE TITLE
pan is not working in iPhone

### ISSUE THREAD

**Issue by mrmean007** [openseadragon/openseadragon#1142]
```
viewer.addHandler('canvas-drag', function(e){
		  Toast("canvas drag");
		  if( e.originalEvent.pointerType !="touch" || !isDrawingMode) return;
		  console.log('drag');
		  console.log(e);
		  dragAmount++;
		  if( true ){
			//console.log('panning');
			var x = e.originalEvent.clientX - startx;
			var y = e.originalEvent.clientY - starty;
			var point = new OpenSeadragon.Point(-x, -y);
			var panBy = viewer.viewport.deltaPointsFromPixels(point);
			viewer.viewport.panBy(panBy);
			startx = e.originalEvent.clientX;
			starty = e.originalEvent.clientY;
		  }
		});
```
this code is working in android phone but not working on iPhone. Is there something missing or wrong ?

**Comment by iangilman** [comment]
Maybe the iPhone's touch events don't have clientX/clientY? I imagine you should use the event's `touches` array instead: 

https://developer.mozilla.org/en-US/docs/Web/API/TouchEvent

Probably easier than that, though, would be to use the `position` property of the OSD event: 

http://openseadragon.github.io/docs/OpenSeadragon.Viewer.html#.event:canvas-drag

**Comment by mrmean007** [comment]
I have tried with OSD position `position` property and it didn't work. I will try `touches` array.

**Comment by mrmean007** [comment]
[here](http://meancoder.000webhostapp.com/osdfabricoverlay/index0.html) is my test page. It is still not working.

**Comment by iangilman** [comment]
Hmm... your test page seems to be working for me. In Mac Chrome, after I click the draw button, a single click in the viewer starts drawing a line, and as I move the mouse around the line follows until I click a second time.

On the iPhone, after I click the draw button, a single tap doesn't look like it's doing anything, but a second tap draws a line from the first tap location, showing that it was doing the same thing as on desktop. The difference here being that touch devices don't have hover, so you can't see the line being drawn between the two taps.

One difference I'm seeing is that it's possible to tap on an existing line and get a blue rectangle with handles that allows you to move the line around. I can get this to happen on iPhone but not desktop. 

Another thing I noticed is that the image doesn't seem to come up at all on Mac Firefox. 

Anyway, looks like you've resolved the location issue?

**Comment by mrmean007** [comment]
No. The issue is still there. I am still not able to pan on iPhone after I click draw button. The drag event triggers, but the viewer is not panning with the event. Something is wrong with way I am getting coordinates. I have tried your suggested solutions except `touches` array because the array does not exists in the object.

**Comment by iangilman** [comment]
I can't reproduce the issue you're describing. Here is what I'm doing:

1. Go to http://meancoder.000webhostapp.com/osdfabricoverlay/index0.html on my iPhone
1. Use my finger to pan around; no problem
1. Hit the "Draw" button to enter drawing mode
1. Note that dragging no longer pans (because we're in drawing mode)
1. Tap twice to make lines (1 for start of line, the second for end of line)
1. Hit the "Draw" button a second time to exit drawing mode
1. Use my finger to pan around; no problem

Can you tell me what I should be doing differently to reproduce the issue you are describing?

As for the `touches` array, I wasn't clear before, but I meant on the `originalEvent`, so in your code above it would be `e.originalEvent.touches`. More reference: 

https://developer.mozilla.org/en-US/docs/Web/API/TouchEvent/touches

**Comment by Kampii** [comment]
Hey Ian, the thing that @mrmean007 is trying to solve is being able to pan while in the drawing mode. The expected behavior is to start the drawing mode and being able to zoom in or drag the image. The single tap would add the first point. The user could then still pan the image with drag gesture or zoom out/ in with the pinch. The next tap would add the 2nd point and draw the line. Does that make sense? We've been struggling with this for quite a while..

**Comment by mrmean007** [comment]
@Kampii that is exactly what is wanted to say.

**Comment by iangilman** [comment]
I see, thank you for the clarification! Won't panning work if you just remove these lines from your draw button click handler?

```
overlay._viewer.panHorizontal = false;
overlay._viewer.panVertical = false;
```

**Comment by mrmean007** [comment]
Thanks. It works now.
