### ISSUE TITLE
Visualizing an image stack?

### ISSUE THREAD

**Issue by mgiacomelli** [openseadragon/openseadragon#1147]
I have been porting our old HDView 3D data over to openseadragon.  Previously what we had done to visualize image stacks (3D data sets) was to have a bar with a list of thumbnails that linked to different HTML files for each depth.  

However the Openseadragon viewer looks a lot more capable, so I'm wondering if it is possible to load multiple identically sized images (each representing a different depth in some object) onto the same viewer and then switch between them while retaining zoom/position?  This way users could rapidly flip between different Z depths when examining 3D data.

**Comment by iangilman** [comment]
Absolutely! That's a great use for OpenSeadragon multi-image: 

http://openseadragon.github.io/examples/multi-image/

You can load all the images at the same location and either add/remove them from the OSD Viewer's world or have them all there all the time but change their opacity. You'll want to manage the stack somehow, since you don't want all of the images trying to load at once. Of course you might want to pre-load the next image in the stack once the current image is done loading. 

Let me know if you have questions, and please share your project once it's ready to see! I'd love to play with it :)

**Comment by AndrewNorgan** [comment]
This would definitely be useful functionality!  We have a lot of use-cases for viewing multiple Z-stacks in images.

**Comment by iangilman** [comment]
@AndrewNorgan Hopefully @mgiacomelli can share their work with you, but if not, and you pursue this, let me know if you need any pointers!

**Comment by mgiacomelli** [comment]
@AndrewNorgan 

We have been using OpenSeadragon for a few weeks now to visualize large (many gigavoxel) multiphoton volumes taken from surgical pathology specimens.  There is a minor delay (~1 second) between large layers while they load, but overall the interface is quite good, and I suspect someone with better javascript skills than I could probably preload layers to hide that latency. 

Here is a very small example volume taken using multiphoton fluorescence and then rendered as H&E using the code in my github page:

http://18.62.11.24/Nora/030917_Norm_1_bot/zstack.html

As you can see it works very well, although compared to software like slideatlas (which uses webgl or something like that) there is some delay and vsync issues.

**Comment by iangilman** [comment]
@mgiacomelli Excellent! 

To avoid that delay you can preload the next image, something like so:

```
viewer.addTiledImage({
  tileSource: ...,
  index: 0 // So it goes underneath the existing one
});
```

When you're ready to switch, you could remove the top one, like so:

```
viewer.world.removeItem(viewer.world.getItemAt(1));
```

...or you could hide the top image instead:

```
viewer.world.getItemAt(1).setOpacity(0);
```

Of course if you have more than 2 images in place at a time you'll have to be good about selecting the right indexes. Anyway, that should help make things smoother.

**Comment by AndrewNorgan** [comment]
@mgiacomelli Great, thank you for sharing!  I am looking to implement your solution as a stopgap solution, it should work well.  @iangilman Is there any plan to implement smooth multilayer viewing by default into OpenSeadragon?

**Comment by iangilman** [comment]
There is currently no plan to implement smooth multi-layer viewing by default. I imagine it would make a great plugin, though, if someone wanted to build it.

**Comment by imoutsatsos** [comment]
I have a related question please. I'm using OSD for reviewing multi-channel digital microscopy images. So I need to review ALL layers simultaneously to get a composite picture. I have used the OSD filtering plugin to colorize the gray scale images and custom positions to place them on top of each other in the viewer.world. Then using the **TiledImage. setOpacity()** method I make them semi transparent so that I can visualize the 'composite' image. However, the composite image lacks contrast as each layer opacity adds a corresponding layer of 'haze' 
![image](https://user-images.githubusercontent.com/3408226/29228429-ae05a4fc-7ea7-11e7-8f42-86a4161fd210.png)

Is there a better way to approach this? In ImageMagic, I can combine 3 separate gray scale images into one RGB image getting much better results. However, even this approach is not sufficient as some images may have more than 3 channels.

**Comment by boskar** [comment]
See this: https://github.com/openseadragon/openseadragon/issues/389

**Comment by iangilman** [comment]
This, too, would make a great plugin! I wonder if some of the existing plugins might contain some good code ideas for strategies to use: 

http://openseadragon.github.io/#plugins
