### ISSUE TITLE
Keep navigation buttons on full screen mode

### ISSUE THREAD

**Issue by umairm638** [openseadragon/openseadragon#1152]
I'm using custom buttons for normal screen and I want to display openseadragon default navigation buttons (home.zoom-in,zoom-out,rotation) when it goes to full scree mode. My code is bellow: I've also tried with setting showNavigator: true but didn't worked. It only work when I remove my custom buttons settings.

    var osd_config = {
    id: "viewer",
    prefixUrl: "js/openseadragon/images/",
    preserveViewport: true,
    showNavigator: false,
    visibilityRatio: 1,
    minZoomLevel: 1,
    minLevel: 1,
    zoomInButton: "zoom-in",
    zoomOutButton: "zoom-out",
    homeButton: "home",
    fullPageButton: "full-page",
    nextButton: "next",
    previousButton: "previous",
    showRotationControl: true,
    gestureSettingsTouch: {
        pinchRotate: true
    },
    tileSources: []
    }

**Comment by iangilman** [comment]
Looks like we don't have a mechanism for changing the icon of a button once it exists. You could look into adding that feature to OpenSeadragon.Button. Otherwise, you could try making two sets of buttons (one for each look) and show/hide the sets as appropriate when you go to full screen. Another option would be to delete one set of buttons and create a fresh set of buttons when you transition. 

Are your custom buttons shown in the viewer or outside of it?

**Comment by umairm638** [comment]
@iangilman My custom buttons are outside of viewer.

**Comment by iangilman** [comment]
I see... so you actually don't care about switching icons; you just want to hide the default controls normally and show them again on full screen?

It looks like to hide the controls you could do something like:

```
viewer.navControl.style.display = 'none';
```

Then wait for fullscreen events and show them again.

**Comment by umairm638** [comment]
@iangilman yes you are right i want to display default controls on full screen. the code you provide, where i've to write that code and how it'll work in my case? i added your code full screen button click but it gives me error that viewer.navControl is undefined.

**Comment by iangilman** [comment]
Looks like in order to make this work you'll need to write your own logic for the buttons that are outside of the viewer. If you tell the viewer about your outside buttons like so: 

```
zoomInButton: "zoom-in",
zoomOutButton: "zoom-out",
homeButton: "home",
fullPageButton: "full-page",
nextButton: "next",
previousButton: "previous",
```

...then it won't create the in-viewer buttons you want. That's probably why `navControl` is undefined.

Here's a quick example of what I had in mind:

http://codepen.io/iangilman/pen/MpPbdq

Notice that I have already built an outside fullscreen button. You'd just need to build outside buttons for the remaining controls you wanted. For their logic you can steal code from OSD, for instance: 

https://github.com/openseadragon/openseadragon/blob/master/src/viewer.js#L3180

Unfortunately we don't yet have that functionality neatly encapsulated, though it would be great. That's discussed in https://github.com/openseadragon/openseadragon/issues/489

**Comment by achu1998** [comment]
Hi @iangilman , If the issue is still open, I'd like to take a look. Please point me in the right direction.
