### ISSUE TITLE
Question: using mouse wheel to scroll

### ISSUE THREAD

**Issue by susanmonnelly** [openseadragon/openseadragon#1154]
I'm investigating a solution to use the mouse wheel to scroll the image in the viewport.   I've set the correct mouse gestures to disable the zoomToScroll and now want to attach that event to a scroll.  Is there an example somewhere that I can follow.   If not I'm wondering if this is the best way to go:

https://openseadragon.github.io/docs/OpenSeadragon.MouseTracker.html#scrollHandler

Thanks for your help,
Susan

**Comment by iangilman** [comment]
Do you just want the page to scroll naturally? Or are you wanting the contents of the viewport to scroll as they would if they were a normal page?

If you just want the page to scroll naturally (so the viewport can scroll into and out of view), disabling zoomToScroll should be enough.

If you want to translate the scroll events into vertical viewport panning, unfortunately that's a little challenging, because the browser's mouse wheel events don't actually line up exactly with how far the page would scroll. You can certainly use the scrollHandler and translate that to `viewer.viewport.panBy` calls, but it wouldn't feel the same as a regular scrolling page. I wrestled with this for the scrolling in this demo:

http://iangilman.com/osd/test/demo/m2/

...and what I ended up going with is a scrollable div that I lay on top of a viewer. I then capture those scroll events and translate them into panning for the viewer underneath. This takes a little finesse to keep everything in sync, but the result is pretty seamless. One side effect is that the scrollable div also needs to be where you get all of your other mouse events (like hovers and clicks), so you need to translate them into whatever you need for the viewer underneath. 

Here's the code for that demo:

https://github.com/openseadragon/openseadragon/blob/master/test/demo/m2/js/main.js

Again, if all you want is for the page to scroll normally, you don't need to bother with any of that.
