### ISSUE TITLE
Tracking pixel coordinates

### ISSUE THREAD

**Issue by PharaunMizzrym** [openseadragon/openseadragon#1159]
Hello
I'm building a project with OpenSeadragon to inspect large objects. In order to do this, I need to know the coordinates of the pixel where the cursor is placed to find out the distance in mm to a certain point of the image that I already know. 
The fist approach that I tried is use imaginghelper plugin, but when the object is created it raises an error:
_Cannot read x property of null in viewer.viewport.contentSize.x_
The code that I wrote for that is this one:
```
viewer = OpenSeadragon({
		id:            'map',
		prefixUrl:     'openseadragon/images/',
                tileSources: url,
		showNavigator: true
     });
var imagingHelper = viewer.activateImagingHelper({onImageViewChanged: onImageViewChanged});
```

Seconldly, I tried to add a handler that captures when the user clicks on the image, but it returns the coordinates on a single tile, not the coordinates on the whole tiled image. The code that I used for this is:
```
viewer.addHandler('canvas-click', function(event) {
        console.log('click', event.position);
 });
```

Is there any way to do this?  

Thanks in advance

**Comment by iangilman** [comment]
Perhaps the imaging helper issue is due to this issue:

https://github.com/msalsbery/OpenSeadragonImagingHelper/issues/9

You might try pinging the author there, or even proposing a patch.

Anyway, it's easy enough to translate to image coordinates. The `event.position` from the `canvas-click` event is in web coordinates, relative to the viewer, so you'd just need to do:

```
var imagePoint = viewer.viewport.viewerElementToImageCoordinates(event.position);
```

For more information on the various coordinate systems, see:

http://openseadragon.github.io/examples/viewport-coordinates/

**Comment by PharaunMizzrym** [comment]
Thanks for your quick response. 
I choosed the second aproach and it works with viewerElementToImageCoordinates method.

I'll try to work further with the imaging plugin issue just in case that I were able to find a solution.

regards
