### ISSUE TITLE
How to map the Google map coordinates as a point on the OpenSeadragon picture

### ISSUE THREAD

**Issue by azhangmeng** [openseadragon/openseadragon#1180]
How to map the Google map coordinates as a point on the OpenSeadragon picture

**Comment by iangilman** [comment]
You mean like latitude and longitude? OpenSeadragon doesn't have built in support for geo coordinates, so you'll need to convert them yourself. Depending on the projection you're using, you should be able to find conversion code that'll help, or you could just fiddle with it until you get something that works. For instance, longitude is -180 on the left (which will probably be 0 in your OSD viewport coordinates) and 180 on the right (which is probably 1 in your OSD viewport), so just do a linear scale for those. Latitude is a little trickier since it may not be linear.

**Comment by zhuyinjing** [comment]
if you want to map the Google map coordinates,
maybe you can see openlayers
its also good plugin for map.

**Comment by azhangmeng** [comment]
@zhuyinjing thank you, I went to study it

**Comment by iangilman** [comment]
Indeed... if you just want to do map zooming, OpenLayers (http://openlayers.org/) is a fine choice. Another option is Leaflet (http://leafletjs.com/).
