### ISSUE TITLE
Why the examples on codepen.io no loger work?

### ISSUE THREAD

**Issue by Medwar** [openseadragon/openseadragon#1206]
Why the examples on codepen.io no loger work?

Giving the message: "Unable to open [object Object]: Unable to load TileSource".
Like this ones:
https://codepen.io/iangilman/pen/oXNMeQ
https://codepen.io/iangilman/pen/EZqazZ

**Comment by iangilman** [comment]
Very strange! I'll have to take a look into it... thank you for alerting me!

**Comment by iangilman** [comment]
The problem is that Codepen went through and changed all http to https, but changing the DZI xmlns to https breaks our DZI detection. The fix is to change the xmlns back to http://schemas.microsoft.com/deepzoom/2008. I've done so for all of my pens in the OSD Collection: 

https://codepen.io/collection/APoyjJ/

...and I've notified @IllyaMoskvin (who's done three of those pens). 

If anyone else has OSD-based Codepens, you should check yours as well! Also let me know about them so I can add them to the collection :)

Meanwhile, another fix we can make in the code is to not worry about http vs https in our xmlns detection... I'll leave this issue open for that fix.

**Comment by IllyaMoskvin** [comment]
Fixed my pens! Now with more cats.

**Comment by iangilman** [comment]
@IllyaMoskvin Beautiful :)
