### ISSUE TITLE
Transparent images not drawn in Safari and iOS

### ISSUE THREAD

**Issue by sickrandir** [openseadragon/openseadragon#1211]
You can see the issue happen in this small clip on Safari:
http://gph.is/2rs5HM3
Working example here:
http://dhhq.duckdns.org/configurator/4

In chrome the same code doesn't produce this effect and images are always shown.
Adding multiple transparent images, each one with a different size and aspect ratio, causes the images to disappear at certain zoom levels and bounds positions.
There seems to be a pattern as images disappear when one of the borders goes offscreen.
In this clip you can see how images disappear even from the sketch canvas:
http://gph.is/2r3oGfE

I can test and debug on Safari and iOS but I'd need directions to the code most probably responsible for the issue.

**Comment by iangilman** [comment]
@sickrandir Thank you for digging into this! I figure the part of the code changed in #1035 is a good starting point: 

https://github.com/openseadragon/openseadragon/pull/1035/files

You might try putting some console logs in there to see if you can notice a pattern for when it works vs when it doesn't. Note that in OSD you'll want to use `$.console.log` since it won't cause problems with the linter.

**Comment by sickrandir** [comment]
I'm logging the 'bounds' just before this.context.drawImage but I just can't seem to find a pattern. Non neg values. It would help to break/log on drawImage just for the tiledImage that disappear. Do you know how to do that? Other guesses?

**Comment by iangilman** [comment]
Indeed... perhaps it's analogous to the issue we had blending from sketch to main, but for drawing into sketch originally. That happens here:

https://github.com/openseadragon/openseadragon/blob/master/src/drawer.js#L303

...which calls to here:

https://github.com/openseadragon/openseadragon/blob/master/src/tile.js#L287

**Comment by sickrandir** [comment]
Looking at what happens here:
https://github.com/openseadragon/openseadragon/blob/master/src/tile.js#L287 and logging just for a selected tile that disappear.
The method drawCanvas gets executed even when the tile disappear and looking at the values of: position.x, position.y, size.x, size.y I can't seem to find a pattern. 
One problem is that I don't fully understand how drawing happens and what can cause an image to not be drawn.

**Comment by iangilman** [comment]
Well, my assumption is that it's something like #1035 where the image would normally be drawn on any other browser, but because of a bug in Safari, it's not being drawn. So it makes sense that drawCanvas is getting called, since OSD thinks it should be drawing that tile, but somehow Safari refuses to draw it. 

I'm sorry to hear there's no discernible pattern. I suppose it's possible we're barking up the wrong tree by looking at how it gets drawn to the sketch canvas. One possible thing to try there would be to attach the sketch canvas to the page so you can actually see what's happening in it. If things get drawn to it but don't make it to the final canvas, then we know the problem is in the copy stage not the original draw stage. Either way it narrows it down. 

Btw, it might be useful for you to make a simplified repro project... both because it allows you to isolate the issue, and also because then I could take a look directly.

**Comment by sickrandir** [comment]
Thanks Ian. 
I made the simplest codepen I could. OSD is externally linked to the latest master version in which I just added debug logs. https://codepen.io/sickrandir/pen/qjOode
I logged the values of: rendered.canvas.width, rendered.canvas.height, position.x, position.y, size.x, size.y 
in drawCanvas method for the tiles of the disappearing image just for the small amount of canvas drag that makes the image disappear. The log trace stops and the image is not dispayed. The log is here: https://gist.github.com/sickrandir/0cfc017ef97bc2b0128c5b6de0ed533c
This is the log of the inverse drag that make the image reappear:
https://gist.github.com/sickrandir/fbab0995745934dc3706c0ba5879efdc

The only thing I notice is that rendered.canvas.height and position.y keeps oscillating on every log, but that does happen both when the image is displayed and when is hidden.

**Comment by sickrandir** [comment]
I tried again the sketchCanvas scenario with this simpler example and I don't see the image disappear. So it seemed that I was mistaken and maybe the drawing on the sketchCanvas with multiple images looked confused and led me to believe the images we actually disappearing. Here the pen with the sketchCanvas: https://codepen.io/sickrandir/pen/vZNVKP

**Comment by sickrandir** [comment]
I focused again on the blendSketch method. 
I added logging like this: 
`   if (bounds.x < 0) {
            	$.console.log("NEG X: ", bounds.x);
                bounds.width += bounds.x;
                bounds.x = 0;
            }
            if (bounds.width > this.canvas.width) {
            	$.console.log("bounds larger than canvas");
                bounds.width = this.canvas.width;
            }
            if (bounds.y < 0) {
            	$.console.log("NEG Y: ", bounds.y);
                bounds.height += bounds.y;
                bounds.y = 0;
            }
            if (bounds.height > this.canvas.height) {
                $.console.log("bounds higher than canvas");
                bounds.height = this.canvas.height;
            }`

and you can see in this small clip that an image can disappear without triggering any of the corner cases addressed in the patch #1035

**Comment by iangilman** [comment]
@sickrandir This is great debugging! I'm sorry I've been so quiet... fighting multiple fires on other projects. I'm still hoping to get to this soon.

**Comment by iangilman** [comment]
@sickrandir Okay, I think I've fixed it... please try #1222.

**Comment by sickrandir** [comment]
@iangilman Thank you so much! I can confirm that the bug is fixed both on Safari on Mac and IOS!

**Comment by iangilman** [comment]
@sickrandir Excellent; thank you for verifying!
