### ISSUE TITLE
Q: scroll to pan?

### ISSUE THREAD

**Issue by jrochkind** [openseadragon/openseadragon#1228]
On my mac trackpad, I'd love it if I could use the two-finger scroll gesture to actually pan the image around, instead of zooming.  As one can do with an ordinary 'page' in a browser or many other apps. 

I can turn off scroll to zoom with `gestureSettingsMouse: { scrollToZoom: false }`, but this doesn't give me "scrollToPan". 

Has anyone figured out any way to do this, or have any ideas to this effect?  I guess it could be tricky figuring out how to translate delta of 'scroll' to an appropriate pan.

**Comment by iangilman** [comment]
Yeah, theoretically it's pretty easy to capture the "wheel" events, and then you can call the pan function from there. The problem is that the browser's wheel events don't translate directly to a scroll pixel amount, and every browser and OS have slightly different translations, and the user can change the responsiveness in their system settings as well. Even from device to device (e.g. from mouse to trackpad) it can be different. 

Since we're so used to the responsiveness of whatever device we're using, it may feel wrong if the scroll amount isn't the same. Still, you could experiment and see if you found something that worked for you... just make sure to try it on a variety of platforms. 

The other approach is to put an invisible scrollable panel on top of your viewer and catch the scroll events on it... that way you're catching actual scroll values because the browser is scrolling this panel (rather than catching the wheel events). This is the approach I took for the scrolling portion of this demo: 

http://iangilman.com/osd/test/demo/m2/

The downside to this is that the scrollable panel will also catch all of your clicks and drags, so you'll have to handle them there and send them through as needed. 

Here's the code for that demo:

https://github.com/openseadragon/openseadragon/blob/master/test/demo/m2/js/main.js
