### ISSUE TITLE
OpenSeaDragon Viewer-flickering while loading the image tile by tile

### ISSUE THREAD

**Issue by shivarajub2010** [openseadragon/openseadragon#1242]
We are using openSeaDrogon Viewer to show 'Legacy Image Pyramid' images whose size is more than 10MB. We are experiencing the delay in loading the tiles (tilesize=256). We have used GleamTech fileUltimate to load the tiles from server (image processing based on the tiles is happening in the server using C#).
We have observed that getTileUrl is called several times which will return the tile url of the Image.
Is there a way to render image without tile flickering that end user should not experience?
Below is the code snippet of OSDViewer.js

  ```
var tileImageUrl =’ /UtilityManager.ashx/ProcessTileImage?’
     var options = {
        tileSource: {
            type: 'legacy-image-pyramid',
            height: height,
            width: width,
            tileSize: 256,
            minLevel: 9,           
            getTileUrl: function (level, x, y) {
                return tileImageUrl + "&level=" + level + "&x=" + x + "&y=" + y +
                 "&tileSize=" + tileSize + "&tileOverlap=" + tileOverlap + "&fileNames=" + fileNames + "&lutColors=" + lutColors + "&RGBColors=" + RGBChannel;
            }
        },
        opacity: 1
    };
    viewer.openTileSource(options);
```

**Comment by iangilman** [comment]
Are you using the latest OpenSeadragon? I ask because `openTileSource` has been deprecated in favor of `open`. 

Also, it looks like you're mixing the protocols for legacy image pyramid and custom tile source. The legacy image pyramid is for images that have multiple sizes, but no tiling. I think you want custom tile source, which is just like what you have, except remove the `type` property. For more info, see: 

http://openseadragon.github.io/examples/tilesource-custom/

Maybe those changes will sort things out already. If not, what other settings are you using for your viewer?

**Comment by shivarajub2010** [comment]
I checked with latest OpenSeaDragon, but the issue persists.
We are trying to display *.tif (Tagged Image Files) in the OpenSeaDragon Viewer. will this be supported by OpenSeaDrgon, if so ,what is the procedure to achieve?

**Comment by iangilman** [comment]
We don't have plans to support TIFF files in OpenSeadragon, as they're only supported by some browsers (appears to be Safari and IE). For other browsers (Chrome and Firefox) we'd need to add some sort of conversion library that reads the TIFF file and converts it into something the browser can use. It's much more efficient to do that conversion once on the server. 

Regarding the flickering issue, can you share your project somehow so I can see it in action?
