### ISSUE TITLE
How to load multiple images (tileSources) from external file?

### ISSUE THREAD

**Issue by dlong500** [openseadragon/openseadragon#1251]
It doesn't look like the JSONP callback method of loading images works for loading multiple images.

What I want to do is define a list of DZI sources in a file that gets referenced when loading the viewer, such as:
`[
"/images/zoom/imageA.dzi",
"/images/zoom/imageB.dzi"
]`

Is there a way to do this without having to write extra code to pull that data in first before loading the viewer?

**Comment by iangilman** [comment]
Loading multiple images certainly works with regular AJAX (if it's on the same server, or if it's on an external server using CORS), just like you said: 

```
tileSources: [ "/images/zoom/imageA.dzi", "/images/zoom/imageB.dzi" ]
```

I assume you're dealing with an external server where you can't use CORS, so JSONP is your only option? Looking at the code it seems like multiple JSONP should work, as long as each file name is different, like so: 

```
tileSources: [ "/images/zoom/imageA.js", "/images/zoom/imageB.js" ]
```

If they both have the same file name (e.g. imageA for both), you'd have a collision, due to this code:

https://github.com/openseadragon/openseadragon/blob/master/src/tilesource.js#L465

Seems like actually we could kill that callbackName entirely because our JSONP function makes a unique one automatically if none is specified: 

https://github.com/openseadragon/openseadragon/blob/master/src/openseadragon.js#L2290

Does that help?

**Comment by dlong500** [comment]
My issue is that I want to be able to have a file that defines the list of multiple images (one or more), and then when loading the viewer that file would be the single argument to `tileSources`.  Is there a way to do that?

For example, I'd might have a file called `/images/item/X204.js` like so:
```
X204({
  images: {[
    "/images/zoom/X204A.dzi",
    "/images/zoom/X204B.dzi"
  ]}
}
```

And then the when loading the viewer the file would be referenced like so:
```
OpenSeadragon({
    ...
    tileSources:   "/images/item/X204.js",
    ...
});
```
That way, I don't have to make extra database calls to figure out that item X204 has two images when loading the viewer, because that information has already been predetermined in the `X204.js` file.

Does that make sense?

**Comment by iangilman** [comment]
I see. No, we don't support that. You'll have to load that file and then pass the results into OpenSeadragon. You can either wait to create your viewer until after you've loaded that file, or you can create the viewer but then call `viewer.open` with the results of the file when they arrive.

**Comment by dlong500** [comment]
Ok, that's basically how I'm doing it now (using `Promise.all` to wait until both the file and OpenSeadragon are dynamically loaded), though it might be nice at some point to add support natively for loading multiple image definitions from an external file just to make things simpler for end users.

**Comment by iangilman** [comment]
Fair enough. I guess we'd need to define some kind of format for such a file. Also we'd want to make it more explicit than just `tileSources: '//foo.com/foo.js'` since we're already using that for JSONP loading of individual tile sources, and we already have too much magic auto-detect stuff with weird edge cases.
