### ISSUE TITLE
Very poor performance on high resolution (5k)

### ISSUE THREAD

**Issue by thomasboulongne** [openseadragon/openseadragon#1324]
I have a viewer in which I navigate using `fitBounds`. It behaves perfectly until I put it on a 5k screen, then it becomes very laggy, it seems to take very long to load. 
Any idea why does it become really laggy and how could I avoid this?

**Comment by iangilman** [comment]
Interesting... I get good performance with the viewer on http://openseadragon.github.io/ in fullscreen mode on a 5k HDPI screen in Mac Firefox. What browser/OS combination are you using? Does that page have the same performance problem for you as your page does?

**Comment by thomasboulongne** [comment]
It gives me a loss in performance (around 25fps, when I have 60+ in smaller resolution), but in my case I also have UI animations (divs appearing, translating) that are really laggy too, worse than 25fps. Tested with Chrome/FF on OSX Sierra.

Is there anything specific I should monitor to track down the issue?

**Comment by jetic83** [comment]
I also experienced some slowniness on larger screens, but it is really a complex question. Some sources of perfomance issues can be:
 - the size itself needs more tiles to be loaded. But a browser only allows 4 or 6 concurrent connections to one server. So some tiles start to have to wait for download. You can see that well with Chrome‘s network inspection. 
- overlays on OSD (also e.g. fabricjs) slow down at many objects (many can be a low number, such as 10, 20, 30). But a larger screen displays more objects. Are your divs overlays? 

Profiling is a good way to identify what is exactly slow.
WebGL really sounds highly interesting. But it seems to be complicated too, otherwise people would have implemented it already.

I am in the stage where I want to optimize the experience too, but it is surprisingly smooth on a fullscreen Surface Studio, Edge, win 10, while it is much slower on a Desktop machine, Chrome, win 7.

**Comment by jetic83** [comment]
Would WebSockets be a solution to the small limit of concurrent web-connections to the tile server?

**Comment by iangilman** [comment]
Possibly so... worth exploring! I'm sure there's lots of work that's been done on optimizing delivery of data streams, especially for video; perhaps we could take advantage of some of that somehow. Of course this would only work if you're willing/able to have a special server-side component, but for some scenarios that would be worth it.

**Comment by boskar** [comment]
Few years ago I had a significant boost using SPDY, therefore current solution should be HTTP2. 
Basics are still the same - single tcp session with efficient serial transmission.

**Comment by jetic83** [comment]
Thanks, boskar, this sounds interesting. Is this something which would have to be implemented in OSD, and if so, how? Or is this something that can directly be used by a different URL for the image source? How did you use SPDY a few years ago? With OSD? If so, could you provide a code snipplet, how? Thanks ;)

**Comment by boskar** [comment]
There is no need of any changes in OSD itself or how You implement it in Your website. 
URL stays the same. 
All I had to do was installing mod_spdy for my apache ( iike this: https://www.digitalocean.com/community/tutorials/how-to-install-apache-mod_spdy-on-a-debian-7-vps ). 

Currently for http2 this guide should do: 
https://httpd.apache.org/docs/2.4/mod/mod_http2.html

and then check in google chrome whether it works: 
chrome://net-internals/#http2
You should see session to Your domain.

**Comment by jetic83** [comment]
Thanks a lot! We are using iis 8.5 (Win 2012 R2), which unfortunately does not support http/2. Only iis 10 (Win Server 2016) does. So, we will have a look at the next upgrade.

**Comment by Sslimon** [comment]
Hello everybody

I want to try this with the websockets but I don't know where I have to add this... I thought I could do it with SocketIO. Then, instead of the Ajax request, I would have to trigger an emit and then receive the result/picture.
Do you have a suggestion where I could add that best and most beautiful?

Thanks and all the best
Simon

**Comment by boskar** [comment]
Sounds a bit like reinventing the wheel for me. All the benefit resulting from multiplexing can be easily achieved with much less effort using methods above (SPDY/HTTP2).
Somebody correct me if I'm wrong, but websockets solution would require separate OSD source plugin a dedicated host side software - which at this point is nonexistent. But that's just an opinion...

**Comment by Sslimon** [comment]
I came up with the idea with the websockets because of the following problem: 

I use openslide-python (https://github.com/openslide/openslide-python) on a redhat server with apache (with wsgi). The images are on a windows share. I have mounted the share with cifs. 

The reading of the tiles is extremely slow (If I have the files locally on the server it is not a problem, the tiles are loaded immediately). The more images are loaded at the same time, the more time the reading needs.

Therefore, I thought that I could open the picture only once, and then read out the tiles. I thought that I could call the openslide_open function once when the websocket connects, and later only use the openslide_read_region with the existing openslide_t*.

Is this a stupid idea, or do you have an Idea how I could make the viewer faster?

Many Thanks

ps: I made a small c program to measure the time. When I open 100 different tiles and I use openslide_open for every tile, this needs 15 seconds. When I use openslide_open only once, then the 100 Tiles are loaded in less than a second.

**Comment by jetic83** [comment]
That is of course now stupid idea. You should use always the same openslide object instead of creating always a new one for every tile (very slow). 

I tried websockets before, but this does not help a lot. Since the creation and handling of tiles is still the same, just the transfer protocol is different. 

What is a better idea for you is to keep the openslide object in the session cache and use this object for the tile requests. 
That is what I do.

**Comment by Sslimon** [comment]
I haven't seen it, but I'm already save the openslide objects in the session cache. So I think thats not the problem and you are right, in this case I have no advantages of the websockets...  
I think the problem is the slow connection to the windows share. When I have the file locally, the viewer is very fast and good. 

I will try the IIPSRV, thanks for the suggestion.

**Comment by differenceclouds** [comment]
Hello everyone. I don't really understand most of this discussion. I just know that the animation with openseadragon is very choppy in every case I've seen in comparison to, say, leaflet.js. I would like to disable all mouse acceleration, easing, everything like that, just to get to a base line of performance. I'm having trouble finding the API options for this. Any help would be appreciated! Thanks!!

**Comment by iangilman** [comment]
@differenceclouds You should be able to disable most animation by using `animationTime: 0` in your viewer options. 

Does Safari have an FPS meter like Chrome does? I'd love to hear what you find on the performance front.

**Comment by msalsbery** [comment]
@differenceclouds  In addition to Ian's comment, you may want/need to use the viewer's gestureSettingsTouch option to set flickEnabled to false (see https://openseadragon.github.io/docs/OpenSeadragon.html#.Options). I'd be interested in performance stats as well, as I generally see pretty smooth performance on all devices (even "ancient" tablets)...

@boskar @jetic83 @Sslimon I'm way late to the party here, but I'd add that, with custom tile servers that extract tiles from single images, I've found that using cache control headers (Cache-Control and ETag) correctly and robustly can greatly improve performance by allowing browsers to use cached tiles instead of re-fetching them every time

**Comment by Sslimon** [comment]
@msalsbery Thank you very much for the suggestion. I will try this. 

I'm still using openslide-python, but we use now nfs instead of cifs to access the histoslides, and now it's much faster. Also if a lot of people are using the page at the same time, the performance is good. I'm exited how much faster it gets with the caching.
