### ISSUE TITLE
How to convert to Image Coordinates in CollectionMode?

### ISSUE THREAD

**Issue by rohithn** [openseadragon/openseadragon#1360]
I am displaying around 50 images in one row using collectionMode.
The images have the same height but different widths.

    viewer = OpenSeadragon({
          id: "osd",
          tileSources: fileList,
          viewportMargins: {top: 0, left: 0, right: 0, bottom: 0},
          collectionMode: true,
          collectionTileMargin: 0,
          collectionRows: 1
        });

I am converting the viewport coordinates to image coordinates using the following code:

      viewer.addHandler('canvas-click', function(event) {
          var tiledImage = viewer.world.getItemAt(0);
          var viewportPoint = viewer.viewport.pointFromPixel(event.position);
          var pointOnImage = tiledImage.viewportToImageCoordinates(viewportPoint.x, viewportPoint.y, true);
        });
    
The `pointOnImage` is correct when the click is on the first image. But if I click on the say 10th image, the `x` value of `pointOnImage` coordinate is wrong. I think it is because I am using `viewer.world.getItemAt(0);`, and OSD is calculating the coordinates based on the first image. Is that correct? If so, what is the correct way of calculating the values while accounting for the difference in image widths?

**Comment by iangilman** [comment]
You're absolutely correct. If you want the tenth image, it's `viewer.world.getItemAt(9)`. If you want to loop through all the images, you can find out how many there are with `viewer.world.getItemCount()`.

**Comment by iangilman** [comment]
Is it really image coordinates you want? Each image gets its own coordinate system, so comparing the coordinates of one image to another image doesn't necessarily make sense. Viewport coordinates are common to all images, so if you're trying to compare two images, that's what you should use. For more on the coordinate system, see:

http://openseadragon.github.io/examples/viewport-coordinates/

At any rate, if you've got a `viewportPoint` that points to the box labeled D002, and you want to find dX in the image coordinates of that 4th image, it would be:

```
var tiledImage = viewer.world.getItemAt(3);
var pointOnImage = tiledImage.viewportToImageCoordinates(viewportPoint.x, viewportPoint.y, true);
var dx = pointOnImage.x;
```

This is not just the coordinate point on that image, it's also the distance from the left side of the image, since image coordinates always start at 0.

If, instead, you're looking for the dX in viewport coordinates, it would be:

```
var bounds = tiledImage.getBounds();
var dx = viewportPoint.x - bounds.x;
```

If none of this helps, it might be useful for me to know what you're trying to accomplish with these values.

**Comment by yuan67-top** [comment]
> 你说得完全正确。如果你想要第十张图片，那就是`viewer.world.getItemAt(9)`。如果你想遍历所有图片，你可以用来查看有多少张图片`viewer.world.getItemCount()`。

How can I know which image I have clicked on?

**Comment by iangilman** [comment]
This is the general recipe for knowing which image has been clicked on:

```
viewer.addHandler('canvas-click', (event) => {
    const viewportPortPoint = viewer.viewport.pointFromPixel(event.position);

    const count = viewer.world.getItemCount();
    for (let i = 0; i < count; i++) {
        const tiledImage = viewer.world.getItemAt(i);
        const viewportBounds = tiledImage.viewport.getBounds(true);
        if (viewportBounds.containsPoint(viewportPortPoint)) {
            console.log(`Clicked on image ${i}`);
            break;
        }
    }
});
```
