### ISSUE TITLE
Pyramid from base line mosaic

### ISSUE THREAD

**Issue by arrigoc55** [openseadragon/openseadragon#1363]
I am new of OpenSeaDrangon and may be this problem has been already discussed and solved. I have a mosaic of jpeg images with the following characteristics (the xml file [z0.txt] is attached):

  Format="jpg"
  Overlap="0"
  TileSize="512"

  Size 
    Height="96768"
    Width="16384"

This mosaic is coming from a BigTiff image processed with VIPS. In my program I elaborate these images and then I wish to build a pyramid image suitable for OpenSeaDragon. The names of the images follow the rule of the dzi baseline image: from 0_0.jpg to 31_188.jpg . 
How can I build the pyramid image starting from this base line mosaic? Thank you for your help.
[z0.txt](https://github.com/openseadragon/openseadragon/files/1555332/z0.txt)

**Comment by iangilman** [comment]
So you have the base of the pyramid but not any of the other levels? And you don't have it all together as a single image? Is it possible for you to combine it into a single image (and then run it through the VIPS DZI conversion)? That would probably be the easiest. Otherwise you'll have to build something custom.

The algorithm for a custom script that took the base layer of the pyramid and made the other levels would be to take the upper left four tiles (2 x 2) and combine them and scale them down into a single 512 pixel tile. Then grab the next four tiles and do the same, etc. until you've done the entire level. Then do the next level the same way, but based on the level you just completed. Keep going until the entire level is approximately 1px.

For more information on the DZI format, see: https://github.com/openseadragon/openseadragon/wiki/The-DZI-File-Format

**Comment by arrigo55** [comment]
Thank you for your reply. Yes I have the base of the pyramid and I ned to build the other levels. Unfortunately I cannot combine all the tiles in a single image because it is too big. If anybody knows how to build a single image starting from 81600 tiles (512x512 each) please let me know :) Otherwise I will try to write a script to build the pyramid levels.

**Comment by iangilman** [comment]
Presumably VIPS can be used to make a blank image of the appropriate size and then copy all of the individual tiles into it. You'd still have to write a script to make it do that, but that might be easier than writing a script to build the pyramid levels.

**Comment by jcupitt** [comment]
Hello, libvips has an `arrayjoin` operator that can join a set of tiles together into a large image:

http://jcupitt.github.io/libvips/API/current/libvips-conversion.html#vips-arrayjoin

You can use it like this (on linux):

```
$ vips arrayjoin "$(ls *.jpg | sort -t_ -k2g -k1g)" x.tif --across 20
```

That will load all the JPG image in the current directory and assemble them into a huge grid, 20 images across. You'd need to check the size of your grid, obviously. 

The `$()` thing sorts the filenames of the form `x_y.jpg` by y first, then x, in numeric order. Without that the tiles will be transposed, annoyingly.

That's assuming overlap 0. If your tiles have an overlap, you'll need to set the `hspacing` and `vspacing` options to control how tiles are positioned. For example:

```
$ vips arrayjoin "$(ls *.jpg | sort -t_ -k2g -k1g)" x.tif --across 20 --hspacing 254 --vspacing 254
```

Will position the tiles every 254 pixels horizontally and vertically.

`arrayjoin` has to be able to open all of the input images, so it needs a lot of file descriptors. Most linuxes default to a maximum of 1024 files open at once per process, so you'll probably need to raise that number. Usually you just edit a couple of config files and log out and in again. I set my system to 65536, but you can use any number. 

Rather than writing a tiff, you can set a deepzoom pyramid as the output. For example:

```
$ vips arrayjoin "$(ls *.jpg | sort -t_ -k2g -k1g)" x.dz --across 20
```

Now it'll directly write a deepzoom (`.dz`) pyramid called `x` from your huge tile array.

**Comment by jcupitt** [comment]
Oh, I just noticed you have 80,000 tiles :) It should work, but you will need a lot of memory.

**Comment by arrigoc55** [comment]
Thank you John for your precious suggestion. I am using Mac and Windows,
not Linux, but I will find the way to use arrayjoin with them. Yes I have
huge images (95,000 tiles the last one), but my specific area of interest
(digital cytology) requires this kind of images.
All the best
Arrigo

**Comment by jcupitt** [comment]
It should work on macOS, though I've not tried raising the number of files limit there. 

WIndows unfortunately has a hard limit of 2000 open files per process which you cannot change, so you'd need to find a different solution there. You could possibly assemble the mosaic in sections I suppose.
