### ISSUE TITLE
Overriding "setFullPage" function, THIS[ this.hash ] visibility problem

### ISSUE THREAD

**Issue by Medwar** [openseadragon/openseadragon#1366]
I am trying to override the standard "Viewer.setFullPage" function.
First I tried to simply reproduce it work from outside, using the code below. 
Below I replaced the standard code that works normally by "...".
But the lines that are left are not working because it doesn't see THIS[ this.hash ] structure.

Could you please help to find a solution?
I am not very experienced with JS.
Perhaps the structure could be replaced by my own one. But I suppose that other standard functions are using this structure so it has to be populated for OSD to work correctly. 
```
(function($) {
    $.Viewer.prototype.setFullPage = function( fullPage ) {
...       
            THIS[ this.hash ].prevElementParent = this.element.parentNode;
            THIS[ this.hash ].prevNextSibling = this.element.nextSibling;
            THIS[ this.hash ].prevElementWidth = this.element.style.width;
            THIS[ this.hash ].prevElementHeight = this.element.style.height;
...
           THIS[ this.hash ].fullPage = true;
...
           THIS[ this.hash ].prevElementParent.insertBefore(
                this.element,
                THIS[ this.hash ].prevNextSibling
            );
...
            THIS[ this.hash ].fullPage = false;
...
    };
}(OpenSeadragon));
```
P.S.
I have tried writing this parameters to viewer properties like 
this.prevElementParent = this.element.parentNode;   ... etc. 
From the first glance it seems to work ok, but I can't be sure if I didn't brake anything.
 
But there's also another issue in the same function:
$.delegate( this, onContainerEnter )( {} );
$.delegate( this, onContainerExit )( {} );
also doesn't work in when trying to override the same function in external JS.
Is there a way how to overcome this in external sript?

**Comment by Medwar** [comment]
Thank you, Ian!
Here I was trying to make fullscreen work for one of higher level <div> elements instead of the viewer. 
I rather easily succeded with it by creating my custom fullscreen button. It works everywhere, except apple devices, where fullscreen is not supported. But OSD does fullPage very good on apple, especially if you scroll the page to hide the address bar before going fullPage. In chrome the OSD image takes all of the screen of IPhone, and that is great.
I wanted to make use of OSD logic. 
And I succeeded, I've overwritten the 'setFullPage', 'isFullScreen', so they didn't need 'THIS' anymore.
But unfortunately that didn't help me with "perfect fullPage" on apple. 
I mostly understand what the problem is and will search the web for a solution.  

And second, I am experimenting. I want to understand to what extent OSD objects are extendable, want to learn how to write plugins. I will try to clean up the code a bit and share it later, so to ask with example. During the development new questions will certainly appear.

**Comment by Medwar** [comment]
May I ask one question for understanding - why everything stored in structure THIS was not just put into public properties of the objects (e.g. like Viewer.hash, Viewer.element, etc.) -
Are there any bad sides in such approach?

**Comment by iangilman** [comment]
The idea with a private variable storage like THIS is that it protects people from meddling with parts of the system they shouldn't be and breaking things.

I don't think that protection is worth it though (that was set up before I was involved in the project). The system I've been recommending we move towards is having those "private" properties be publicly attached to the object, but to have their names prefixed with `_` as a warning that they are private, and to not publicly document them. That way they are accessible if need be,  but you're not encouraged to use them (since you really should know what you're doing when you use them). One other warning about such "private" properties is that since they are not official parts of the API they are subject to change.

I would be in favor of a patch that took all of the THIS properties and added them directly to the Viewer in the way I described here, if you're up for tackling such a thing.

Another extensibility problem we have is "private" functions that are only accessible inside the source file. Again, I would attach those directly to the objects but prefix them with `_` and not document them.

That said, it's possible some of these "private" properties and functions should actually be elevated to public status. Ideally any plugin should be able to do its work entirely with just publicly available properties and functions, so if there are things we need to expose in order to become more extensible, we should do so.

I'm delighted that you're looking into this stuff!
