### ISSUE TITLE
error while loading tif : "Image load exceeded timeout"

### ISSUE THREAD

**Issue by johnico** [openseadragon/openseadragon#1378]
Hi .
1.  I am loading tif with a cgi-bin application and the loading is very slow
is there any way to cache the tiles or load it in a fast way? 

my tif loading is like the following;

```
 var tileSources = { tileSource:url + "/cgi-bin/ImageServer.cgi/"+imageLocation +".dzi" };
                        openViewer(viewer,tileSources);
```

2. I am getting an error : "Image load exceeded timeout" . , what is mean and how can I fix it ?

**Comment by iangilman** [comment]
To give a longer timeout for the tiles you'll want to set he OpenSeadragon timeout value. Ideally this would just be `timeout: 60000` (or whatever number you want, in milliseconds), but we have a bug with that route:

https://github.com/openseadragon/openseadragon/issues/1279

Until that bug is fixed (which you're welcome to do; it shouldn't be too hard) you have to use this:

```
OpenSeadragon.DEFAULT_SETTINGS.timeout = 60000; // or whatever number
```

**Comment by johnico** [comment]
But how that going to improve the loading ? And load the image fast as possible

Another question 
Using dzi with folder that already located on the server would be better than using cgi server ?

**Comment by iangilman** [comment]
Yeah, changing the timeout won't improve the loading speed. The loading speed is entirely up to how fast your server and network connection are; OSD tries to load it as fast as you can.

An already converted DZI would definitely be faster than CGI, since there's no processing needed.
