### ISSUE TITLE
How to Create new Buttons and Append them to the Existing Toolbar?

### ISSUE THREAD

**Issue by RockGuitarist1** [openseadragon/openseadragon#1387]
So I am trying to add a Print button to the existing toolbar that exists on the Viewer and keep running into some issues. Here is the code that I am using:

```
let viewer = OpenSeaDragon({
      id: 'openseadragon',
      prefixUrl: `/openseadragon/images/`,
      sequenceMode: true,
      showReferenceStrip: true,
      showRotationControl: true,
      showNavigator: true,
      tileSources: tileSourcesArray
    });
```

```
viewer.addHandler('open', () => {
      let printButton = new OpenSeaDragon.Button({
        tooltip: 'Print',
        srcRest: `/images/Browser_Chrome.png`,
        srcGroup: `/images/Browser_Chrome.png`,
        srcHover: `/images/Browser_Chrome.png`,
        srcDown: `/images/Browser_Chrome.png`,
        onClick: this.print
      });

      viewer.addControl(printButton, { anchor: OpenSeaDragon.ControlAnchor.TOP_LEFT });
    });
```

The addControl function throws this error: `Cannot set property 'position' of undefined`

I want this new button to appear right after the "Next Page" button inside of the viewer. I am creating this button the right way? I am not creating a button with HTML, so I am not assigning an element property to the button.

**Comment by iangilman** [comment]
Strange... that certainly seems like it should work. The only issue I see is your capitalization on `OpenSeadragon` is wrong, but I assume that's just in this example code, since otherwise none of it would work.

Could you share a codepen of the problem so I can take a closer look?

Btw, you're going to want to add this new button to the button group in the upper left, I assume... Unfortunately we don't have a good mechanism for that. I can suggest some additions to `OpenSeadragon.ButtonGroup` to make it possible, though.

**Comment by RockGuitarist1** [comment]
Yep, here is one. It's returning the same error that I am getting.

[Codepen](https://codepen.io/anon/pen/BYaZVq)

**Comment by iangilman** [comment]
I see... Looks like addControl wants an element, not a Button. This fixes it:

```
 viewer.addControl(printButton.element, { anchor: OpenSeadragon.ControlAnchor.TOP_LEFT });
```

Looks like we could use some better documentation on that function!

**Comment by RockGuitarist1** [comment]
Great! It's always the little things. Thank you so much!
