### ISSUE TITLE
slow performance in macOS Safari with 63 x 32768 * 32768 VIPS created DZIs

### ISSUE THREAD

**Issue by jason-green-io** [openseadragon/openseadragon#1396]
Panning and initial zooming in is slow on desktop. iOS Safari tries, but fails to load the page. Seeing that I have 1px images in level 0, why is it so slow manipulating the home/default zoom level?

https://minecraft.greener.ca/bigmap/osd.html

**Comment by iangilman** [comment]
I think it's probably because there are 63 images. For one thing, it needs to load 63 DZI files. Then there are all the tiles... Looks like it loads about 150 tiles just at the beginning (at least on my browser). This is partially due to the fact that the navigator is open (otherwise it would just be loading tiles for where you are).

Might it be possible to combine all these images into a single image and then convert it into a DZI? That should be much more efficient. If not, there are some things you can try:

* Turn the navigator off
* Store all of the DZI information in a single JSON or JavaScript file and load it once (saving 62 file loads) and then use the "Inline Configuration" technique described in http://openseadragon.github.io/examples/tilesource-dzi/
* Try `immediateRender: true` when you create the viewer and see if that reduces the tile loads

We would like to be able to support large collections like this. The key is to have single tiles that aggregate the low resolution data for all of the images, so you can load just one or two tiles and be able to display zoomed out versions of everything. The issue for that is https://github.com/openseadragon/openseadragon/issues/67, and no one has tackled it yet.
