### ISSUE TITLE
Support square edge tiles that are padded rather than cropped.

### ISSUE THREAD

**Issue by MarkusAnthony** [openseadragon/openseadragon#1418]
Hey Guys,

Hoping all will understand what I mean... For Dicom Supplement 145 all tiles are to be square.

Section 315: An image object describes one level. Levels are composed of tiles, and so may be sparse (not all tiles present). For any level the resolution is fixed for all tiles in the level, and all tiles have the same width and height, and may not overlap, although the level may be sparse and any number of tiles may be absent.

So I have a utility that creates square tiles for all levels. At full zoom everything looks great.

The problem is during zooming. For example, if there are 145 rows/columns where the cells are 256x256 when you zoom out to the next level it appears that OpenSeaDragon creates 72 rows/column (256x256) and one that is (256x128). The square tile that is requested and put in that cell gets distorted.

We are using dzi.

I would like OpenSeaDragon to keep all cells square so no images are distorted.

I have an online example if someone wants to work with me privately on it.

-Markus

![zoomedin](https://user-images.githubusercontent.com/3238156/37129077-f9b7672c-2231-11e8-9ab8-6c93bb28a739.JPG)
![zoomedout](https://user-images.githubusercontent.com/3238156/37129078-f9ce91ae-2231-11e8-9dbe-19568acdfa4a.JPG)

**Comment by iangilman** [comment]
Yes, the DZI file format specifies that edge tiles get cropped. We don't support uncropped edge tiles. 

Can you explain again why you need them uncropped? Sounds like there's a spec that asks for square tiles? Really, the tiles are still square except for the cropping.

You can read more about DZI here:

https://github.com/openseadragon/openseadragon/wiki/The-DZI-File-Format

...and for reference, this topic (of padding versus cropping of edge tiles) has been discussed before in https://github.com/openseadragon/openseadragon/issues/234 and https://github.com/openseadragon/openseadragon/issues/647.

**Comment by MarkusAnthony** [comment]
Hey Ian,

I mentioned the reason above but here is more detail. Digital pathology is a relatively new field compared to digital radiology. Radiology uses the DICOM standard for image and metadata storage.  DICOM has updated there standard (supplement 145) to include whole slide imaging and pyramid files. Most vendors dealing with digital pathology will probably follow the [DICOM 145 supplement](ftp://medical.nema.org/medical/dicom/final/sup145_ft.pdf) standard for pyramid files.

The standard states: 

Section 315: An image object describes one level. Levels are composed of tiles, and so may be sparse (not all tiles present). For any level the resolution is fixed for all tiles in the level, and **all tiles have the same width and height**, and may not overlap, although the level may be sparse and any number of tiles may be absent.

So we must include only square images in our DICOM fileset. 

Is this limitation only for dzi or is it a limitation for OpenSeaDragon as a whole?

Can we use a difference tile source (zoomify, tms...). Will any of these make a difference?

-Markus

**Comment by iangilman** [comment]
Thank  you for filling in the context for me. I was not previously aware of this standard. 

Regardless of what tile source you use, OpenSeadragon does not currently support edge tiles that are padded rather than cropped. I would welcome a patch to change that, and can provide pointers on where to start. It may be as simple as updating the values in the `drawImage` call in `Tile.drawCanvas`:

https://github.com/openseadragon/openseadragon/blob/master/src/tile.js#L360

...so instead of `rendered.canvas.width` and `rendered.canvas.height` we match the aspect ratio of `size.x` and `size.y`. We might not even need to do any additional setup (telling the system that it's a padded tile format), since I can't think of any time where we actually want the tiles to be distorted.

Would you be up for giving that a try?

**Comment by MarkusAnthony** [comment]
Thanks Ian. I will look into it soon!

**Comment by MarkusAnthony** [comment]
Hey @iangilman, can you give me a little more detail on what the change is and I will try it out asap.

**Comment by iangilman** [comment]
I'm guessing it should be something like:

```
        var sourceWidth = rendered.canvas.width;
        var sourceHeight = rendered.canvas.height;
        if (size.y < size.x) {
          sourceHeight = sourceWidth * (size.y / size.x);
        } else if (size.x < size.y) {
          sourceWidth = sourceHeight * (size.x / size.y);
        }

        context.drawImage(
            rendered.canvas,
            0,
            0,
            sourceWidth,
            sourceHeight,
            position.x,
            position.y,
            size.x,
            size.y
        );
```

**Comment by MarkusAnthony** [comment]
Hey Ian. It looks like it works for the most part. There is something funky going on with the right/bottom corner. I will look into it and get back to you. I can make the pyramid and dzi public if needed.

**Comment by iangilman** [comment]
Good point! That code is based on the assumption that even if we don't want the full tile we either want the full width or the full height. For the corner tile, that is of course not the case. That might take a bit more work, since the info we need probably isn't available in this function, and we'll have to get it piped in from somewhere else in the system (like the tile source or the TiledImage). 

I think having access to that DZI would be helpful.

**Comment by MarkusAnthony** [comment]
@iangilman I will email you the dzi and the pyramid location.

**Comment by iangilman** [comment]
Great, thank you!
