### ISSUE TITLE
Problem with changing the tilesource

### ISSUE THREAD

**Issue by AdnaanShaikh** [openseadragon/openseadragon#1428]
We are working on osd for quite sometime, facing an issue with loading tiles for image when the tilesource is changed.
Ignoring tile a.Tile loaded before reset
We tried to remove the old tilessource before adding new one, tried replacing it with new one, but it takes time to do somethings with old tilesource before loading the new one

In the sample code you can zoom into the image and press next button to change tilesource but it takes time before new image is visible on screen.
Sample code:
https://codepen.io/AdnaanS/pen/EEvwye

Are we missing something?
Any help is appreciated.

**Comment by iangilman** [comment]
It looks like your tile server is just really slow. Here's the initial load on my browser (Mac Firefox):

![image](https://user-images.githubusercontent.com/338989/37936945-66a3054c-310c-11e8-8fcf-c737a7fc6ade.png)

That's 5 seconds to load about 20 tiles.

Given that you've got that kind of delay, of course you're going to see blank for a little bit, since you are removing the previous image before the new one loads. Changing it like so should be better:

```
function next() {
  var self = this;
  self.imageCounter = (imageCounter+1)%9;
  // self.viewer.world.removeItem(self.viewer.world.getItemAt(0));
  self.viewer.addTiledImage({
      tileSource: {
          y: 0,
          x: 0,
          height: 3300,
          width: 2550,
          tileOverlap: 2,
          tileSize: 250,
          getTileUrl: function (level, x, y) {
              var url = base + (self.imageCounter+1) + "/" + level + "_" + x + "_" + y;
              return url;
          }
      },
      success: function () {
          self.viewer.world.removeItem(self.viewer.world.getItemAt(0));
      }
  });
}
```

Of course you might still want to let the user know that the change is happening, via a spinner or something, if you can't improve the server speed.

Also note that the `success` function just means the image has been added, not that any tiles have necessarily loaded. If you want to wait for the first tile to load, you can use the `tile-loaded` event. Here's an example: https://codepen.io/iangilman/pen/BrmLKP

...or if you want to wait for the image to be fully loaded (which will take longer, but you won't see it be blurry for a moment), you can use the `fully-loaded-change` event. https://github.com/openseadragon/openseadragon/issues/1257 has some examples for how to use that.

Another strategy is to preload the next image even before the user asks for it; this way it's already ready when they hit the button.

**Comment by sraza123** [comment]
Thanks for the response, this helped alot

**Comment by Adnaan03** [comment]
thanks for the help
