### ISSUE TITLE
dzi on the fly

### ISSUE THREAD

**Issue by adv1023** [openseadragon/openseadragon#1437]
I am working with MEAN on Ubuntu. I have nearly 1,000,000 images so I can't store the DZI files. What is the best way to create DZI files on the fly?  Create the DZI files only when the image is viewed.

**Comment by boskar** [comment]
It all depends on Your input file format and size. I'm using https://github.com/ruven/iipsrv

**Comment by iangilman** [comment]
How big are these images? If they are less than 2000 pixels across, you could use the simple image tileSource:

http://openseadragon.github.io/examples/tilesource-image/

Otherwise take a look at:

http://openseadragon.github.io/examples/creating-zooming-images/

There are a couple of server options mentioned (like the one @boskar listed above), or you could set up your own server side component based on one of the other tools.

**Comment by adv1023** [comment]
Thank you.
