### ISSUE TITLE
'Book' style presentation for hundreds of dzi's

### ISSUE THREAD

**Issue by SamHall** [openseadragon/openseadragon#1451]
I'm working on presenting hundreds of pages of old documents. While I can do this with collection mode, and presenting 100 at a time in selection buttons, I really like this demo (based on Mirador), and the universal viewer as well (universalviewer.io)
http://iangilman.com/osd/test/demo/m2/

I believe all based on IIIF and JSON, and other things I can't easily wrap my head around.

Are there any similar approaches that could utilize DZIs, and not require XML or JSON to feed it?
i.e. - I'm okay with hundreds of lines of code since this won't grow beyond it.
(FYI - My dzi's live on Amazon S3.)

Thanks.

**Comment by iangilman** [comment]
Which aspect of that demo are you thinking of? The large scrolling list of thumbnails? The sideways scrolling page view?

Anyway, depending on what you're trying to do, it could be easy or hard. You certainly don't need IIIF or JSON or XML... In your code you can make an array of all of your images (which I suppose is what you're already doing with collection mode). Perhaps the first step is to step away from collection mode and learn how to lay things out yourself (if you want more control over that). Here's a quick example:

```
viewer.addHandler('open', function() {
  var count = viewer.world.getItemCount();
  var i, tiledImage, bounds;
  var pos = new OpenSeadragon.Point(0, 0);
  for (i = 0; i < count; i++) {
    tiledImage = viewer.world.getItemAt(i);
    bounds = tiledImage.getBounds();
    tiledImage.setPosition(pos, true);
    pos.x += bounds.width;
  }
});
```

**Comment by SamHall** [comment]
Actually, I probably need some examples of how to properly utilize an array with DZIs.  
What I like about that demo is how it presents the thumbnails, and transitions to the horizontal scroll, but with options to return to the thumbnail view.

**Comment by iangilman** [comment]
By an array of DZIs, I just mean like this:

```
var tileSources = [
  '/content/a.dzi',
  '/content/b.dzi',
  '/content/c.dzi'
];

var viewer = OpenSeadragon({
  tileSources: tileSources,
  // More options
});
```

Unfortunately the thumbnail to horizontal scroll transition is pretty tricky, mostly because the stuff needed to make the thumbnails scroll nicely. Anyway, you're certainly welcome to use the code from that demo if you want!

**Comment by SamHall** [comment]
I'm loading arrays that way now, but all within the page's code vs. a sequential load from a directory. Not that it matters too much for manageable numbers.
I've been eyeing the demo code. 
If by some miracle I get close to figuring it out and getting it to work I'll certainly reach back out for help.
:  )
Thanks.

**Comment by SamHall** [comment]
iangilman - 
Do you know of a way to utilize DZI collections with the Mirador presentation method?
I've read about iiif, but cannot find a straightforward method of generating something 'ingestible' by the demo, given a collection of DZI folders/files.

**Comment by iangilman** [comment]
I don't have a lot of direct experience with Mirador. You might try asking over at http://projectmirador.org/. It's also possible @aeschylus or @rsinghal could chime in here. 👋

**Comment by iangilman** [comment]
As as for loading sequentially, why do you want to do that? I know one concern is how long it takes to load all of the DZI files when there are 100 of them. My recommendation there is to store the DZI data directly in the code, or in a single file that contains info for all of them. Then load them directly using the "inline configuration" technique shown on this page:

http://openseadragon.github.io/examples/tilesource-dzi/

Here's an example of how to parse the information that's in a DZI file so you can use it inline:

https://codepen.io/iangilman/pen/gpejpJ

Once you've done that, there's no problem and loading hundreds of them, because the individual tiles won't be loaded until they needed. That said, if you zoom out enough that all of the hundreds are on screen at the same time, that will still be hundreds of tiles. You want to stay zoomed in enough that you're only showing a reasonable number of items.

**Comment by iangilman** [comment]
Cool… I look forward to seeing it in action! Perhaps I'll have more suggestions once I get a better idea of how you're planning on putting it all together.

And yes, getting into IIIF might be more work than you need to do at this point.
