### ISSUE TITLE
Can I control how the full-res image is displayed - unaliased??

### ISSUE THREAD

**Issue by robertlight** [openseadragon/openseadragon#1463]
If I zoom way in on the the image, I get an aliased view of the real image.

Is there any way I can get full fidelity in my full-res image? ie; no anti-aliasing?

I really want to have my pixels "fat-pixeled" when the zoom goes beyond 1:1 pixel-for-pixel rendering.... I don't want the images "smoothed" or messed with in any way.

For example:  here's what it looks like in OSD (zoomed in to full-res):
![zoomed-in-osd-image](https://user-images.githubusercontent.com/5215735/39842637-3628acca-53b5-11e8-8983-d8a2854ef022.png)

But here is the _real_ full-res image - notice that the pixels aren't anti-aliased.
![zoomed-in-gimp-image](https://user-images.githubusercontent.com/5215735/39842648-47e37a9e-53b5-11e8-8128-ebe50f8ece29.png)

**Comment by iangilman** [comment]
See the discussion in https://github.com/openseadragon/openseadragon/issues/1455. Now that we have a few requests for this, I'll mark this issue as an enhancement in the hopes someone can add it as an official feature.

It may be as simple as:

```
viewer.drawer.context.imageSmoothingEnabled = false;
```

...Along with adding the appropriate option to turn it on, of course.

It's possible the Drawer's sketContext needs it as well.

**Comment by Mayank1728** [comment]
Hey @robertlight ! I would like to contribute if possible.

**Comment by iangilman** [comment]
@Mayank1728 That would be great! Let me know if you need any pointers...

**Comment by iangilman** [comment]
@Mayank1728 Wonderful! Your projects look good :) 

Here's our contributing guide: https://github.com/openseadragon/openseadragon/blob/master/CONTRIBUTING.md 

Now that I'm looking at this issue more closely, though, I'm realizing it was already fixed by https://github.com/openseadragon/openseadragon/pull/1507! I know you commented on another issue that could use work, so I guess maybe that's the one to get started with. Can you remind me which one that was? 

Meanwhile, I'll close this issue since it's already fixed :)
