### ISSUE TITLE
Q: How to avoid the flicker issue of a multi-image API ?

### ISSUE THREAD

**Issue by M-Momtaz** [openseadragon/openseadragon#1468]
Hello, I have a new version of `OpenSeadragon Image Flipbook` demo. 
I need to avoid the flicker effect occurred when button `go` is clicked.
[new version](https://codepen.io/m-momtaz/pen/xjzVzp)

Reference :  #1238

**Comment by iangilman** [comment]
Hmmm.... I'm actually not sure why your modified version is flickering. Anyway, you don't need a lot of it since you're having the user click manually, so here's a different approach:

https://codepen.io/iangilman/pen/erjyBP

This assumes there's a brief pause between clicking next and clicking it again (so it can preload the following image).
