### ISSUE TITLE
Odd glitching at level change, missing navigation image

### ISSUE THREAD

**Issue by darkmich** [openseadragon/openseadragon#1473]
I'm working on a site to show virtual microscope slides at:
http://slides.cldavis.org/IAAAM/test.html

I'm trying to use Digitalocean's version of S3 and a CDN (keycdn) to serve the files. I'm only using levels 9-15 to keep the number of files down to a minimum.

I've mostly got the switching working; however, the navigator doesn't show an image now and I get weird glitching while zooming in and out. I think this might be the way I've got the addTiledImage coded, but that was the only way I could get it working. Any suggestions are greatly appreciated - I'm sure this is due to my lack of Javascript ability!

Relevant code:
Viewer setup
```
    var viewer = OpenSeadragon({
        id: "view",
        prefixUrl: "/openseadragon/images/",
        showNavigator:  true,
        navigatorAutoFade: true,
        autohidecontrols: true,
        showRotationControl: false,
});
```

Slide change code:

```
function changeImage(image,mpp,height,width) {

var TS = new OpenSeadragon.TileSource( {
        height: height,
        width: width,
        tileSize: 254,
        tileOverlap: 1,
        minLevel: 9,
        maxLevel: 15,
        getTileUrl: function( level, x, y ){
                return "http://virtualslides-c103.kxcdn.com/IAAAM2018/" + image$
        }
});

viewer.scalebar({
xOffset: 50,
yOffset: 50,
barThickness: 3,
stayInsideImage: true,
});

viewer.scalebar({
pixelsPerMeter: mpp ? (1e6 / mpp) : 0,
});
}
```

**Comment by iangilman** [comment]
I am just guessing, but I'd say you're not seeing anything in the navigator because you don't have tiles below level 9; the navigator is very zoomed out, so it wants those lower level tiles. We don't have a mechanism for it to use the higher level tiles if the lower level ones aren't available, so it just gives up.

By glitching, do you mean the distortion on the bottom tiles? This looks like your edge tiles are padded instead of cropped. I recommend cropping them instead if you can. You can see some discussion on this in https://github.com/openseadragon/openseadragon/issues/1418. If you need to have them padded, you'll need to build the latest master of OpenSeadragon, since we haven't yet released that fix.

**Comment by darkmich** [comment]
Ok - thanks! It seems to work when hosted on the server as opposed to S3, so I'll probably just switch to that route. I appreciate the look!
