### ISSUE TITLE
Conversion of external canvas image X and Y Vertices web point(not openseadragon) to ImagePoint of Openseadragon 

### ISSUE THREAD

**Issue by vinaymuthanna0727** [openseadragon/openseadragon#1475]
HI ALL,

I am getting x and y vertices details from external canvas image (not on onclick event of openseadragon) .Now i need to convert x and y point(web point) to image point and draw a line on openseadragon viewer on load (on load of the image viewer)

Here is the sample code ,But it is not working any suggestion.
viewer is initialized .

 
   position.x = imageLength - experimentShapes[i].Points[0].X;
   position.y = imageLength - experimentShapes[i].Points[0].Y;
   var webPoint = position;
    var viewportPoint = viewer.viewport.pointFromPixel(webPoint);
    var imagePoint = viewer.viewport.viewportToImageCoordinates(viewportPoint);

**Comment by iangilman** [comment]
It sounds like you want to be able to convert from the external image coordinates into whatever coordinates you need to draw the line with (which depends on which plugin you're using to draw the line with... some use viewport coordinates and others use image coordinates). Which plugin are you using?

If the plugin uses image coordinates, you're already set. If it uses viewport coordinates, you just need to use `imageToViewportCoordinates`.

Or maybe your external image coordinates are not full image coordinates because they are thumbnails that are scaled down? If that's the case, you'll have to convert them to image coordinates by multiplying by however much they are scaled down. At any rate, you don't want to convert those coordinates directly into viewport coordinates without going through image coordinates, because your external image isn't zoomed/panned the same way as the OpenSeadragon viewport is.

**Comment by vinaymuthanna0727** [comment]
Thanks iangilman . i will try use imageToViewportCoordinates and check it.
will this work for conversion 

var imagePoint = new OpenSeadragon.Point(X,Y);
const viewerPoint = tiledImage.imageToViewportCoordinates(imagePoint);

or how to convert to imageToViewportCoordinates .Any example please

**Comment by iangilman** [comment]
Yes, perfect! Let me know how it goes :)

**Comment by vinaymuthanna0727** [comment]
Its working fine..
Thanks
