### ISSUE TITLE
Overlays do not align with image - how to properly use pixel coordinates ?

### ISSUE THREAD

**Issue by filak** [openseadragon/openseadragon#1491]
I am trying to higlight words in image.  The words coordinates are in pixels: [x, y, w, h]

        this.viewer.open([
        {
          tileSource: images[0],
          x: 0
        }
        ]);
...
    
      var Point1 = new OpenSeadragon.Point(x, y);
      var Point2 = new OpenSeadragon.Point(x + w, y + h);
      var topLeft = this.viewer.viewport.windowToImageCoordinates(Point1);
      var bottomRight = this.viewer.viewport.windowToImageCoordinates(Point2);

      this.viewer.addOverlay({
          location: new OpenSeadragon.Rect(topLeft.x,
                                         topLeft.y,
                                         bottomRight.x - topLeft.x,
                                         bottomRight.y - topLeft.y)
      });

But the rectangles do not align with image.

**Comment by filak** [comment]
UPDATE: This way it works:

        this.viewer.addTiledImage({
           tileSource: images[0]
        });
...

      var Point1 = new OpenSeadragon.Point(x, y);
      var Point2 = new OpenSeadragon.Point(x + w, y + h);
      var topLeft = this.viewer.viewport.imageToViewportCoordinates(Point1);
      var bottomRight = this.viewer.viewport.imageToViewportCoordinates(Point2);

      this.viewer.addOverlay({
          location: new OpenSeadragon.Rect(topLeft.x,
                                           topLeft.y,
                                           bottomRight.x - topLeft.x,
                                           bottomRight.y - topLeft.y)
      });

Though when navigating between pages I see a lot of:

[Viewport.imageToViewportCoordinates] is not accurate with multi-image; use TiledImage.imageToViewportCoordinates instead.

Images are being added to the viewer. I have tried to remove the old image before adding a new one with this.viewer.world.removeAll(); 

but it somehow resets the viewport so the overlay coordinates get messed up.

**Comment by iangilman** [comment]
If the rectangles are in image pixels, you definitely want `imageToViewportCoordinates` like you're using in the second example. It shouldn't matter how you open the image, though, so you can use `open` instead of `addTiledImage`, which will take care of the multi image issue. I assume you don't need to have multiple images in the viewer at once? If you do, you just need to call `imageToViewportCoordinates` on each image separately. 

BTW, either way, `imageToViewportCoordinates` may not work until the image is loaded, so you might want to wrap your overlay adding code in `viewer.addHandler('open', ... )`.

**Comment by filak** [comment]
Thank you, now ti works!

https://github.com/filak/wck/blob/7fff2b62e94f24989d0648a9fe20cbb8f5e9e124/src/app/book/iiif-viewer/iiif-viewer.component.ts

**Comment by iangilman** [comment]
Excellent :)
