### ISSUE TITLE
showing and hiding elements depending on zoom level

### ISSUE THREAD

**Issue by Salitehkat** [openseadragon/openseadragon#1511]
Hi, 
I am trying to show and hide elements depending on the zoom level. I grabbed the function that tracks the zoom level on this [example](https://openseadragon.github.io/examples/viewport-coordinates/) and added the conditions. Is this approach correct/clean or is there a better way to achieve it?

here is the code I am using: 

	
	
`				  var updateZoom = function() {
                 var zoom = viewer.viewport.getZoom(true);
                 var imageZoom = viewer.viewport.viewportToImageZoom(zoom);
				 

                 zoomEl.innerHTML = 'Zoom:<br>' + (Math.round(zoom * 100) / 100) + 
                  '<br><br>Image Zoom:<br>' + (Math.round(imageZoom * 100) / 100);
				  
				var zoomL =(Math.round(zoom * 100) / 100)
				
				
				var zoom0="0.01"
				var zoom1="0.02"
				var zoom2="0.03"
				
			
				
				
			
	           var square = document.getElementById("square");
				var circle = document.getElementById("circle");
				var triangle = document.getElementById("triangle");
			
			
		
				
				if(zoomL>=zoom0&&zoomL<zoom1){
					
				   square.style.display = "none";
					circle.style.display = "none";
					triangle.style.display = "block";
					 console.log ("zoom level 0")
					
					}
				
				
					if(zoomL>=zoom1&&zoomL<zoom2){
						
					square.style.display = "block";
					circle.style.display = "none";
					triangle.style.display = "none";
					 console.log ("zoom level 1")
					
					
					
					}
				
				
					if(zoomL>=zoom2){
					
					square.style.display = "block";
					circle.style.display = "block";
					triangle.style.display = "none";
					 console.log ("zoom level 2")
					
					
					}
				
				
				} // FIN UPDATE ZOOM
			
				

				
				viewer.addHandler('open', function() {

				viewer.addHandler("animation-finish", function animationFinishHandler(event){
                 console.log("animation-finish");
				  updateZoom();
			
					});
				});`

Thanks so much for any light.

**Comment by iangilman** [comment]
Seems reasonable to me. You might use `animation` rather than `animation-finish` if you want to match the zoom exactly. Also, it's better not to put quotes around your numbers (e.g. use `var zoom0=0.01` instead of `var zoom0="0.01"`. 

Anyway, that seems good. Is it working well?

**Comment by Salitehkat** [comment]
Hi, thanks and thanks for asking. 
It works, but needs a “fine tunning” ;)

I was reuniting questions to make it clean:

1- To use  zoom values is better (or more accurate) than to use the imageZoom values? 

2- On both options I am facing the problem that these values change on window/viewport resize. ( Id like to maintain the autoResize:true). Is there any other value (or trick)  that can measure the zoom of the viewport and remains the same on resize? Ive read other posts on this issue so I am guessing the answer is no ;(

3- I am using "animation-finish" to optimize de calculations, so to grab the zoom value only when animation stops. Maybe I am just complicating and it’s the same as to use “animation” as you suggested and have more accurate values (“match the zoom exactly”).

3 – Can I use this only:

`             viewer.addHandler("animation-finish", function animationFinishHandler(event){
                   updateZoom(); });`

instead of this: 
`viewer.addHandler('open', function() {
viewer.addHandler("animation-finish", function animationFinishHandler(event){
updateZoom(); });
});`

What is the difference? Cause both work but I am guessing the open function has a benefit..
Thank you so much for your time again.

**Comment by iangilman** [comment]
> 1- To use zoom values is better (or more accurate) than to use the imageZoom values?

Either are fine; just depends on what works better for your scenario.

> 2- On both options I am facing the problem that these values change on window/viewport resize. ( Id like to maintain the autoResize:true). Is there any other value (or trick) that can measure the zoom of the viewport and remains the same on resize? Ive read other posts on this issue so I am guessing the answer is no ;(

Image zoom doesn't change in relation to the viewport size, so if that works better for you, you should use that.

> 3- I am using "animation-finish" to optimize de calculations, so to grab the zoom value only when animation stops. Maybe I am just complicating and it’s the same as to use “animation” as you suggested and have more accurate values (“match the zoom exactly”).

Yes, that's valid... You're using less time because that happens less frequently. 

Note that this works well with the `viewer.viewport.getZoom(true);` because the `true` gets the current zoom and not the target of where you're zooming to... After an animation the current and the target should be the same. Another option would be to use the `zoom` events and use `viewer.viewport.getZoom(false);` which would give you the target of the zoom, which is set on zoom events, even though the current zoom hasn't yet caught up with it. 

The effect for the user of those three techniques is as follows:

* `animation`: The elements hide/show precisely as you pass the specified zoom point.
* `animation-finish`: The elements hide/show a little after you pass the specified zoom point. 
* `zoom`: The elements hide/show a little before you pass the specified zoom point (but when we know you will be passing the zoom point). 

> 3 – Can I use this only:
> 
> viewer.addHandler("animation-finish", function animationFinishHandler(event){ updateZoom(); });
> 
> instead of this:
viewer.addHandler('open', function() { viewer.addHandler("animation-finish", function animationFinishHandler(event){  updateZoom(); }); });
> 
> What is the difference? Cause both work but I am guessing the open function has a benefit..

You don't need to wrap your `animation-finish` (or any other) handler inside of an `open` handler. You would need an `open` handler if you actually wanted to perform direct operations; not everything is set up before the image is opened.

**Comment by Salitehkat** [comment]
Thank you!!! Ill apply these ideas and come back with a report,

**Comment by Salitehkat** [comment]
Hi, finally some new  advances. ;)

I am facing a problem with the animation of an svg element in relation to zoom level. I have uploaded [this example](https://linkrural.org/pp/indexSVG.html) to expose the problem. ( I couldnt make a codepen due to svg restriction issues). The rotate function runs well if its outside the update zoom function, otherwise (like in this example) when I zoom in the triangle rotation slows down and if I zoom in more it finally stops. Please, does anyone understand why it happens and which is the best approach to solve it? (hopefully mantaing the "interaction with the zoom levels) Many many thanks

**Comment by Salitehkat** [comment]
Guess Ive solved it. It was a problem of running the animation function only if it was not already running. Had to do with the animation function (not with osd). Merci!

**Comment by msalsbery** [comment]
@Salitehkat Looks resolved, closing. Please feel free to reopen this issue if necessary!
