### ISSUE TITLE
TileSource OSM with overlays

### ISSUE THREAD

**Issue by Azeeloth** [openseadragon/openseadragon#1517]
Hello,

I'm currently working on an app in which I display a map using the OpenStreetMap support from OSD. On this map i need to put overlays corresponding to Lat/Lon coordinates.

I tried to place the point "[0.0;0.0](https://www.google.fr/maps/place/0%C2%B000'00.0%22N+0%C2%B000'00.0%22E/@-4.439133,-4.6182453,4.62z/data=!4m2!3m1!1s0x0:0x0) " ( center of a Mercator map so position of the overlay is `x: 0.5, y:0.5`) and that's where I came accross the issue : there's some kind of offset on the overlay and I can't find the reason behind it (maybe I'm missing some obvious thing).

Here's a [CodePen ](https://codepen.io/anon/pen/yqwGVx)for example. 

Thanks in advance.

**Comment by iangilman** [comment]
Thank you for including a CodePen! I'm not sure I understand what the issue is, though. You're trying to put a red dot in the very center of the map? That appears to be what's happening. Do you want it to be right on the equator? It looks like the OSM map doesn't have its center right on the equator, so you'll have to compensate.

OSD doesn't have any built in support for lat/lon conversion, but it shouldn't be too hard to add on top.

Anyway, I'm happy to help; I'm just not quite sure what the problem is. :)

**Comment by Azeeloth** [comment]
![center_osd](https://user-images.githubusercontent.com/33488130/44107194-d7ba03da-9ff6-11e8-856f-18175d354c03.PNG)
![center_osm](https://user-images.githubusercontent.com/33488130/44107195-d90b4f78-9ff6-11e8-96a1-85569a7423b6.PNG)

The first picture is the center given by OSD and the second one is the center on OSM. With none or low zoom it appears to be in the right spot, but when we zoom to a country scale, there's a difference and that's where my issue is. I was going to compensate because this offset seems to be same everywhere but I thought that maybe I was missing something.

For the conversion I already found some formulae.

Thanks for your help.

**Comment by iangilman** [comment]
I measured the position of the OSD dot, and it's exactly in the middle of the map, so it's accurately doing 0.5 like you asked. To get it in the geographical center you'll have to offset it so it matches the correct location, but once you've done so it should remain consistent as you zoom.
