### ISSUE TITLE
How to limit tile requests while mouse drag in the navigator ?

### ISSUE THREAD

**Issue by xiayuan920** [openseadragon/openseadragon#1522]
Hi, I found that many tiles are requested when I drag the red frame of the navigator . Is there any way to reduce these requests during the dragging process? by the way, I can reduce the requests on onCanvasClick of  the navigator by setting panTo to true. but I can not use the same way to solve the onCanvasDrag of the navigator.

**Comment by iangilman** [comment]
The tile loading is because you're exposing new areas of the image, so it wants to load the tiles for those areas. 

You tried adding `true` to the `panBy` in the navigator onCanvasDrag and it didn't help? You could also add it to the `applyConstraints` to be thorough. 

Another thing to try is to initialize your viewer with `imageLoaderLimit: 1`... that way it only tries to load one tile at a time, which should reduce the number of tiles it's loading.

I suppose beyond that it could be interesting to consider adding a "don't load new tiles" option you could turn on when the user starts dragging and turn off again when the user stops. This might not be a good UX, though, since you'll expose blank or very blurry areas.

**Comment by xiayuan920** [comment]
Thank you very much for your answer. I am very interested in your suggestion to add "don't load new tiles" options,but I don't  know how to use it ,Looking forward to your help.

**Comment by xiayuan920** [comment]
I have an other question about the event of unloaded.When the tiles are released, what operation is done on the image loaded on the tile, is it released? if the image is released, why is the memory not coming down?I found in the project that when I quickly drag the red area in the navigator, the memory will rise wildly and cannot fall. Setting the value of maxImageCacheCount doesn't seem to work either.

**Comment by iangilman** [comment]
I believe we're releasing the images fully when we unload a tile. It's up to the browser when to garbage collect and reclaim the memory, though, so it won't necessarily happen immediately. Of course if you can find a place where we aren't releasing the images, I'd love to know about it!

As for adding the ability to pause tile loading, you'd have to write that patch yourself. I'm thinking adding `pause` and `resume` functions to OpenSeadragon.ImageLoader: 

https://github.com/openseadragon/openseadragon/blob/master/src/imageloader.js 

... Might be a good API.

**Comment by xiayuan920** [comment]
Thank you for your answer. Since I am not very familiar with Javascript, I would like to ask for your help on whether you can force the memory to be freed after the tile is unloaded.

**Comment by iangilman** [comment]
It doesn't look like it's possible to force garbage collection to happen in JavaScript:

https://stackoverflow.com/questions/8032928/can-i-trigger-javascripts-garbage-collection/12658212

It's entirely up to the browser. It should definitely do it before it runs out of memory though. 

Are you encountering problems with low memory situations, or are you just concerned about keeping things clean?
