### ISSUE TITLE
Strategies for dealing with large numbers of files

### ISSUE THREAD

**Issue by jeffabruce** [openseadragon/openseadragon#1526]
We've been using DZI tiled images for a while now with great success. The one thing that is a little disappointing in projects is the sheer number of files. A typical hi-res image might be broken up into 2000+ images. If you have several images, the total number of files get really, really big. Copying all of those individual files can take a while.

I was just curious if there was a better way or a different strategy that I was not aware of. Perhaps the non-DZI strategies use fewer fiels. Or, is there some way to have a single file or post-processing into a standard ZIP. Then coordinate the server to pull file references out of the ZIP (or some such strategy).

Or does everybody simply have these projects with thousands and thousands of files?

Thanks for any help or advice!

**Comment by xgui3783** [comment]
We frequently use OSD powered viewer that inspects a DZI like image, but
the backend is a image service that reads tiled multipage TIFF images (each
page represent a different level in terms of magnification). So you would
have a huge (multi GB) tiff image instead of thousands of tiles.

Is this what you may be looking for?

The downside of this approach is you need more than just a plain webserver,
and the requirement for the server would be significantly higher (CPU/ RAM
etc)

**Comment by iangilman** [comment]
Yep, that's the basic tradeoff... you can either have a ton of files and a super dumb server (or a CDN even), or you can have a smart server with fewer files (either because it tiles single images on the fly or because it pulls tiles out of a zip or something). I suppose a middle ground would be to upload your tiles to your server in a zip and then unzip it on the server, rather than transferring the tiles one at a time.

For smart servers, you can of course roll your own, or there are a couple of options listed here (look for "server" in the second column):

http://openseadragon.github.io/examples/creating-zooming-images/

A third option you could explore if you're feeling ambitious is to store the tiles packed into a single file and provide a way for OSD to grab just the bits it needs using HTTP range requests. There's already some discussion and even a link to a prototype here: https://github.com/openseadragon/openseadragon/issues/944

**Comment by SamHall** [comment]
It's the nature of the beast. I ended up moving all the DZI files to Amazon S3 storage. The issue I ran into was that most inexpensive hosting options limit the number of files to 100-250k. I'm way past that. I use Cloudberry Explorer for Amazon S3 ($40 paid app) to manage the uploads. The monthly costs are low - based on file access... for my site around $2.00. Uploading over a million files was slow, and cost about $12.00.
