### ISSUE TITLE
Non transparent tiles show border on v2.4.0 but not on v2.3.1

### ISSUE THREAD

**Issue by Kampii** [openseadragon/openseadragon#1591]
In [this codepen](https://codepen.io/anon/pen/qgOyeX), if opened with Firefox 64.0.2 (64-bit) on MacOS, you will see that each tile has a border. 
![image](https://user-images.githubusercontent.com/725316/51864788-8a0fc080-22f9-11e9-8e2d-10a2ae5577de.png)

If library "2.4.0" is replaced with "2.3.1" then the issue disappears. This looks very similar to issue https://github.com/openseadragon/openseadragon/pull/1470 but we are not really trying to overlay/ or underlay other tiles or make them transparent at the moment. We have not used "clearReact" so I am not sure how this would affect this issue in our case. Switching to jpeg tile format is not an option. Also, we are using overlap "2" in [our dzi file](https://s3.us-east-2.amazonaws.com/imgprocuploads/tiles/b7f3a8b685f16fb88963083cfd307d32a3794ec1612f3adb0e37aa0d67ace34e.dzi) which worked just fine. 

What are the options?

**Comment by iangilman** [comment]
I would say that is most likely due to the #1470 change. I guess the first step would be to try changing that code back. If that works, it would be good to try some additional variations on the math for `clearRect` (and yes, you're using it, since that's in the basic tile drawing code). I wonder if it's a problem with floating point rounding... perhaps we should `ceil` the position and `floor` the size, or something.

Ideally we can come up with math for this that works in all situations. Otherwise we may have to make it an option (so it doesn't break the #1470 scenario), or do some sort of situation detection.

**Comment by Kampii** [comment]
We reverted the change in the library that was related with the transparent image and it works fine now.

**Comment by iangilman** [comment]
Yes, it makes sense that it would work fine for your case, but reverting the change in OSD itself would break the case covered by #1470. The goal is to find something that works in both cases. 

That said, of course if you're okay with having your own modified OSD, sounds like you have a fix that works for your project.

**Comment by Kampii** [comment]
Oh I hear you, it would be great to cover both cases! Looks like Dvidan and Avandecreme are familiar with the granular details. I'll see if I can have one of our guys to dig deeper into this.

**Comment by iangilman** [comment]
@Kampii Great! 

@Dvidan @avandecreme FYI, #1470 evidently wasn't completely perfect. Any thoughts on how to find the happy medium?

**Comment by iangilman** [comment]
While we have been unable to find an automatic fix for this issue, we've now landed a set of options that allow you to fix the issue based on your needs and preferences: #2075. I'm going to close this issue and we can start a fresh one if there are new ideas for how to fix it more robustly and/or automatically.
