### ISSUE TITLE
When the viewer area is less than a quarter of the tile area, the SVG filter fails

### ISSUE THREAD

**Issue by bslydhs** [openseadragon/openseadragon#1607]
I am working on a project based on qt5, using SVG filters. Everything's fine, except when viewer's area is less than a quarter of tile's area, SVG filters don't work .
I need to drag zoom in or zoom out the viewer to get SVG to work again.
Part of the code is as follows:
```
<filter id="rgb">
		<feColorMatrix type="matrix" values=" 1 0 0 0 0
                                                      0 1 0 0 0
                                                      0 0 1 0 0
                                                      0 0 0 1 0"
						   color-interpolation-filters="sRGB">
		</feColorMatrix>
</filter>
```
`document.getElementsById("viewer").style.webkitFilter= "url(#rgb)";`

**Comment by iangilman** [comment]
Wow... I've never thought of trying that! So this is an otherwise generic OpenSeadragon viewer, and you're applying this SVG filter over it? What browsers are you using? How's the performance (just curious)? Is the problem you are encountering consistent across browsers?

I think in general people use https://github.com/usnistgov/OpenSeadragonFiltering to do this kind of filtering. Would be neat if the SVG filter could work as another option.

Could you share a link to an example with the issue, like a CodePen or something?
