### ISSUE TITLE
Annotation get shifted by 5px when rendered back using fabric

### ISSUE THREAD

**Issue by techiepop** [openseadragon/openseadragon#1611]
we are using open sea dragon with fabric overlay, where i draw annotations and get back contour from the backend. But this contour gets shifted by 3-5px when it is rendered back on the image. Is there any optimal solution for this kind of issue ?

**Comment by iangilman** [comment]
Is it 3 - 5px at every zoom level, or does the gap change as you zoom in? If it's the former, I wonder if there is some CSS that's bumping the overlay a little. 

Have you filed this issue on the fabric overlay project page?

Anyway, might be good to be able to see a link to a repro. I'm not sure what the cause is off the top of my head.

**Comment by msalsbery** [comment]
I was thinking possibly some CSS as well...
