### ISSUE TITLE
Openseadragon for maptiler (newbie question)

### ISSUE THREAD

**Issue by tpl42** [openseadragon/openseadragon#1613]
Can someone explain to me how to use openseadragon for viewing maptiler mbtiles output?

 I have tried using this code basically

OpenSeadragon({ 
       id: "openseadragon1",        
prefixUrl: "/openseadragon/images/",
tileSources:   [{
        type:       "tiledmapservice",
        tilesUrl:   "/maps/t1/t1.mbtiles",
}]
}]

But nothing is displayed except the buttons.

I can make it work with a jpeg so I guess the installation must be ok. And i can the buttons.

Any help much appreciated. If there are other ways to view maptiler output for example.

I am new to openseadragon and not very experienced at html either!

Thanks

**Comment by iangilman** [comment]
Unfortunately I don't know anything about Maptiler... I presume it produces TMS files? Our TMS example (http://openseadragon.github.io/examples/tilesource-tms/) includes a width and height... maybe that's important? BTW, that example isn't working at the moment because the dataset it points to is no longer online... We're on the lookout for another dataset to use! 

Looks like we have some other issue filed awhile ago about Maptiler and/or TMS, but they are not the same thing (https://github.com/openseadragon/openseadragon/issues/355, https://github.com/openseadragon/openseadragon/issues/1365)... still, perhaps @hampusb  or @francescocretti who filed them might have some ideas here.

**Comment by tpl42** [comment]
Many thanks for your help. I will look into this further. JD

**Comment by francescocretti** [comment]
Ehy @tpl42 .
I've never used maptiler, but a TMS ([Tile Map Service](https://en.wikipedia.org/wiki/Tile_Map_Service)) output should be a set of folders and subolders numbered by rows and columns.
**Looking at your example seems like you have a *.mbtiles* file that is probabily not readble as a *tiledmadservice* input** (@iangilman correct me if I'm wrong).

Your could try to convert your mbtiles output to a proper TMS scheme. 
I found this on Google: https://github.com/tomchavakis/MBTilesToTMSApi

Otherwise you could use another tool to generate yout tiles from the original image. I used this script: https://www.gdal.org/gdal2tiles.html. 
I documented the tiles generation process in the README of my project repo: https://bitbucket.org/splsteam/splswebapp/src

Once you have TMS scheme files you can set OSD options like this:
```
"id": "OSDviewer",
"tileSources": {
  "type": "tiledmapservice",
   "tilesUrl": "../media/images/tilesTMS/",
   "crossOriginPolicy": "Anonymous",
   "width": 16776704,
   "height": 8388352
   }
```
(make sure the path in *tilesUrl* is correct).

Hope it could be useful. Let me know.
Francesco

**Comment by francescocretti** [comment]
**UPDATE**
Seems you can perform the conversion from *mbtiles* to TMS with **mbutil** https://github.com/mapbox/mbutil

**Comment by iangilman** [comment]
@francescocretti Awesome! Thank you for adding this info!

BTW, have I already asked you if you know of a TMS tile source out there we can use for our example page?

**Comment by francescocretti** [comment]
@iangilman mhm in don't know about an open TMS tile source one the web.

I could generate one if you know where to host it

**Comment by tpl42** [comment]
Thanks for your help. I have now tried zoomify and found that works OK with openseadragon. 

It seems openseadragon wants the width and height of the image and I don't see how to get this information from MapTiler .

**Comment by iangilman** [comment]
@francescocretti That would be great! We can host it on https://github.com/openseadragon/example-images. Let me know how you'd like to get it to me... you can make a pull request against that repository, or send me a Dropbox/Drive link or something.

**Comment by iangilman** [comment]
@tpl42 I don't know enough about MapTiler to know where to find that information either. Glad you found something that works!
