### ISSUE TITLE
detect webp support automatically

### ISSUE THREAD

**Issue by eroux** [openseadragon/openseadragon#1622]
OSD seems not to support webp images at all (see [these lines](https://github.com/openseadragon/openseadragon/blob/master/src/openseadragon.js#L2511)). Maybe this could be determined on the flight according to the navigator? There seems to be a [quick method](https://stackoverflow.com/a/27232658/2560906) for that.

**Comment by iangilman** [comment]
That list of supported formats appears to only be used in this check of the DZI XML: 

https://github.com/openseadragon/openseadragon/blob/master/src/dzitilesource.js#L266

Otherwise I think we just load whatever image you ask for, regardless of format (but of course it only works if your browser supports that format). 

What are you trying to accomplish?

**Comment by eroux** [comment]
I have some code to use this list in the iiif tiles, the idea is that a iiif service can indicate some favorite formats, but if webp is indicated, OSD should use it only if the browser supports It, otherwise it should use another one

**Comment by eroux** [comment]
Ideally jp2 and tiff support could also be detected automatically. Modernizr has [some code](https://modernizr.com/download?setclasses) for webp and jp2, but not for tiff (which doens't work in Firefox nor Chrome anyway). I don't know if it's ok to include these modernizr plugins as dependencies or if it's best to just copy some code in OSD?

**Comment by iangilman** [comment]
Gotcha! Sounds good. 

And yes, I don't think we want to take on any dependencies (currently we have none). Ideally the detection code is small enough to just include (and fast enough to just run). If you're planning on copying code directly from Modernizr, I'm not sure the best way to handle the open source license stuff... presumably we add another "Portions of this source file taken from" section as seen at the top of https://github.com/openseadragon/openseadragon/blob/master/src/openseadragon.js 

If the detection is quick, I guess we might as well do it always, but otherwise maybe it should wait until the first time `imageFormatSupported` is called.

**Comment by eroux** [comment]
ok yes, makes sense. Although one problem is that the detection used by modernizr is asynchronous and the call to `imageFormatSupported` is synchronous...

**Comment by iangilman** [comment]
Interesting. Well, I guess if it has to be asynchronous, then doing it ahead of time is worthwhile.

**Comment by eroux** [comment]
Another option would be to have an API function that sets the supported formats. This would allow the webp detection to happen just once, then be propagated to the various areas of the system (UV, Mirador, OSD, other libraries such as [this one](https://github.com/sul-dlss/iiif-evented-canvas/) (used by Mirador), etc. what do you think?

**Comment by iangilman** [comment]
Yes, that seems like a good way to go.

**Comment by MisterX2000** [comment]
Is there any progress on this, because I'd like to use webp based Deep Zoom Images generated with vips.
Also most browsers support webp nowadays (except safari and internet explorer)
https://caniuse.com/#feat=webp

**Comment by eroux** [comment]
I don't think so. If you want to open a PR it should be fairly easy, just expose a function that allows the user to modify https://github.com/openseadragon/openseadragon/blob/master/src/openseadragon.js#L2511
