### ISSUE TITLE
Openseadragon not loading images

### ISSUE THREAD

**Issue by Tune55** [openseadragon/openseadragon#1637]
Ian,
I am still struggling with trying to get Opendragon working on my website.
I have the latest code uploaded to my root directory
I have the output of DeepZoom composer also uploaded in a named folder, also on the root directory. 
On my page, the viewer comes up but says can't load the tile source. Also the button codes are there and work, but without the graphic images of buttons. The image (button) folder is also there with all the other code files on the root directory.

My question: On DeepZoom Composer there three output types: Images, Silverlight Deep Zoom with application, and Seadragon Ajax.

I used the Images output. Any ideas?

**Comment by iangilman** [comment]
Sounds like you're doing the right stuff, but might not have your paths correct. Can you show me your folder structure and also viewer creation code?

**Comment by Tune55** [comment]
I am beginning to think this is a Weebly issue. They have so many
restrictions, workarounds are a nightmare.
Here is my page code and the file image is attached.
Thanks for looking at this for me.

<div id="openseadragon1" style="width: 800px; height: 600px;"></div>
<script src="http://dartmouthhas.org/files/theme/openseadragon.min.js
"></script>
<script type="text/javascript">
var viewer = OpenSeadragon({
id: "openseadragon1",
prefixUrl: "openseadragon/images/",
tileSources: "
http://dartmouthhas.org/files/theme/walkermapimagesoutput/dzc_output.xml"
});
</script>

**Comment by iangilman** [comment]
Thank you for the info; looks like you have several issues. 

For starters, the file at http://dartmouthhas.org/files/theme/walkermapimagesoutput/dzc_output.xml is a "Deep Zoom Collection" (DZC) file (which is a group of images, not just one image); OpenSeadragon doesn't support those kind of files. However, the DZI ("Deep Zoom Image") file is also in there, located at: 

http://dartmouthhas.org/files/theme/walkermapimagesoutput/dzc_output_images/map%202.xml

You can use that as your tile source, and it should work fine, except for your next problem: because it's on a different server from your website (I'm assuming, since you said you are using Wix for your website), the browser will block the load for security reasons. You can fix this by setting up CORS on the dartmouthhas.org server, if you have access to do so. If you don't, another option is to load the data out of the XML file and put it directly in your code in a format OpenSeadragon will understand. You would do that like so: 

```
var viewer = OpenSeadragon({
  id: 'openseadragon1',
  prefixUrl: 'openseadragon/images/',
  tileSources: {
    Image: {
      xmlns: 'http://schemas.microsoft.com/deepzoom/2009',
      Format: 'jpg',
      Overlap: '1',
      Size: { Height: '7441', Width: '10555' },
      TileSize: '256',
      Url: 'http://dartmouthhas.org/files/theme/walkermapimagesoutput/dzc_output_images/map%202_files/'
    }
  }
});
```

That should get your image showing up. If you have a lot of images you want to do this for, you might check out the function I made for converting the xml to the format OpenSeadragon likes: 

https://codepen.io/iangilman/pen/gpejpJ

As for getting the button images to show up properly, you need to have the "images" folder from the OpenSeadragon distribution (i.e. what you get from http://openseadragon.github.io/#download) somewhere (such as next to http://dartmouthhas.org/files/theme/openseadragon.min.js) and then the `prefixUrl` needs to point to that (e.g. http://dartmouthhas.org/files/theme/openseadragon-images/ or something). Another option is to use the images folder from a CDN, such as https://cdn.jsdelivr.net/npm/openseadragon@2.4/build/openseadragon/images/.

**Comment by Tune55** [comment]
Making progress, got my buttons!!! I have the viewer and buttons, but I
still get the message "can't load tile source"
I re-converted two versions of my image (both composition outputs), Images
and the Deepzoom Silverlight, no change to results.

Question: The path from your scripts point to the tilesource as
dzc_output.xml. Looking at that code, I don't see any path or reference to
the output_file images. Should there be one?

<?xml version="1.0" encoding="utf-8"?><Image TileSize="256" Overlap="1"
Format="jpg" ServerFormat="Default" xmlns="
http://schemas.microsoft.com/deepzoom/2009"><Size Width="1" Height="0"
/></Image>


Question: If this were a CORS issue, wouldn't the button image folder also
not be accessible? I did get the button images.

I did try to use your alternative to the CORS issue, but lost the viewer as
well.
code I used:
<div id="openseadragon1" style="width: 800px; height: 600px;"></div>
<script src="http://dartmouthhas.org/files/theme/openseadragon.min.js
"></script>
<script type="text/javascript">
var viewer = OpenSeadragon({
  id: 'openseadragon1',
  prefixUrl: 'openseadragon/images2/',
  tileSources: {"
http://dartmouthhas.org/files/theme/walkermapcomposition2/dzc_output.xml"
    Image: {
      xmlns: 'http://schemas.microsoft.com/deepzoom/2009',
      Format: 'jpg',
      Overlap: '1',
      Size: { Height: '7441', Width: '10555' },
      TileSize: '256',
      Url: '
http://dartmouthhas.org/files/theme/walkermapcomposition2/dzc_output_images/files/
'
    }
  }
});

So close I can feel it!

**Comment by iangilman** [comment]
The file you had before was working for me, but now that you've replaced it, the new http://dartmouthhas.org/files/theme/walkermapcomposition2/dzc_output.xml doesn't look like a valid DZI or DZC. You'll note it says the width is 1 and the height is 0; not much of an image. One of the Deep Zoom Composer output options should be able to get you a valid DZI. It's fine if it is part of a DZC like your earlier example.

Here's an example of a valid DZI:

https://github.com/openseadragon/example-images/tree/gh-pages/duomo

Regarding CORS, it's unnecessary for image files and JavaScript files, but it is necessary for XML.
