### ISSUE TITLE
Print image

### ISSUE THREAD

**Issue by s-nandra** [openseadragon/openseadragon#1638]
Hi

I am struggling to print or download the image when its open:

my code:
```
 this.printscreen = function() {
        var viewer = OpenSeadragon({ id: "dzdoc",   maxZoomLevel: 20 });
            var img = viewer.drawer.canvas.toDataURL("image/png");
            console.log(img);


  };
```

**Comment by iangilman** [comment]
The big problem I see with this code is that opening the image is an asynchronous operation. You'll want to wait until the `open` event is fired. 

In addition, you probably don't actually want to make the screenshot at the moment the file is open, because it won't have loaded all (or maybe even any) of the tiles. To test for that, you'll want to locate the image in the viewer and wait for its `fully-loaded-change` event. Another option, of course, would be to use a `setTimeout` or have the user press a button when they think it's ready. 

Here's an example with those events:

```
viewer.addHandler('open', function() {
  var tiledImage = viewer.world.getItemAt(0);
  tiledImage.addHandler('fully-loaded-change', function() {
    var img = viewer.drawer.canvas.toDataURL("image/png");
    console.log(img);
  });
});
```

The other issue I'm seeing (but maybe this is just in your example here) is that you aren't providing a `tileSources` property when you make the viewer.

**Comment by s-nandra** [comment]
I can see the image in the modal window and added a button, 
I have added tilesources to the function:
 var url =
            'https://****.amazonaws.com/data/storage/companies/uhe/filelibrary/288026dd-2937-4119-b592-b1db95065f31/dzis/288026dd-2937-4119-b592-b1db95065f31_0001_full.dzi';

        var viewer = OpenSeadragon({ id: "dzdoc", tileSources: url,  maxZoomLevel: 20 });
        viewer.addHandler('open', function () {
            var tiledImage = viewer.world.getItemAt(0);
            tiledImage.addHandler('fully-loaded-change', function () {
                var img = viewer.drawer.canvas.toDataURL("image/png");
                console.log(img);
            });
        });
When I click the button I can see 4 icons appearing at the bottom of the page > zoom in, out, toggle home
Im not sure how to trigger the image to download or way to print it.

**Comment by iangilman** [comment]
Probably the first step is to just make sure your viewer works at all. One small detail: you need to make sure it has size on the page. This CSS would work: 

```
#dzdoc {
  width: 1000px;
  height: 1000px;
}
```

If that's not enough, look for errors in the console.

Once you have the viewer working, you can return to trying to get it to print.
