### ISSUE TITLE
Multiple openseadragon Canvas with multiple paperjs on same screen 

### ISSUE THREAD

**Issue by PpyMohan** [openseadragon/openseadragon#1651]
Actually i have compared Image openseadragon canvas both have paperjs annotation but problem is if i am in single canvas screen it's working fine. but when i go to compare view getting problem in canvas annotation  if i zoom canvas 2  first canvas annotation changing.?? how do i clear this problem  .

**Comment by iangilman** [comment]
Thank you for the link to the code. I don't understand what you mean by multiple canvas. Can you explain? Is it possible to show it running?

**Comment by PpyMohan** [comment]
i have splitwindow in that left and right side we have different Images. i wanted to draw annotation on image both the side using Paperjs is that possible.

**Comment by iangilman** [comment]
So you have two separate OpenSeadragon viewers? And each has it's own PaperJS overlay? And when you draw on one of the overlays you want the same thing to appear on the second overlay? Or is it something different from that?

**Comment by PpyMohan** [comment]
Both are different images so i want to draw both the side draw annotations.

**Comment by iangilman** [comment]
I'm sorry, I'm having trouble understanding what the problem is. If you have two separate OpenSeadragon viewers, each with their own image and their own PaperJS overlay, you should be able to draw annotations into each with no problem. What is the problem you are having?

It would be helpful if you could share a running example. The code in the StackOverflow link above just has what looks like a single viewer, a single image, and a single overlay. Is the problem because you are running that code twice to get two? Are you sure you're keeping your variables separate?

**Comment by PpyMohan** [comment]
While zoom in and zoom out on one side viewer another side annotation
changing and which side i have zoomed know that side image goes hide.

**Comment by iangilman** [comment]
Are they all part of the same viewer,  or are they separate viewers?

I don't think I'm going to be able to help you without seeing it. Can you send a link? Even a video would be helpful.

**Comment by PpyMohan** [comment]
Sorry for late response, i will share you the video for the exact issue on weekend.
