### ISSUE TITLE
open-failed not emitted when deep zoom image fails to load with 401

### ISSUE THREAD

**Issue by robhicks** [openseadragon/openseadragon#1673]
My code attempts to open a deep zoom image:

```JavaScript
this.viewer = new OpenSeadragon(Object.assign(this._config, odzDz.osdConfig, { element }));
this.viewer.addHandler('open', this.imageOpenedListener);
this.viewer.addHandler('open-failed', this.imageOpenFailedListener);
this.viewer.open(this.currentImage.deepzoom);
```

The deep zoom url looks like this:
"https://www.familysearch.org/service/records/storage/dz-dist/dz/v1/dgs:008618756_00532/image.xml?session=2f28ca97-d0d9-4445-aba4-479623122482-prod&ctx=IndexingCtx"

I have attached an 'open-failed' handler to the viewer. Unfortunately, if an image fails to load with a 401, the open-failed handler never gets called. 

An error gets triggered in OpenSeadragon makeAjaxRequest and it looks like an onError handler is passed in but it does not appear to be wired to trigger the 'open-failed' event.

Should the failure to open a deep zoom image not be raised when an image fails to load due to a 401 not trigger an 'open-failed' event? If not, how can I catch the failure?

**Comment by iangilman** [comment]
Are you using `loadTilesWithAjax`? When you're referring to the `makeAjaxRequest` call, is it this one?

https://github.com/openseadragon/openseadragon/blob/c7aa6eda84931c1fc3454f1b8404d8c58d16948c/src/tilesource.js#L483

...Or this one?

https://github.com/openseadragon/openseadragon/blob/c7aa6eda84931c1fc3454f1b8404d8c58d16948c/src/imageloader.js#L94

The former is for the DZI file, and it does fire an `open-failed` on error (at least it should, and it has code to do so). The latter is for individual tiles, and only used when you use `loadTilesWithAjax`, and it doesn't fire `open-failed` because it's just a single tile that's failing, not the entire image. It should raise a `tile-load-failed` event, though.

**Comment by robhicks** [comment]
@iangilman,
As noted in the code above, we are using viewer.open passing in the deep zoom uri. Off the top of my head I don't know what open calls. But I'll see if I can debug through it tomorrow to find out.

**Comment by iangilman** [comment]
@robhicks Apologies for not being clear... I was asking whether you were using the `loadTilesWithAjax` option when creating your viewer. That would be happening in this line: 

```
this.viewer = new OpenSeadragon(Object.assign(this._config, odzDz.osdConfig, { element }));
```

I just don't know what's in `this._config` and `odzDz.osdConfig`.

As for `viewer.open` it first opens the DZI file and then starts loading tiles, so both of the code paths I mentioned above apply.

**Comment by robhicks** [comment]
@iangilman, here is the contents of my configuration:
```JavaScript
{
      crossOriginPolicy: 'Anonymous',
      debugMode: false,
      loadTilesWithAjax: true,
      showFullPageControl: false,
      showHomeControl: false,
      showNavigationControl: false, // Turns on/off the default image toolbar
      showNavigator: false, // Turns on/off the viewport navigator control
      showRotationControl: false,
      showSequenceControl: false,
      showZoomControl: false,
      tabIndex: '', // https://github.com/openseadragon/openseadragon/issues/954
      zoomPerClick: 1.4,
      zoomPerScroll: 1.2  
}

Thanks for your help.

**Comment by iangilman** [comment]
Thanks! Looks like you are using `loadTilesWithAjax`. You should be able to know about the failure like so:

```
this.viewer.addHandler('tile-load-failed', this.imageTileFailedListener);
```

Keep in mind that for every DZI there are many tiles, so you'll likely get a number of tile failure calls.

Anyway, this is happening because you're successfully loading the DZI file, but evidently you're not loading your tiles.

**Comment by robhicks** [comment]
Thanks @iangilman!
