### ISSUE TITLE
We force a little overlap when drawing a tile source that has no tile overlap

### ISSUE THREAD

**Issue by karin-toth** [openseadragon/openseadragon#1722]
Hi!
I'm loading DZI with tileOverlap=0 but the rendered canvas has an overlap between the tiles anyway. Running version 2.4.1. This is my setup:
``` 
const source = new OpenSeadragon.DziTileSource(32, 32, 16, 0, '/api/dz/ex7/ex7_files/', 'bmp');
source.minLevel = 4;
source.maxLevel = 5;
this.osView = new OpenSeadragon.Viewer({
  id: 'dzi',
  tileSources: source,
  imageSmoothingEnabled: false,
  showNavigationControl: false,
  defaultZoomLevel: 1.0
});
```
Each tile is 16x16 looks like this:
![tile](https://user-images.githubusercontent.com/17121676/67105407-03717b00-f1c9-11e9-9410-72229d6f9a8c.png)
I'm rendering the DZI in a div that is set to 32x32 pixels in size. The rendered image in the browser (chrome btw) looks like this:
![actual](https://user-images.githubusercontent.com/17121676/67105577-4af80700-f1c9-11e9-98f8-b6584e5bf515.png)
I was expecting all edges to show on all tiles, since overlap was set to 0 as seen here:
![expected](https://user-images.githubusercontent.com/17121676/67105615-5fd49a80-f1c9-11e9-848d-47d952a27eed.png)

Is this expected behavior?

**Comment by iangilman** [comment]
Interesting! The tile overlap is working fine, but the tiles aren't being drawn precisely in this case. You can tell the overlap is working if you zoom in on it. Here it is at 320x320:

<img width="341" alt="image" src="https://user-images.githubusercontent.com/338989/67120152-93013480-f19d-11e9-9a31-c845beb03808.png">

Of course the tiles have to squish and stretch at anything other than 100%, but you're right that they should line up better when they're at 100%. I'm afraid we haven't really been focused on optimizing that case, since the user rarely ends up at exactly 100%.

I'm curious, what are you working on that requires that precision?

Would you be up for digging into the code to track down where it's happening? I'm happy to provide guidance.

**Comment by iangilman** [comment]
Okay, it looks like this is the line: 

https://github.com/openseadragon/openseadragon/blob/3bbfbcbc0e136405e3f8ed95316d36255dba835f/src/tiledimage.js#L1624

**Comment by karin-toth** [comment]
Thanks for your quick reply! I'm working with microscopy images and I'm testing out this lib for viewing our slides. 
I removed the line you pointed out and did some testing with different images. The sizes of the tiles seems correct now, but when the tile sizes are rendered to fractions of a pixel I see some seams. Here is a code snippet I tested with: 
```
var source = new OpenSeadragon.DziTileSource(80, 80, 16, 0, '/api/dz/ex9/ex9_files/', 'bmp');
source.minLevel = 7;
source.maxLevel = 7;

var osView = new OpenSeadragon.Viewer({
  id: 'dzi',
  tileSources: source,
  imageSmoothingEnabled: false,
  showNavigationControl: false,
  defaultZoomLevel: 1.0
});
```
css:
```
#dzi {
  width: 81px;
  height: 81px;
  background-color: darkgreen;
}
```
The tiles are simply 16x16 grey and pink. Here is how firefox and edge looks for me (windows):
![firefox](https://user-images.githubusercontent.com/17121676/67224160-ea6b0300-f430-11e9-8bcb-e44058990e68.png)
Chrome looks fine, no seams. Since the surrounding div is 81 pixels, each tile is rendered as 16.2 pixels wide, causing sub-pixel rendering, as you probably noted. Reading on MDN, they recommend avoiding sub-pixel rendering and putting Math.floor(...) on sizes. I tested that out by adding 
```
        position.x = Math.floor(position.x);
        position.y = Math.floor(position.y);
        size.x = Math.floor(size.x);
        size.y = Math.floor(size.y);
``` 
to tile.drawCanvas(...). It seemed to solve the problem, but this lib being quite large and I've only spent a couple of hours reading the code, there is probably a nicer way to fix it, I assume.

**Comment by iangilman** [comment]
Indeed. We've been discussing that very issue over in https://github.com/openseadragon/openseadragon/issues/1683. I have a proposed patch, which is pretty much what you came up with, here: https://github.com/openseadragon/openseadragon/pull/1713 but we haven't merged it, since it does affect animation smoothness. I've written up some thoughts for additional exploration in #1683, but it may be something that can't be fully addressed without changes to Firefox itself.

Meanwhile, for your purposes, creating your tile source with a one pixel overlap should sidestep all of these issues (unless you need to use PNG tiles, in which case you're back to #1683).

**Comment by karin-toth** [comment]
Thanks for the links. The issue of sub-pixel rendering is not really in the scope of this issue, but non the less interesting! Fixing this issue brings up the problem with seams showing on all browsers and images when using no overlap. 
I have been thinking about the seams/sub pixel issue a bit, but let's discuss that in #1638 or #1713. I'd be happy to contribute to discussing solutions and coding.

**Comment by iangilman** [comment]
Sounds good! I look forward to hearing your thoughts :-)

And yeah, the subpixel rendering isn't directly related to this issue, but only because the current behavior avoids it. Like you say, if we were to change the current behavior then we would have the subpixel rendering issue to deal with.

**Comment by ZhiJingWu** [comment]
Hi, @ConnerMan 
May I ask you for advice, how did you solve the problem of image stitching gap in the end? Because after I commented out the line of code of the overlap, and then zoomed in on the image, there was still an image stitching gap, and after switching to the Firefox browser, the stitching gap became a white line. The first picture below is based on the stitching gap after the Google browser continues to zoom in on the image, and the second picture is the white line that appears after the Firefox browser opens the image
![谷歌](https://user-images.githubusercontent.com/59996019/220022434-4f3d6bad-c9a1-4c77-bf2d-e0191b003722.png)
(The gaps that still exist after removing the overlap code based on Google browser)
![火狐](https://user-images.githubusercontent.com/59996019/220022428-1fefae61-62cc-45ed-a1e5-6210c3582786.png)
(The white line that still exists after removing the overlap code based on the Firefox browser)

**Comment by iangilman** [comment]
FYI, the new WebGL renderer that's in the works in #2310 fixes this issue! @karin-toth if this is still a concern for you, I'd love it if you could give it a try. You'll have to grab the branch from the PR and build it, since it's not merged yet.

**Comment by iangilman** [comment]
I suppose we can close this now that the WebGL renderer has been released!
