### ISSUE TITLE
How do I use fitBounds to display the top row of a collection

### ISSUE THREAD

**Issue by Pin0** [openseadragon/openseadragon#1762]
I have a OSD viewer with dynamically loaded images. Sometimes there are 50 images, sometimes only 3. When the images are loaded I want them to be on top of the viewer.

Currently I have:
` 
var bounds = this.viewer.world.getHomeBounds();
var box = new OpenSeadragon.Rect(0, bounds.y + (bounds.height/2),bounds.width, 0);
this.viewer.viewport.fitBounds( box, true );
`

This one I have derived from the fitHorizontally function. 
The question I have is: into what should I change 'bounds.y + (bounds.height/2)' so that all the top row of the tileSources is alligned top?

Logically I thought it would be 0 but then the top row starts in the middle of the viewer. 

I tried using the height of the viewport but I'm obviously missing something. Any help would be much appreciated!

PS. How is it that the viewport bounds change when using a different amount of images, should the viewport not always be the same (only depending on screen size)?

**Comment by iangilman** [comment]
You need to take into account the aspect ratios... the viewport has whatever aspect ratio it gets from the viewer (e.g. the window size or the size of the element it's inside of), and `getHomeBounds` has whatever aspect ratio the content has (which is most likely different from the viewer's aspect ratio). When you call `fitBounds` with a rectangle that doesn't match the viewer's aspect ratio, it'll get centered in the viewport. To avoid that, you need to match the viewer's aspect ratio with your rectangle.

Something like this should work (I haven't tested this code):

```
var homeBounds = this.viewer.world.getHomeBounds();
var viewerBounds = this.viewer.viewport.getBounds();
var box = new OpenSeadragon.Rect(homeBounds.x, homeBounds.y, homeBounds.width, viewerBounds.height * (homeBounds.width / viewerBounds.width));
this.viewer.viewport.fitBounds( box, true );
```

**Comment by Pin0** [comment]
Ah now I understand, thanks @iangilman your code snippet worked perfect!

Thanks again and really appreciate all that you do for OpenSeadragon!

**Comment by iangilman** [comment]
Awesome... glad to hear it! :)

**Comment by KatherinR13** [comment]
Why we use "viewerBounds.height * (homeBounds.width / viewerBounds.width)" to find the height

**Comment by iangilman** [comment]
@KatherinR13 The viewer and the content might have different aspect ratios, so that code can be used to deal with that. `viewerBounds` is the rectangle that defines the viewport and `homeBounds` is the rectangle that defines the content. `homeBounds.width / viewerBounds.width` gives you a factor that you can use to scale from the size of the viewport to the size of the content. Using that factor to scale `viewerBounds.height` brings you to the content size but with the viewport aspect ratio.

**Comment by KatherinR13** [comment]
Oh... ok, now it's clear

**Comment by iangilman** [comment]
Good question! The purpose of this issue was to display the top row of a collection... for that you want to fit the entire width, but you don't mind if the height is chopped off. That's why we're basing the scale factor on the width. If, instead, you want to fit the entire height and you don't mind the width getting chopped, then you can base the scale factor on the height.

**Comment by KatherinR13** [comment]
Ok, now it's clear. Thank you 😊
