### ISSUE TITLE
Is there any way to clear specific draw instead of clearing whole draw by calling viewer.annotations.clean() in openseadragon-annotations

### ISSUE THREAD

**Issue by Jithesh363** [openseadragon/openseadragon#1781]

**Comment by iangilman** [comment]
This is probably a good thing to file at https://github.com/Emigre/openseadragon-annotations/issues, since it's about that plugin, not OpenSeadragon.

Anyway, looking at the code: 

https://github.com/Emigre/openseadragon-annotations/blob/4653efa77f15eacaf2bd75c22346300733301281/src/main.js#L27

...Looks like you could probably do a `getAnnotations()` and then filter the result and call `setAnnotations()` with it.
