### ISSUE TITLE
How can I load a SVS slide into openseadragon using electronjs?

### ISSUE THREAD

**Issue by Mefistofelex** [openseadragon/openseadragon#1782]

**Comment by iangilman** [comment]
I don't know anything about SVS. Presumably, part of the process will be converting from SVS into another, more common format. Assuming you've done that, you could either convert to DZI (or some other tiled format) in a local cache and then serve that to OSD, or you could send the entire image and use the "simple image" tile source (see http://openseadragon.github.io/examples/tilesource-image/). Since everything is happening on the local machine (in Electron), sending the entire image without tiling it isn't going to cause any "network delays". It would only be a problem if the image is so large you end up with memory problems.

So, my recommendation for starters is to convert your SVS into something like PNG (assuming you want a lossless format) locally on the hard drive, and then serve that (however one serves image files in Electron) to OpenSeadragon with a tile source like so:

```
OpenSeadragon({
    ...
    tileSources: {
        type: 'image',
        url:  '/local-cache/converted-image.png'
    }
    ...
});
```
