### ISSUE TITLE
index.js:1 [Viewport.setHomeBounds] this function is deprecated; The content bounds should not be set manually.

### ISSUE THREAD

**Issue by jeffreycwitt** [openseadragon/openseadragon#1783]
@iangilman sorry to bother you. 

In an older version of OpenSeaDragon, I used the following: 

`instance.viewport.setHomeBounds(rect, instance.viewport.contentSize.x);`

to set the home bounds 

(so that when one clicks on the "go home" button they return to a particular set of constraints.)

This doesn't seem to work any more, as I get: 

`index.js:1 [Viewport.setHomeBounds] this function is deprecated; The content bounds should not be set manually.`

I wonder if you could point me in the right direction for how to properly set the homeBounds in the current version of OSD. 

Many thanks.

p.s. thanks for your work on OSD and making it open source. Where can I send bitcoin?

**Comment by iangilman** [comment]
I believe we made this change because the content bounds affect a lot of things (not just the home region) and they are updated dynamically as the tiled images are moved around. We haven't really replaced it with any mechanism for setting the home bounds, though. 

As for how to proceed, I think it depends on exactly what you're trying to accomplish, and if you're up for writing an OSD patch. If you are, maybe we need a new `setHomeBounds` that just affects what happens when the user hits the home button. Or maybe we should make the home button function itself overwritable. 

If you just want a solution without writing a patch, one option would be to overwrite `goHome` like so:

```
OpenSeadragon.Viewport.prototype.goHome = function() {
  // Give it whatever rectangle you want
  this.fitBounds(new OpenSeadragon.Rect(0.25, 0.25, 0.5, 0.5));
}
```

> p.s. thanks for your work on OSD and making it open source. Where can I send bitcoin?

Happy to help. Thanks for the offer! I actually don't have Bitcoin (though I guess maybe I should for this reason?). I do have other ways you can help sponsor me if you'd like:

https://github.com/sponsors/iangilman
https://www.patreon.com/iangilman
https://ko-fi.com/iangilman

:)

**Comment by jeffreycwitt** [comment]
Thanks @iangilman that worked well. 

I modified it just a bit, to change the goHome function for each instance. As I sometimes have more than one running. 

```
   //OpenSeadragon.Viewport.prototype.goHome = function () {
    instance.viewport.goHome = function () {
      // Give it whatever rectangle you want
      this.fitBounds(rect);
    }
```
I sent you a coffee!

**Comment by iangilman** [comment]
Great, glad it works! And thank you for the coffee :)
