### ISSUE TITLE
Simple Image File Size + Optimization Question

### ISSUE THREAD

**Issue by lucas-tata-hologic** [openseadragon/openseadragon#1792]
Hi there,

I am working on a web application that utilizes OpenSeadragon for viewing large TIFF files (~1.5Gb). It has worked very well in general, so thank you for your efforts! 

We are trying to add a feature to our application that will pan the user at a constant speed through the image at a less than full resolution. We found that when we pan the viewer at a constant rate while in DZI format, there is noticeable framerate lag every time the viewer requests more tiles from the backend, while still trying to pan the image. We have attributed this to the viewer synchronously querying for the tile, loading tiles, then continuing the pan operation. 

From viewing the documentation and various resources on this viewer, it seems this is a bottleneck and therefore we should not be using the tiling method for this function. We took this info and instead used the OpenSeadragon viewer in simple image format, segmenting our large images and panning through them one by one. The performance is near perfect, with a high quality viewing experience for the user. 

We would like to use the simple image format for our entire image, without segmenting it. We are having trouble with this simply due to the large size of the simple image (~20Mb). We have found through experimentation that we can display right around 10Mb (268,435,456 pixels), which is half of our large image in simple image format. When we try to display any image >10Mb in the OpenSeadragon viewer, we are receiving a blank white screen. After doing some research we have found that this could be due to web browser limitations on <canvas> elements, as we are pushing the bounds: https://stackoverflow.com/questions/6081483/maximum-size-of-a-canvas-element

When we set the OSD option for useCanvas to false and try to display the 20Mb image we are successful, but the performance on pan and zoom operations is very poor. Are there any workarounds for the canvas limitations in OpenSeadragon? Is there anything to boost performance when we set useCanvas to false? Or is there possibly anything we can set on OpenSeadragon so it would be able to handle tile request and load operations in a more asynchronous fashion to allow for smoother code driven pan operations?

Any thoughts are appreciated! 

Thank you

**Comment by iangilman** [comment]
Apologies for the delayed response! The quarantine has knocked my schedule for a loop, so I've been having a hard time getting to OpenSeadragon issues.

Interesting that you are experiencing a noticeable lag on tile load. OpenSeadragon is designed to animate smoothly regardless of network activity, but of course we are to some extent at the mercy of the browser. At any rate, most of the time it's not an issue, in my experience.

Do you have a link to your project that you can share, so I can take a look?

> We have attributed this to the viewer synchronously querying for the tile, loading tiles, then continuing the pan operation.

The tile loading process is actually entirely asynchronous, and the animation continues throughout. The one exception is the actual tile decoding, which at least some browsers do on the main thread for some reason. It's possible this is the source of the lag you are experiencing. If so, there's not much that can be done about it.

Anyway, if you're happy with the simple image workaround (besides the file size limitation), one thing you might try is to use the multi-image feature:

http://openseadragon.github.io/examples/multi-image/

… and lay multiple sample images next to each other in the viewer, so they add up to a single full image.

Regarding turning `useCanvas` off, yes, you'll definitely get worse performance there… Canvas is just a lot faster than moving DOM elements around on the page. However, there is a potential in-between idea: right now we copy all of the tiles internally to canvases (for performance reasons, but nothing as dramatic as the `useCanvas` difference). Turning that functionality off could be enough to deal with the canvas size limitation (since it's probably those tiles that are hitting the limit rather than the canvas that we draw to on the screen). There is some discussion of that here: https://github.com/openseadragon/openseadragon/issues/1500. I can help point you in the right direction if you'd like to work on that enhancement. 

Note that loading a 20 MB image before the user can see anything is potentially not a great UX (depending on their network speed). There are trade-offs everywhere. :-)

**Comment by 2mer** [comment]
I looked into other image viewers to see how they tackle the decode of images (cornerstone, OHIF viewer - which uses cornerstone under the hood)

they seem to decode in web workers powered by WASM

I didnt get to benchmark this too much, but here is an example repository (that should be taken with a grain of salt) highlighting a simple (and totally naive) implementation for patching a DZI tilesource (the example only works with JPEGs) to get its tile data via a web worker instead of directly requesting the tiles

[demo](https://2mer.github.io/osd-worker-example/)
[source](https://github.com/2mer/osd-worker-example/tree/main)

**Comment by iangilman** [comment]
Very cool! Thank you for sharing the implementation. I wonder where might be a good place to share this further; it might get a little lost here on this closed issue. Maybe post about it in the discussions as well?
