### ISSUE TITLE
Storage usage and LIP

### ISSUE THREAD

**Issue by seratz** [openseadragon/openseadragon#1802]
Hello,

I will be dealing with lots of JPG's, and they are like 5 to 10MB each. If I create zoomable versions for each one, how much more storage should I expect? Im trying to decide if using "Legacy Image Pyramids" or go full tiled, calculating costs for storage and bandwidth.

Another question about "Legacy Image Pyramids" with just 2 images (low and high res), is it any different from just making a simple javascript code to replace the low image when the user hits my zoom button?

Thanks!

**Comment by iangilman** [comment]
A DZI tile set should be approximately 1.333 times the storage of the original images. This is due to the pyramid; the tiling doesn't add any significant weight. You can easily work the permit storage out mentally: each level is one quarter the area of the one above it (and therefore one quarter the storage space). With a two-level pyramid, the storage is 1.25 that of the original. With each new level you add another quarter of the previous level, approaching one third of the original at the limit.

Legacy pyramids allow you to not go strictly by halves if you want, but they don't include any tiling, so the high-res image has to be loaded in its entirety. Depending upon your use case that may be fine.

And yes, legacy pyramids (and OpenSeadragon in general) is just replacing lo-res images with high-res ones as you zoom, so you can certainly do that yourself if you prefer. OSD is fairly sophisticated in when it chooses to switch images, but depending on your scenario you might want to do it your own way.

**Comment by seratz** [comment]
thanks for the answer
