### ISSUE TITLE
Hover Event over an Overlay that is not bind to a visual element

### ISSUE THREAD

**Issue by BoazTelem** [openseadragon/openseadragon#1810]
Hi Guys,
I have many overlays set with class: highlight:hover 

        .highlight:hover {
            filter:     alpha(opacity=70);
            opacity:    0.7;
            background-color: transparent;
        }

Without attaching any visual ui element to the overlay I can see the result of the outline around the overlays as soon as I am rolling over with the mouse on the overlay area.

What I would like to do is to have 1 visual element `<div>` attached to the side of the overlay as soon as the mouse is hover it. I am unable to find a way to get the hover event when rolling over an overlay unless I am attaching a visual element to it, what am I missing? Due to the fact that I have many overlays I don't want to add to the dom so many ui elements just to present 1 tooltip. I want to be able to attach the tool tip without it. Thoughts?

**Comment by alvaromartmart** [comment]
What do you mean exactly with "without attaching any visual ui element to the overlay". As far as I know the overlay itself is actually an element (you either provide it by reference or by the id, or a div is created otherwise if you pass a plain object to the `addOverlay` method)

Either way, if you want to display some other element next to an overlay when the overlay is hovered, I can think of a couple different approaches:
- Add it as a child to the overlay element and use the `:hover` selector to toggle `display: visible`/`display: hidden` on the child element.
- Add it as an independent overlay and update its position any time you hover a specific overlay

**Comment by BoazTelem** [comment]
I am not adding the overlay in runtime, I am passing an array of objects to the overlay attribute 

var overlayArray = buildOverlays(columns,rows);	

function buildOverlays(columns,rows)
{
	var tempArray = [];
	for(var i=0;i<columns;i++)
	{
		for(j=0;j<rows;j++)
		{
			var obj = {};
			obj.id = (i+1) + "_" + (j+1);
			obj.x = i/columns;
			obj.y = j/rows;
			obj.width = 1/columns;
			obj.height = 1/rows;
			obj.className = 'highlight';
			tempArray.push(obj);
		}
	}
	return tempArray;
}

var viewer = OpenSeadragon({
		                id: "mosaic_container",
		                prefixUrl: "/openseadragon/images/",
				tileSources: "/test/myevent.dzi",
				overlays: overlayArray,
				//debugMode: "true",
				visibilityRatio: "1"
			});

Then when I roll over with my mouse on the overlay I can see the outline nicely, what I want to do now is when hover or clicking an overlay it will popup a window on the side of the tile. I don't need more than 1 popup at a time. My thinking was either attach it the overlay id in runtime and then show it or using the mouseTracker in some way, what is the best way to attach 1 ui element to a tile on roll over or click?

**Comment by BoazTelem** [comment]
Trying to simplify what I want to achieve:
If I can get a reference to the overlay id when clicking and/or hovering the viewer I will be able to solve it.

I couldn't find something like: **getOverlayBy(location);**

**Comment by alvaromartmart** [comment]
Maybe you could add a `(mouseenter)` event handler to your overlay elements and use `Viewer.getOverlayById()`. Either that or create a `MouseTracker` for each overlay.

**Comment by BoazTelem** [comment]
Thanks! This was my initial idea and I tried it but I couldn't seems to be able to register events to those overlays, maybe I am doing it wrong. As I gave all of them the class of .highlight I tried to do something like:

`$( ".highlight" ).hover(function() { ...`

but it didn't work, am I doing something wrong?

**Comment by btelem** [comment]
What I ended up doing is listening to click event, them map the tile from layer 14 which I know how to map it to overlay and moved the overlay to that position, it works, but it's not general enough and I was hoping for an easier way to do it...

```
viewer.addHandler('canvas-press', mousedownHandler);
			
			function mousedownHandler(target, info) {
	
				var viewportPos = viewer.viewport.pointFromPixel(target.position);
				var tiledImage = viewer.world.getItemAt(0);
				if (tiledImage) {

					// getTileAtPoint technique
					var viewportPosRect = new OpenSeadragon.Rect(viewportPos.x, viewportPos.y, 0, 0);
					var tileSourcePosRect = tiledImage._viewportToTiledImageRectangle(viewportPosRect);
					var tileSourcePos = tileSourcePosRect.getTopLeft();
					var source = tiledImage.source;
					
					if (tileSourcePos.x >= 0 && tileSourcePos.x <= 1 && tileSourcePos.y >= 0 &&
						tileSourcePos.y <= 1 / source.aspectRatio) 
					{
						var tilePoint = source.getTileAtPoint(14, tileSourcePos);
						
						overlay = viewer.getOverlayById("tile_box");
						var newX = (tilePoint.x)/columns;
						var newY = (tilePoint.y)/rows;
						overlay.position.x = newX;
						overlay.position.y = newY;
						overlay.adjust(overlay.position,overlay.size);
						viewer.forceRedraw();
						//console.log('getTileAtPoint', 14, tilePoint.x, tilePoint.y);	
					}
				}
			}
```

**Comment by iangilman** [comment]
Unfortunately, due to the complicated gesture handling OpenSeadragon does, it ends up blocking some events, so things like `$( ".highlight" ).hover` won't necessarily work. You need to use the MouseTracker instead.

Here's an example for click, but the principle should be the same for hover:

https://codepen.io/iangilman/pen/mEkKaY

BTW, if you're doing with 30,000 overlays, you might consider using one of the Canvas overlay plug-ins instead, so you can draw them dynamically as needed:

https://github.com/altert/OpenSeadragonCanvasOverlay
https://github.com/joshua-gould/OpenSeadragonCanvasOverlayHd

Then you would get events on the viewer itself and do the math to figure out what was hit and what needs highlighting.

**Comment by btelem** [comment]
Thanks Ian! very helpful!
