### ISSUE TITLE
Custom tile source to bring an empty image if tile is not found

### ISSUE THREAD

**Issue by lesolorzanov** [openseadragon/openseadragon#1813]
Hello. I am using OSD to view DZI and I was thinking if there is an event when a tile is not found, so that if this event happens I can capture it and instead of an error I get a default empty/white/black tile of the correct size.

I am asking this because I would like to use some images that have a high percentage of background. If I could use this default tiles for background then I could avoid saving a bunch of empty tiles.

Do you think I should do this with a custom tile source? or should I try to do something with viewer.tile-load-failed?

**Comment by iangilman** [comment]
I believe if the viewer can't load an tile (because the tile is missing, for instance) it just treats that area as transparent (and puts an error in the console). Is that not what's happening for you? If that is happening, how is it not what you're hoping to happen?

One possible solution is to use the DZI DisplayRects feature… This allows you to tell OpenSeadragon ahead of time about the missing tiles so it doesn't even bother trying to load them. It looks like there may be a bug in that functionality (https://github.com/openseadragon/openseadragon/issues/1081), but if that's the sort of feature you want, maybe you could take a look at fixing the bug.
