### ISSUE TITLE
Controls only active when the viewer set active in multi-viewer case

### ISSUE THREAD

**Issue by q36071554** [openseadragon/openseadragon#1816]
Hello, I am a Newbie in javascript and I have used OpenSeaDragon to create a viewer on asp.net and it worked great, I can zoom in, zoom out, open and close navigator with html input buttons to the viewer. But now I need to create 4 viewer in the same time, and so I need to have a mechanism to decide which viewer is the active viewer. For example, I have A B C D four viewers,  and each viewer has an different tile image, now when A viewer is the active viewer. I would like to let the control buttons only work on A viewer. Does anyone have any suggestion about how to deal with this mechanism?  Thanks a lot .

**Comment by iangilman** [comment]
Which control buttons are these? The standard navigation controls inside the viewer? They should already work only for the viewer they are inside of. Or some custom controls you've made?

**Comment by q36071554** [comment]
Oh sorry I didn't explained clearly. Yes, the control buttons are all custom controls. After Adding a new viewer the custom control can only deal with the previous viewer. I have no idea how to let the custom control to control the other viewer. Thanks for your reply!

**Comment by iangilman** [comment]
I see, so you want to have a single set of custom controls, but you want them to affect whichever viewer is currently the active one. Thank you for the clarification!

Unfortunately OpenSeadragon doesn't yet have a nice API for doing that, since you can't call the button handlers directly. Here's the issue for that enhancement: https://github.com/openseadragon/openseadragon/issues/489 If you're interested in tackling it and making a pull request, I'm happy to help answer questions!

Otherwise, the workaround is to copy that code (link at the bottom of the above issue) out to your own file and call it directly when one of your buttons is clicked.
