### ISSUE TITLE
Image disappears on page refresh in Wordpress

### ISSUE THREAD

**Issue by chamster** [openseadragon/openseadragon#1839]
I have a viewer in a Wordpress page. The first time I load the page, I can see the image, pan, zoom, etc.

When I reload the page, instead of the image I see a light grey box the size of the image, which I can pan and zoom, and I can see the navigator with a blue box instead of the image. But I can't see the image.

In Chrome, if I reload the page ctrl + shift + r (not loading from browser cache) then I can see the image.

Here's the page: https://terracomwebdesign.com/websites/theclovenproject/timeline-test/
Password: guest

Here's the code on my wordpress page:

```
<!-- wp:paragraph -->
<p>Here's the timeline:</p>
<!-- /wp:paragraph -->
<div id="seadragon-viewer" style="width:100%; height:500px;"></div>
<script type="text/javascript">
	
	
     var viewer = OpenSeadragon({
  	id: "seadragon-viewer",
        defaultZoomLevel: 10,
	panVertical: false,
	visibilityRatio: 1.0,
	constrainDuringPan: true,
	minZoomLevel: 10,
	maxZoomLevel: 10,
	showNavigator:  true,
	tileSources: {
        type: 'image',
        url: 'https://terracomwebdesign.com/websites/theclovenproject/timeline.jpg'
    }
});
viewer.addHandler('open', function() {
	var bounds = new OpenSeadragon.Rect(0, 0, 0, 0.5);
	viewer.viewport.fitBoundsWithConstraints(bounds);//
	});

</script>
```
Here's a page running the same code outside of Wordrpess. Works fine here:
[https://terracomwebdesign.com/websites/theclovenproject/timeline/index.html](url)

What it's supposed to look like:

![Screen Shot 2020-06-22 at 11 01 41 AM](https://user-images.githubusercontent.com/5459830/85320470-f43d7e00-b477-11ea-997c-85527975d196.jpg)

What it looks like after refresh:

![Screen Shot 2020-06-22 at 11 02 03 AM](https://user-images.githubusercontent.com/5459830/85320493-fef81300-b477-11ea-95c4-c8a6983e6cf8.jpg)

**Comment by iangilman** [comment]
That's a strange one! Basically, if the image is coming from the browser's memory cache, it doesn't load properly, but if it gets it from the server, it's fine.

I don't know the cause of the issue (something about your server?) but I have a few suggestions for possible fixes:

The simplest would probably be to add a randomized "cache buster" to the image URL so it never loads from the browser's cache. Something like:

```
url: 'https://terracomwebdesign.com/websites/theclovenproject/timeline.jpg?foo=' + Math.random()
```

Another thing to try would be to use http://openseadragon.github.io/examples/tilesource-legacy/ instead of http://openseadragon.github.io/examples/tilesource-image/, since they each operate on the image in a different way.

BTW, I'm delighted to see you're using OpenSeadragon for comics! You might be amused to see my comic tech experiment: https://www.driftory.com/

**Comment by chamster** [comment]
Thanks for the ideas. The "cache buster" seems like a good idea, but didn't change the behavior. See [https://terracomwebdesign.com/websites/theclovenproject/timeline-test-2/](https://terracomwebdesign.com/websites/theclovenproject/timeline-test-2/).

The legacy images probably aren't appropriate for my purpose mostly because I don't actually need to zoom. I just need to pan. I want to create a timeline that would function much like [https://www.ireland.com/features/game-of-thrones-tapestry/](url) but without the need to zoom.

So right now I have one very wide image, just to try to get it working, though I know that's not going to be good for performance as a permanent solution.

I tried cropping my image so it's a fraction of the file size, thinking maybe the large file size of the image (7.4mb) might be a problem. But still got same behavior with smaller image.

Ideally I would use a series of separate images side-by-side and pan from one to the next. I don't know if this is possible with OpenSeadragon. Or if maybe some other solution might be simpler. It would look the same as the current image, which is a series of "panels" that are side by side, except right now they are all combined into one very wide image.

Glad you like the idea of using it for comics. I'll let you know when it's published. driftory.com looks really cool.

**Comment by iangilman** [comment]
Odd that the cache buster isn't fixing it! It definitely seems to be loading it from the server each time, but it still doesn't show up. Very strange.

I'm suggesting the legacy tile source, because it's another way to do a "single image" just like you're doing with the image tile source, but it processes the image differently: the image tile source converts it into a canvas-based tile pyramid, whereas the legacy tile source does less processing. Here's how you would use it:

```
tileSources: {
  type: 'legacy-image-pyramid',
  levels: [{
    url: 'https://terracomwebdesign.com/websites/theclovenproject/timeline.jpg',
    height: 19000,
    width:  630
  }]
}
```

Since you're just supplying a single image, it's not about zooming. I think it's worth trying, though, just to see if it works.

And yes, I would say that breaking the image up into multiple images would be good for performance. It's definitely possible to do with OpenSeadragon. Take a look here:

http://openseadragon.github.io/examples/multi-image/

Here's an example using two legacy tiles sources (though you can also do it with the image tile source) next to each other:

```
tileSources: [
  {
    x: 0,
    y: 0,
    width: 9500,
    tileSource: {
      type: 'legacy-image-pyramid',
      levels: [
        {
          url: 'https://terracomwebdesign.com/websites/theclovenproject/timeline1.jpg',
          height: 9500,
          width: 630
        }
      ]
    }
  },
  {
    x: 9500,
    y: 0,
    width: 9500,
    tileSource: {
      type: 'legacy-image-pyramid',
      levels: [
        {
          url: 'https://terracomwebdesign.com/websites/theclovenproject/timeline2.jpg',
          height: 9500,
          width: 630
        }
      ]
    }
  }
]
```

**Comment by chamster** [comment]
Thanks for your ideas.

I figured it the problem! I had installed and activated the Zoom OpenSeadragon plugin, and although I wasn't using it, I hadn't deactivated it. So I deactivated it and bam, no more problem with cached image. Sorry I wasted your time and didn't catch that sooner :-(

So now I'm trying to use multi image source in order to improve performance.

I've published these examples outside of Wordpress in order to minimize the moving parts.

It works, but my problem is that if I implement constraints like `defaultZoomLevel`, `minZoomLevel`, and `maxZoomLevel`, the image loads zoomed way in to like one pixel. And you can't zoom out.

If I comment out those constraints, then it works. But it loads zoomed in than I want. Also I don't even want to be able to zoom. I just want to be able to pan. Which is why I set default, min, and max to the amount of zoom that I want.

Multi without contraints: [https://terracomwebdesign.com/websites/theclovenproject/timeline/multi1.html](url)

Multi with contraints: [https://terracomwebdesign.com/websites/theclovenproject/timeline/multi2.html](url)

Code with constraints:

```
<script type="text/javascript">
    var viewer = OpenSeadragon({
        id: "seadragon-viewer",
        defaultZoomLevel: 8,
		panVertical: false,
		visibilityRatio: 1.0,
		constrainDuringPan: true,
		minZoomLevel: 8,
		maxZoomLevel: 8,
		showNavigator:  true,
		prefixUrl: "openseadragon/images/",
				
		tileSources: [
		  {
			x: 0,
			y: 0,
			width: 5374,
			tileSource: {
			  type: 'legacy-image-pyramid',
			  levels: [
				{
				  url: 'https://terracomwebdesign.com/websites/theclovenproject/timeline/timeline1.jpg',
				  height: 630,
				  width: 5374
				}
			  ]
			}
		  },
		  {
			x: 5374,
			y: 0,
			width: 5374,
			tileSource: {
			  type: 'legacy-image-pyramid',
			  levels: [
				{
				  url: 'https://terracomwebdesign.com/websites/theclovenproject/timeline/timeline2.jpg',
				  height: 630,
				  width: 5374
				}
			  ]
			}
		  }
		]
	});
	
</script>
```

**Comment by iangilman** [comment]
Relying on a specific zoom value isn't going to work if your viewer isn't a fixed aspect ratio, since the zoom value is relative to the width of the viewer.

My recommendation is to not constrain zooming, but instead disable it. Turn off `showZoomControl` and set `zoomPerClick` and `zoomPerScroll` to 1 (these are all options when creating the viewer). I think that's enough to disable scrolling on touch screens as well, but you should verify that.

Then, to set the initial position, use `fitBounds` after the 'open' event. This will get you the leftmost side of the screen (doing the math to adjust for the aspect ratios of your viewer and content):

```
viewer.addHandler('open', function() {
    var contentBounds = viewer.world.getHomeBounds();
    var viewportBounds = viewer.viewport.getBounds();
    var bounds = contentBounds.clone();

    bounds.width = contentBounds.height * (viewportBounds.width / viewportBounds.height);
    viewer.viewport.fitBounds(bounds, true);
});
```
