### ISSUE TITLE
Browser tab freezes when browsing tiffs

### ISSUE THREAD

**Issue by kgronowski** [openseadragon/openseadragon#1852]
Hi,
I'm having an issue when browsing tiffs with universalViewer and OpenSeadragon. After some time of changing images, zooming in and out, browser tab freezes completly. Problem occurs in many browsers (Chrome, Firefox, Opera, Edge). Guys from UniversalViewer (https://github.com/UniversalViewer/universalviewer/issues/735#issuecomment-655417511) suggested that this could be ralated to tile sizes and OpenSeadragon's tile cache. They suggested to change tile size to 256 but unfortunatly that did not solve the issue.

Do you guys have any idea what could be causing the problem and how to solve it?

Example: https://rcin.org.pl/demo//dlibra/applet/publication/18329/edition/84065?handler=iiif&format_id=3

**Comment by iangilman** [comment]
That's no good!

I think the first thing I would suggest trying is setting your `maxImageCacheCount` to something smaller (it defaults to 200). See if that fixes it.

Anyway, of course this shouldn't be happening. Even if we run out of memory it would be better if we started purging stuff rather than locking up. I think that's tricky, though… I don't think the browser is very forthcoming with how much memory is available (and how much you've used).

Also, the cache should be getting cleared between each image load… Sounds like maybe something is leaking though?

Would you be up for trying to debug this? If so, I can provide some guidance. Otherwise, hopefully someone else will pick up the gauntlet. It seems like it's a pretty reasonable guess that it's an out of memory issue caused by loading a lot of tiles (though of course you never know).

**Comment by stephenwf** [comment]
Mentioned in the UV bug report but one possible work around could be to change how the cache size is described. A cache size of 200 with 256x256 images would be roughly 50mb worth of bit maps stored (200 images * 4 bytes per pixel * 256 * 256). 

We could base the cache on an estimated size, like 50mb which would fill much faster with the tiles in the example here. I think they were 672x560 tiles, so a 50mb cache could store 33 of these, but they are much larger so you _would_ need less of them anyway

**Comment by msalsbery** [comment]
@kgronowski  I would take a look at the example site's memory use. I'm able to grind it to a halt on an iPhone just by selecting 3 or 4 images. In Chrome/Edge devtools memory snapshots, there's a lot of leakage just selecting images. I don't know if IIIF images use the tile cache differently, but I'd be looking at the site and/or the tile source before diving into the tile cache

**Comment by msalsbery** [comment]
@kgronowski  not sure if it helps, but uv.js seems to retain the most objects...

**Comment by kgronowski** [comment]
Thanks for suggestions guys :) 
I was able to fix the issue by updating OSD. UV was using older version of OSD (2.2.1). After updating it to newest (2.4.2) everything seems to be fine and browser no longer freezes.

**Comment by msalsbery** [comment]
@kgronowski excellent! Thank you for the update!
