### ISSUE TITLE
Support Minification During movement Properly with MipMap pyramids, EWA or Summed Area Tables

### ISSUE THREAD

**Issue by devshgraphicsprogramming** [openseadragon/openseadragon#1856]
Right now when I zoom out the examples and move the image around I get aliasing due to what I presume is **nearest neighbour filtering** (or bilinear, doesn't matter, still bad cause it won't account for display's pixel footprint).

It you had a prefiltered representation, either as a mip-chain or as a Summed Area Table, the image would handle subpixel movements and minification better.

**Comment by devshgraphicsprogramming** [comment]
My bad, seems to actually be doing minification properly but there's a delay before the lowpass convolution is applied so I can see some aliasing during the zoom-in/zoom-out animation/motion that later disappears.

**Comment by iangilman** [comment]
Hmm… I don't think we are rendering any differently during animation than we do at rest. We're just using canvas's [drawImage](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/drawImage) for our rendering.

There can be differences due to tiles not being loaded yet, though. Perhaps that's part of what you're seeing? If you zoom out, it'll scale down the high-res tiles until the lo-res title has been loaded, so that might feel like stronger aliasing getting replaced by a smoother version.

Just to be clear, you're seeing these effects while zooming the demo on http://openseadragon.github.io/? Or somewhere else? What browser/OS? I can't say I'm seeing what you're seeing, but I'd like to learn more.

**Comment by devshgraphicsprogramming** [comment]
> Just to be clear, you're seeing these effects while zooming the demo on http://openseadragon.github.io/? Or somewhere else? What browser/OS? I can't say I'm seeing what you're seeing, but I'd like to learn more.

Demo on the github page, Firefox + Windows 10.

**Comment by iangilman** [comment]
Cool, good to know. Would you say it's consistent with the tile loading theory?

**Comment by devshgraphicsprogramming** [comment]
> Cool, good to know. Would you say it's consistent with the tile loading theory?
No because I can repeatedly zoom in and out and get this issue, you'd have to drop unused tiles for this to happen over and over again.

**Comment by iangilman** [comment]
Cool, thank you for confirming.

I still don't think I'm seeing what you're seeing, nor do I have a good sense for what we might do to fix it. At any rate, if you're interested in working on contributing a fix, I'm happy to help answer questions along the way. Otherwise perhaps someone else will pick this up.
