### ISSUE TITLE
Legacy Internet Explorer Support?

### ISSUE THREAD

**Issue by msalsbery** [openseadragon/openseadragon#1863]
With [support ended for Internet Explorer 10 ](https://docs.microsoft.com/en-us/lifecycle/announcements/internet-explorer-10-end-of-support) I thought I'd open an official issue on our support for old Internet Explorer versions.

It's not a huge issue, but at some point it would be nice to sweep out all the code we have for old IE support. Even if we still support 10 it would be a nice cleanup, and not a huge task.

Comments?

Note: Even in my latest MouseTracker patch (in progress, coming v2.5.0) I'm still testing back to IE 9 (via emulation on IE 11)...I'd go back to 8 but we fail there - could be my test page or OpenSeadragon, but that debugging is a project for after this patch gets in...

**Comment by iangilman** [comment]
As of this moment on https://caniuse.com/usage-table, I'm seeing on desktop browsers:

* IE9: 0.24%
* Opera: 1%
* IE11: 1.38%
* Edge: 3%
* Firefox: 3%
* Safari: 3%
* Chrome: 30%

That doesn't include mobile browsers, which is why it doesn't add up to 100%. I didn't include any of the other IE versions, because they are basically rounding errors at this point.

With those numbers, I feel comfortable officially dropping support for IE10 and earlier. IE11 is still hanging on (and has been dropping extremely slowly), so I think we should still retain support for it. Of course we should keep an eye on it; someday its reign will end!

**Comment by msalsbery** [comment]
> With those numbers, I feel comfortable officially dropping support for IE10 and earlier.

Music to my ears (eyes?)!

**Comment by msalsbery** [comment]
@iangilman 

What do you think about removing IE<11 support for the 2.5.0 milestone?

**Comment by iangilman** [comment]
Sounds good. Let's make it official :-)

**Comment by msalsbery** [comment]
Linking #373 in case it notifies concerned parties

**Comment by iangilman** [comment]
Good thinking, but I don't think linking sends notifications, so I've added an explicit comment there.

**Comment by msalsbery** [comment]
> Good thinking, but I don't think linking sends notifications, so I've added an explicit comment there.

Gracias!

**Comment by rmontroy** [comment]
What about these parts?
https://github.com/openseadragon/openseadragon/blob/ab3f49abe3b80ed110a9ab592086d89fd5bc4198/src/openseadragon.js#L2301
https://github.com/openseadragon/openseadragon/blob/ab3f49abe3b80ed110a9ab592086d89fd5bc4198/src/openseadragon.js#L2476-L2481

**Comment by msalsbery** [comment]
> What about these parts?
> https://github.com/openseadragon/openseadragon/blob/ab3f49abe3b80ed110a9ab592086d89fd5bc4198/src/openseadragon.js#L2301
> 
> 
> https://github.com/openseadragon/openseadragon/blob/ab3f49abe3b80ed110a9ab592086d89fd5bc4198/src/openseadragon.js#L2476-L2481

Clearly I didn't search on enough variations of "IEx"...Up for submitting a pull request? :)
