### ISSUE TITLE
A problem to run the very first example

### ISSUE THREAD

**Issue by AdamOrHd123** [openseadragon/openseadragon#1864]
Hi,
I'm trying to run the example.
I copied the openseadragon to the directory where I run the html file from.
This is the html file:

```
<!DOCTYPE html>
<html>
	<head>
		<title>Liquid Layout</title>
        <script src="./openseadragon/openseadragon.min.js"></script>
        <script type="text/javascript">
            var viewer = OpenSeadragon({
                id: "openseadragon1",
                prefixUrl: "/openseadragon/images",
                tileSources: "C:\GIT\mos_blog\static\photos\1.bmp"
            });
        </script>
    </head>
    <body>
        <div id="openseadragon1" style="width: 800px; height: 600px;"></div>
    </body>
</html>
```

I get this error when running it:
Uncaught TypeError: Cannot read property 'appendChild' of null
    at new m.Viewer (viewer.js:272)
    at OpenSeadragon (openseadragon.js:740)
    at tile.html:7

Can you please assist?

**Comment by iangilman** [comment]
> Uncaught TypeError: Cannot read property 'appendChild' of null

This is because your script is before the openseadragon1 div, and therefore the div doesn't exist when the script runs. Move the script below the div and it should be fine.

That said, you may have some other issues… I don't think the URL you're using for your tile source will work… It's just a file path, but needs to be a URL. Assuming your HTML file is already inside of "C:\GIT\mos_blog\", you would just use "static/photos/1.bmp".

Also, a BMP by itself isn't enough to describe the tile source. If you just have a single image like that, you need to use http://openseadragon.github.io/examples/tilesource-image/, like so:

```
    tileSources: {
        type: 'image',
        url:  'static/photos/1.bmp'
    }
```

I hope that helps!

**Comment by msalsbery** [comment]
Closing this...feel free to re-open if issue persists!
