### ISSUE TITLE
Adding ALT text to OSD images

### ISSUE THREAD

**Issue by ghost** [openseadragon/openseadragon#1877]
I have bunch of opeanseadragon images but how do I add ALT text to the images so it passes accessibility. 
example of my code is:
```
<div class="gallery">
    <div class="gallery_image-wrapper">
      <div class="gallery_image">
<div id="materials-0416" class="suarrmaterials-zoomable-image" style="height:400px; width:400px;" data-image="2013/02/dscn0416.jpg">   </div><div class="gallery_image-description"><h3>DSC-0416</h3></div>    
      </div>
    </div>
    <div class="gallery_image-wrapper">
      <div class="gallery_image">
<div id="materials-0149" class="suarrmaterials-zoomable-image" style="height:400px; width:400px;" data-image="2013/02/dscn0419.jpg">   </div><div class="gallery_image-description"><h3>DSC-0149</h3></div>    
      </div>
    </div>
    <div class="gallery_image-wrapper">
      <div class="gallery_image">
<div id="materials-0421s" class="suarrmaterials-zoomable-image" style="height:400px; width:400px;" data-image="2013/02/dscn0421.jpg">   </div><div class="gallery_image-description"><h3>DSC-0421</h3></div>    
      </div>
    </div>
</div>
```

**Comment by iangilman** [comment]
Is each viewer a single image, or are there multiple images in the same viewer? If it's one image per viewer, you can put your accessibility code on the div that contains the viewer. It wouldn't be a literal alt tag, because that's just for images (and the viewer is a canvas), but you should be able to provide some sort of accessibility code to the containing div.

If it's more than one image per viewer, then you'll want to do custom overlays as @msalsbery suggests.
