### ISSUE TITLE
enhancement openseadragonizer : add copy Link to web version in browser addon

### ISSUE THREAD

**Issue by Clemens-Ratte-Polle** [openseadragon/openseadragon#1880]
Hi.
I got a suggestion for the Browser Extension OpenSeadragonizer.
How about adding the option to copy the link to an image to watch it in the web version of OpenSeadragonizer?
https://openseadragon.github.io/openseadragonizer

Like this:
https://openseadragon.github.io/openseadragonizer/?img=https%3A%2F%2Fpreview.redd.it%2Fcok76s7jf9z41.png%3Fwidth%3D960%26crop%3Dsmart%26auto%3Dwebp%26s%3D6260f285ef3ad2b07da225486442b8b3d7c887e7&encoded=true

So i could send it to friends who can watch images with openseadragon much better :) 
Perhaps also with option for URL shortening :) 
thx

**Comment by iangilman** [comment]
Good idea! Can you file it over in https://github.com/openseadragon/browser-extension/issues?

Also, if you're interested in making a patch for this feature, I'm happy to help point you in the right direction :-)

**Comment by Clemens-Ratte-Polle** [comment]
hi. What do you mean with "file it over"? :)

**Comment by iangilman** [comment]
> hi. What do you mean with "file it over"? :)

Sorry if that was confusing! I'm just saying that this issue should be filed in the browser extension repository, since it has to do with the browser extension, which is not part of the OpenSeadragon repository (which is where this issue is). Please file a new issue in https://github.com/openseadragon/browser-extension/issues, so it doesn't get lost here.

**Comment by Clemens-Ratte-Polle** [comment]
ok thx 👍
