### ISSUE TITLE
Include Flat Toolbar Icons in the images folder?

### ISSUE THREAD

**Issue by abrlam** [openseadragon/openseadragon#1891]
Is it possible to include the [icons](https://github.com/peterthomet/openseadragon-flat-toolbar-icons) created by @peterthomet in the images folder (e.g. ```images/flat_icons```)?

This gives users an option to update the icons easily without downloading the set from another source.  They can also take advantage of the CDN.

Thank you.

**Comment by msalsbery** [comment]
@abrlam  What about using the prefixUrl property in the viewer create options?

**Comment by abrlam** [comment]
@msalsbery The prefixUrl will play a role with this request.

For example:
prefixUrl: 'https://cdnjs.cloudflare.com/ajax/libs/openseadragon/2.4.2/images/flat_icons'

This allows users to change the icons from the original to the new set. You can say it's more for convenience than anything.

**Comment by iangilman** [comment]
It's a nice idea, but I don't think I'm in favor of it, for these reasons:

* It increases our support surface area… Every time we add a new button, we'll have to do it for both icon sets. In fact, the flat icons already don't have all of the buttons we need for the current version of OpenSeadragon.
* It will make our install package bigger.
* Even though there's only one alternate icon pack at the moment, ideally it would be great if there were many. Looking forward, if there are 5 or 10 icon packs, would we include them all? If not, how do we choose which ones? Each new icon pack we add multiplies the first two issues in this list.

Let's stick with a single icon pack in the core product, but keep it easy to add alternates to your app.

Of course I realize the icons we currently have in the core are pretty retro (though at this point maybe they are retro enough to be cool again?)… I'm not against changing them to something else. I think I would want it to be something newly designed for the purpose, though, rather than just swapping in the flat icons.
