### ISSUE TITLE
Suggestion to improve the speed of changing tilesources

### ISSUE THREAD

**Issue by Adnaan03** [openseadragon/openseadragon#1915]
We have created the custom ImageJob to load the tiles from indexedDb instead of fetching them from server. First tilesource is loaded fast in around 700-1000ms but consecutive tilesources loading time keeps increasing if we switch them quickly.
So is there any thing in OSD which could be increasing the load time?
We know that loading tiles from indexed db is fast, and there is some extra work being done by OSD so we need some way to properly stop it so that we can load new tile source faster

**Comment by iangilman** [comment]
Just to confirm, you're opening new tile sources and replacing the old ones? Or you are adding new tile sources on top of existing ones?

Anyway, OpenSeadragon shouldn't be doing anything to slow down successive tile source openings. This issue is from a while ago, but if you're still looking into this, I would suggest isolating just the OpenSeadragon aspect (loading a bunch of tile sources without using indexedDb) to see if you can create a shareable repro.
