### ISSUE TITLE
Trying to add parameters to image request within TEI Publisher

### ISSUE THREAD

**Issue by 50jonesh** [openseadragon/openseadragon#2022]
Hello everyone,
I’m not sure it will be possible to answer my questions here, but I’ll try anyway.

I’m part of a team working to create a digital edition of a medieval manuscript. We’re using a tool called [TEI Publisher](https://teipublisher.com/exist/apps/tei-publisher/doc/documentation.xml?id=introduction)  to arrange and present our edition, and TEI Publisher uses OpenSeaDragon to display the facsimile images of the manuscript. We’re trying to find a way to apply region parameters to our image requests, in order to crop out some extraneous space from the original images. IIIF provides [guidelines](https://iiif.io/api/image/3.0/#4-image-requests)  for how to add these region parameters to a URI string, and I’ve been able to construct a few on my own that function perfectly well when pasted into a web browser (for example, see this [https://ids.lib.harvard.edu/ids/iiif/8311653/full/full/0/default.jpg](https://ids.lib.harvard.edu/ids/iiif/8311653/full/full/0/default.jpg)  for the original image, and this [https://ids.lib.harvard.edu/ids/iiif/8311653/pct:3,4,63,93/max/0/default.jpg](https://ids.lib.harvard.edu/ids/iiif/8311653/pct:3,4,63,93/max/0/default.jpg)  for the cropped version). 

According to the IIIF guidelines, applying these parameters to an image request is as simple as adding the appropriate components to the end of the URI string - after the image ID but before the file format designator (in the above URLs, the “/full/full/0/default” and “pct:3,4,63,93/max/0/default” serve this function). So I originally expected that adding similar parameters to our digital edition would be simple. Except that, we haven’t been able to find a way to add these parameters within the actual edition, mainly because we can’t find any complete URI strings anywhere in our files. As best as I can figure it, TEI Publisher has split the component parts of the URI string into two pieces, each of which is being kept in a separate document. When OpenSeaDragon sends out an image request for our facsimile images, then, I suspect that it must be stitching together these component parts to get a complete string.

The first part of the request string is in our HTML template. The line of code that pertains to the facsimile images is <pb-facsimile>, within which is a property called “base-URI,” which provides three of the four required pieces that make up a IIIF image request string: the scheme (https) the server (ids.lib.harvard.edu) and the prefix (ids/iiif).

`<pb-facsimile id="facsimile" base-uri="https://ids.lib.harvard.edu/ids/iiif/" default-zoom-level="2" show-navigation-control="show-navigation-control" show-navigator="show-navigator" subscribe="transcription"/>`

The TEI Publisher devs did confirm for me that OSD does rely on the “base-uri” element when sending out image requests. I also noticed that some of the other properties applied in this same line equate to the customizable features I see in your [documentation](https://openseadragon.github.io/docs/OpenSeadragon.html#.Options) (such as default-zoom-level, show-navigation-control, and show-navigator), which would seem to confirm that this line is key to how OSD is incorporated into TEI Publisher.

The only piece missing to make this a complete URI string, however, is the unique image identifier, which appears only in our XML code under page break tags. Each <pb> in the XML has a property “facs”, which provides the image ID for the facsimile. For example, this is the <pb> tag for page one of our manuscript:

`<pb facs="iiif:8311653"/>`

My first thought, when I first approached this problem, was to add the region parameters to this “facs” property, with the expectation that those extra characters would be added to the URI string along with the image ID, and that OSD would then process the parameters as part of the image request. However, adding anything to this tag element only results in a 404 error.

This is particularly strange, because at present our image IDs don’t end with a file designation, which sets them apart from all examples I’ve seen from IIIF, TEI Publisher, and yourselves. Based on both the guidelines from IIIF and the example code I’ve seen, it seems that any IIIF image request strings must end with a file format designation – either something like “.jpg” for an image request or “.json” for an image information request. But if I attempt to add any kind of file designation to the image IDs, or any of the parameters specified in the IIIF guidelines, to the “facs” XML element, I’m met with a 404 error.

I am very aware that my troubles in figuring out this problem likely stem from a misunderstanding of what’s going on within TEI Publisher. And I’ve tried to ask for more clarification from the TEI Publisher devs, but they seem unwilling to explain things further. They have simply identified OSD as the tool being used to request and display images, and suggested that OSD does not support IIIF’s region parameters. That explanation seems inadequate to me, given how adding parameters is portrayed in the IIIF guidelines as a standard part of an image request – and given that [at least one user](https://github.com/openseadragon/openseadragon/issues/1400)  has posted on this GitHub page previously about how he was able to incorporate such parameters into his IIIF request. But I don’t know how else to go about testing my theories since the code I’m working with from within TEI Publisher looks so different from that of your guidelines and documentation. 

If there’s anything you notice about what I’ve written here that might suggest how OSD is managing image requests within this platform, or where I might be going wrong in my understanding of the image request process, I would greatly appreciate any help or insight.

One final piece of the puzzle I should mention is a line in our ODD (or “One Document Does it all,” which is the file that instructs the TEI Publisher viewer on how to render specific XML tags within the viewer interface). In this file, there is an element specification related to the <pb> element in our XML, describing how these page breaks should be rendered:

```
<elementSpec ident="pb" mode="change">
                    <model output="epub" behaviour="break" useSourceRendition="true">
            <param name="type" value="'pagebreak'"/>
            <param name="label" value="(concat(if(@n) then concat(@n,' ') else '',if(@facs) then concat('@',@facs) else ''))"/>
        </model>
                    <model predicate="starts-with(@facs, 'iiif:')" behaviour="webcomponent">
            <param name="name" value="'pb-facs-link'"/>
            <param name="content" value="@n"/>
            <param name="facs" value="replace(@facs, '^iiif:(.*)$', '$1')"/>
            <outputRendition xml:space="preserve">
                            font-size: 16px;
                            color: #888888;
                            cursor: pointer;
                            display: inline;
                            display: block;
                            margin-right: -32px;
                            float: right;
            </outputRendition>
        </model>
                </elementSpec>
```
Although I don’t know enough about how the XML code in an ODD file works, it appears to me like the line `<param name="facs" value="replace(@facs, '^iiif:(.*)$', '$1')"/>` may have something to do with how OSD knows to add the image ids to the base URI to construct a complete image request.

**Comment by iangilman** [comment]
Thank you for writing up such thorough notes! 

Judging by issue https://github.com/openseadragon/openseadragon/issues/1793, OSD does not yet support passing through selectors like `pct:3,4,63,93`. Evidently there is some interest in that, but no one has stepped up to implement it. 

One of the suggestions from that issue could point a way to getting the result you want, though... you could load the full image and then use OSD's clipping feature to crop out the bits you don't want. It looks like the numbers in `pct:3,4,63,93` are percentages for left, top, width, height, so those can be used to generate the clip. Here's an example:

```
var url = 'https://ids.lib.harvard.edu/ids/iiif/8311653/info.json';
var leftFactor = 0.03;
var topFactor = 0.04;
var widthFactor = 0.63;
var heightFactor = 0.93;

viewer.open(url);

// We have to wait until the viewer has opened the image in order to access the image and get its size
viewer.addHandler('open', function() {
    // Get the image; there's only one so we know it's item 0
    var tiledImage = viewer.world.getItemAt(0);
    
    // Find out the image's full size in pixels
    var size = tiledImage.getContentSize();
    
    // Figure out the clipping bounds in image coordinates
    var left = Math.round(size.x * leftFactor);
    var top = Math.round(size.y * topFactor);
    var width = Math.round(size.x * widthFactor);
    var height = Math.round(size.y * heightFactor);
    var clipBounds = new OpenSeadragon.Rect(left, top, width, height);
    tiledImage.setClip(clipBounds);
    
    // Now that we've clipped it, the new home bounds are matched to the visible area; we can use 
    // goHome to take us there (passing true to bypass the usual animation)
    viewer.viewport.goHome(true);
});
```

That's in vanilla OSD, of course... I'm not familiar with TEI at all, so I can't say how to integrate it there. 

One thing to be aware of with this technique is that you're still sending the data for the bits that have been clipped out, so it's a little less efficient than just grabbing the region of interest, but I think in practice it won't make that much difference in terms of loading speed. 

BTW, you pointed to https://github.com/openseadragon/openseadragon/issues/1400 as someone who had used the `pct` successfully. The way they did it is to ignore the tile pyramid that IIIF provides and instead load the entire full-res image as a single tile using the "[simple image](http://openseadragon.github.io/examples/tilesource-image/)" tile source rather than the IIIF tile source. You can do that like so if you want:

```
viewer.open({
  type: 'image',
  url: 'https://ids.lib.harvard.edu/ids/iiif/8311653/pct:3,4,63,93/max/0/default.jpg'
});
```

This has the disadvantage of loading the entire image at once, which can be slow for big images. The image above is only 2268 × 3591 pixels, so it's probably not too big of a deal, as long as you're just showing one of these pages at a time. If you do have larger images or if you're planning on showing a number of them at the same time, you wouldn't want that. 

One halfway point would be to use the [legacy tile source](http://openseadragon.github.io/examples/tilesource-legacy/), which allows you to manually specify a pyramid, but not individual tiles at any layer in the pyramid. This might make sense if you have a lot of images you want to show at the same time; you can specify a low-res pyramid level for when you are zoomed out looking at all of them. You would need to already know the dimensions of the image before loading the image, and you would need to know how to tell the IIIF server to give you low-res versions. 

I hope this gives you some possible leads to work with!

**Comment by 50jonesh** [comment]
Thank you so much for the detailed response!

Thanks for bringing my attention to issue #1793 – I only wish I were proficient enough with any of these tools to volunteer to work on this!

Both suggestions you make (calling the full image and using OSD to crop it, and loading the entire image as a single tile) sound like they could work for the purposes of my team’s project - assuming, as you mentioned, that TEI Publisher can support it. As I don’t know much about its inner workings either, I’ll have to take what you’ve given me and show it to them to see what the possibilities are.

Regardless, I really appreciate the help!

**Comment by iangilman** [comment]
Sounds like a plan... good luck!
