### ISSUE TITLE
Non-0 rotation used with visibilityRatio results in incorrect image boundaries

### ISSUE THREAD

**Issue by AaronPlave** [openseadragon/openseadragon#2040]
When using a `visibilityRatio` of 1 (and possibly less) the image boundaries are not correctly computed when rotation is not 0 degrees. This can be seen on the OSD example for visibilityRatio https://openseadragon.github.io/examples/ui-zoom-and-pan/ and I've seen this behavior in other tests. What's puzzling me is that, unless I'm misremembering, this behavior was not the case as recently as a few months ago when I was working on supporting rotation in an application I develop. I'm not sure if there was a browser update that somehow changed this behavior? Or am I missing something.. I'm currently using OSD 2.4.1 with Chrome Version 93.0.4577.63 (Official Build) (x86_64) on Mac 10.15.7. I also see this on Firefox 78.14.0esr (64-bit) and Safari Version 14.1.1 (15611.2.7.1.6, 15611). Also appears on iOS Safari.

Recording of issue:
https://user-images.githubusercontent.com/4419607/134102541-b4f958a4-15a9-49b6-adb9-06fdde6d020d.mov

**Comment by iangilman** [comment]
Interesting! Have you tried other versions of OSD? It would be great to know if this is still happening on master... I feel like there may have been fixes in this area, but I'm not finding them.

**Comment by AaronPlave** [comment]
I've been trying to find a pattern and it looks like the size of the OSD container has an affect on this issue. Specifically when the ratio of width to height is not 1:1 the issue appears. I've put together a fiddle documenting this, doesn't seem to be dependent on OSD version. http://jsfiddle.net/c2h8f6zx/186/ Any clue as to if this is a bug or if I'm missing some bit of configuration?

**Comment by iangilman** [comment]
It certainly looks like a real bug! Interesting that no one has spotted it before. I would think it would affect the "home" position as well as the constraints. 

Thank you for trying it on different OSD versions. Did you get a chance to try it on the latest master?

Are you up for digging further to find a fix? If so, I can point you in the right direction. Otherwise, hopefully someone will take an interest and pick this up.

**Comment by AaronPlave** [comment]
Didn't try it on latest master, have never actually gone through the process of building OSD from src but can give that a go. But in the interest of checking quickly - is there a build of master somewhere?

And I can take a look at a fix but will definitely need some pointers on where to start and what the likely culprits might be.

**Comment by iangilman** [comment]
We don't have regular builds of master. The closest I can think of is the ones @msalsbery did for https://github.com/openseadragon/openseadragon/pull/1872, but those are a year old now. Getting it building shouldn't be hard, though... just typical `npm` stuff (though you do need to install Grunt). Here's the info: 

https://github.com/openseadragon/openseadragon/blob/master/CONTRIBUTING.md

Of course you'll need it in order to actually fix the issue. 

In terms of where to start, I would start with `Viewport.applyConstraints`: 

https://github.com/openseadragon/openseadragon/blob/f097808c95ea11ed8ac9cd57044d98ce3da38914/src/viewport.js#L570

I suspect the problem may be with the zoom constraint more so than the pan constraint, so you might look at `Viewport._applyZoomConstraints` and the `getMinZoom` and `getMaxZoom` that it calls. None of those things seem to take rotation into account, so that's a likely culprit.

**Comment by AaronPlave** [comment]
May have found a resolution for this but almost feels too simple, wonder if this will break other things.. putting up a PR for this shortly but I'm testing out getting bounds _with_ rotation in `applyConstraints` and then not applying the rotation in the `fitBounds` call at the end of the function. So far it seems to work but again, there may be side effects I'm not aware of.

**Comment by AaronPlave** [comment]
See https://github.com/openseadragon/openseadragon/pull/2041

**Comment by peterjcaulfield** [comment]
Just chiming in to say I just hit this bug too! I had a config of:

```
constrainDuringPan: true,
visibilityRatio: 1
```

And the image will "bounce" during panning before reaching the edges when rotated on its side.

**Comment by iangilman** [comment]
@peterjcaulfield Good to know! I've pinged @AaronPlave over on #2041, but if he's not willing/able to continue with that patch, would you be interested in taking it over?
