### ISSUE TITLE
Dynamic image tiling 

### ISSUE THREAD

**Issue by roshtha** [openseadragon/openseadragon#2082]
Hello all,
I am working on microscope images using open sea dragon deep zoom display. The whole image can be very big ie. 4096x2160 pixels. 
I am also arranging multiple tiled image sources in rows and columns. 
Each image of 4096x2160 pixels arranged in 54 rows and 16 columns. ([Reference to an issue posted earlier](https://github.com/openseadragon/openseadragon/issues/2050) ) https://github.com/openseadragon/openseadragon/issues/2050

Currently I use static deep zoom image files that have to be created before use. 
The image tiling generation itself takes several hours to complete.
I also want to improve the loading time of tiles.
I would like to know whether it is possible to do tiling dynamically as users' zoom or pan 
How to use dynamic tile image generation with openseadragon?

I see in viewers of https://cancer.digitalslidearchive.org/, the images are getting loaded at a faster rate. 
Are the tiling for these images done before hand or is it done dynamically?
Is custom tile sources along with a tiling service implementation or IIPimage server can achieve this functionality?

Thanks.

**Comment by iangilman** [comment]
You have 864 image files, each of which is 4096 x 2160 pixels in size? And altogether they make a single image?

Do you want to be able to see the entire image (all 864 files laid out together) when zoomed out? If so, you'll definitely want to turn this into more of a pyramid, with low resolution versions of your image. Otherwise you have to load 864 files before you can see the whole thing, and that's always going to be slow no matter how you do it.

Can you turn all of those image files into a single file with the entire image? If you then turn that into a DZI file, you'll get a full tiled pyramid, which should load much more smoothly.

What are you using to convert your images with? I recommend VIPS; it's quite fast. But yes, you could also have them tiled on the fly using IIPimage server or similar. You'd still want to stitch them into a single image ahead of time, though, I believe (unless IIPimage has functionality for that as well).
