### ISSUE TITLE
multiple images on a page have issues with controls

### ISSUE THREAD

**Issue by elrayle** [openseadragon/openseadragon#2087]
openseadragon 2.4.2

### Description

When a web page has more than one image that is controlled by openseadragon using ![image](https://user-images.githubusercontent.com/6855473/149172637-cf2add4f-2267-490b-821d-f8f2f2f277a5.png), the following conditions occur:
* they all share the same id for these controls (i.e., “osd-zoom-in”, “osd-zoom-out”, “osd-home”, “osd-full-page”)
* only the controls for the first image have any impact
* when the controls for the first image are used, all images are impacted (e.g. click the + icon to zoom in on the first image and all images on the page are zoomed in, not just the first one)

[For context, see the issue in action.](https://exhibits-prod-1.library.cornell.edu/chinese-traditional-dress/feature/han-women-s-style)

### Expected

For accessibility (and probably function as well), each control should have a unique id.

When there are multiple controlled images, the controls for each image function as expected and only impact the image they are associated with.

### Actual

The control icons share ids by function.  That is, all the zoom in buttons have id "osd-zoom-in", all zoom out buttons have id "osd-zoom-out", etc.

When there are multiple controlled images, only the controls for the first image function and the controls impact all the images on the page.

**Comment by iangilman** [comment]
Thank you for reporting this! I assume you're using the custom button binding as documented in https://openseadragon.github.io/examples/ui-binding-custom-buttons/? What's not mentioned there is that you can pass the button elements directly instead of using IDs. That should fix your issue. 

I'll mark this as a documentation problem; that page should be updated, as well as the doc comments that create the appropriate documentation at https://openseadragon.github.io/docs/OpenSeadragon.html#.Options. For whoever wants to take that on, the former is in a different repository: 

https://github.com/openseadragon/site-build/blob/master/www/ui-binding-custom-buttons.html

...and the latter is in this repository: 

https://github.com/openseadragon/openseadragon/blob/055699a00aeae886582a3e7f9db2f9f2edf83809/src/openseadragon.js#L540

**Comment by elrayle** [comment]
Thanks for the additional info.  I will take a look at the ui-binding-custom-buttons.

**Comment by shyamkumaryadav** [comment]
@iangilman can i fix it on https://github.com/openseadragon/site-build/blob/master/www/ui-binding-custom-buttons.html ?

**Comment by Mayank1728** [comment]
Hey @iangilman ! Please let me know the documentation changes needed to fix this issue.

**Comment by iangilman** [comment]
@Mayank1728 Just the things mentioned in my comment directly above. So I don't just repeat myself, can you tell me which part you are confused about?

**Comment by KevinBritten** [comment]
I went ahead a made a couple of PRs in the repos listed for this issue. My first open source PRs, please let me know if anything needs to be changed to make things clearer!

**Comment by iangilman** [comment]
@KevinBritten I always love to hear when people make their first open source PR here! Welcome :)
