### ISSUE TITLE
Disabling a button doesn't seem to be working

### ISSUE THREAD

**Issue by atilara** [openseadragon/openseadragon#2185]
Hi!

I'm trying to disable a button using the following code:

```js
viewer.fullPageButton.disable()
```
In this example, the `fullPageButton` should be disabled and clicking on it shouldn't activate its funcionality. But that's not what happens, as you can see in the video: https://drive.google.com/file/d/1towUUBhWgSVJfA3bKTqWYNo8NRRP3X8r/view?usp=sharing

**Comment by pearcetm** [comment]
I've noticed this too and had to work around it before. I think the issue is that the "button" element isn't actually a `<button>` but is instead a `<div>`. Only `<button>` and `<input>` elements become actually disabled from interaction when that property is set (see https://stackoverflow.com/a/37111175/1214731). You can replace these `div` elements with `button` elements and it will work as you expect.

```
// viewer = your viewer instance
let oldbutton = viewer.homeButton.element;
let newbutton = document.createElement('button'); 
newbutton.style = 'padding:0;border:none;outline:none;background:none transparent;'
oldbutton.replaceWith(newbutton);
newbutton.appendChild(oldbutton);

viewer.homeButton.element = newbutton;
//viewer.homeButton.disable() should now work like you expect
```

**Comment by iangilman** [comment]
Wow, that is quite the oversight! It looks like the `disable` call disables the element, but doesn't actually stop the event handling! Here's the disable call: 

https://github.com/openseadragon/openseadragon/blob/bdb44d84fb59e1050e95f6f92613057c24371ba7/src/button.js#L398

... And here's the click handler:

https://github.com/openseadragon/openseadragon/blob/bdb44d84fb59e1050e95f6f92613057c24371ba7/src/button.js#L322

You would expect some sort of check in the click handler to not do anything if it was disabled. 

It should be a relatively quick fix, adding disabled checks to all of the event handlers. 

Also, good point from @pearcetm; using a `<button>` or `<input>` would make the existing `this.element.disabled = true` function as expected. I suppose that's how this bug got here... Perhaps these buttons originally were one of those element types. 

Anyway, at this point, I think the way forward is to put explicit checks inside the handlers. If you're up for it @atilara, I would welcome a PR with that! Otherwise, hopefully someone else will take it on :)

**Comment by pearcetm** [comment]
I noticed that my hacky attempt at a workaround doesn't actually work, since it appears to break the MouseTracker. It would be nice to find a quick-fix type of workaround that can be applied as a patch after creating a viewer instead of having to modify the OpenSeadragon source code - it would be helpful even after a PR with a permanent fix is made and approved (when using a CDN for example). I'll have to think more about how to get this to actually work.

**Comment by pearcetm** [comment]
Ok, I think this is actually a functional way to patch the current issue - enable/disable the mouse tracker at the same time as enable/disable is called on the button:
```
let olddisable=OpenSeadragon.Button.prototype.disable;
let oldenable=OpenSeadragon.Button.prototype.enable;
OpenSeadragon.Button.prototype.disable=function(){olddisable.call(this); this.tracker.setTracking(false); }; OpenSeadragon.Button.prototype.enable=function(){oldenable.call(this); this.tracker.setTracking(true); }
```
 A similar approach could be used as a cleaner fix than adding a disabled check to every handler:

    /**
     * @function
     */
    disable: function(){
        this.notifyGroupExit();
        this.element.disabled = true;
        this.tracker.setTracking(false); /<---- new line
        $.setElementOpacity( this.element, 0.2, true );
    },

    /**
     * @function
     */
    enable: function(){
        this.element.disabled = false;
        this.tracker.setTracking(true); /<---- new line
        $.setElementOpacity( this.element, 1.0, true );
        this.notifyGroupEnter();
    },

To me, this causes the expected behavior of disabling a button (and restoring functionality on re-enabling). However, I'm not sure if there are cases where this might break some kind of desired effect that would rely on having the MouseTracker enabled even on disabled buttons... @iangilman, thoughts?

**Comment by iangilman** [comment]
@pearcetm That's a very elegant solution! I don't think there would be any negative side effects... When you disable button, you pretty much want all of its event tracking to go away (until you re-enable), so this seems like it fits the bill. 

Would you be up for making a PR with this fix? Would be great to have :)

**Comment by atilara** [comment]
That's great! Glad I was able to bring something valid and sad I didn't have the time to help coding. Thanks for the fix @pearcetm.
@iangilman, sorry to disturb you, but do you have a prediction on when the next release with this fix will happen?

**Comment by pearcetm** [comment]
@atilara In the meantime, I think the following should work - put this before you initialize a viewer:

```
OpenSeadragon.Button.prototype.disable = function(){
    this.notifyGroupExit();
    this.element.disabled = true;
    this.tracker.setTracking(false);
    OpenSeadragon.setElementOpacity( this.element, 0.2, true );
}

OpenSeadragon.Button.prototype.enable = function(){
    this.element.disabled = false;
    this.tracker.setTracking(true);
    OpenSeadragon.setElementOpacity( this.element, 1.0, true );
    this.notifyGroupEnter();
}

```

**Comment by iangilman** [comment]
@atilara We usually don't do releases more than once every six months, and we recently did one, but we've also just merged a few good bug fixes, so I've been thinking it might be worth doing a new release sooner (maybe in the coming month?).

**Comment by atilara** [comment]
Okay! Thank you both for taking your time to answer!
