### ISSUE TITLE
Safari 13 rotated tiles

### ISSUE THREAD

**Issue by ozgunlu** [openseadragon/openseadragon#2209]
I used Php Deepzoom to convert jpg to dzi.

File names like column_row.jpg in different layer folder.
![Screenshot_12](https://user-images.githubusercontent.com/47758022/194017078-5e4d6427-dd36-4d5c-9a9f-dcac2c78456b.png)
![Screenshot_13](https://user-images.githubusercontent.com/47758022/194017104-a6819425-c53a-4362-bd86-629f30b6d9ab.png)

It works on Chrome browser. But in safari all tiles rotated to right automatically after osd has loaded.

![Screenshot_14](https://user-images.githubusercontent.com/47758022/194017687-2aa6ce9d-963c-44ff-b050-404a55f1d371.png)

`<script src="https://cdnjs.cloudflare.com/ajax/libs/openseadragon/3.1.0/openseadragon.min.js"></script>`
viewer = OpenSeadragon({
    id: "viewer",
    prefixUrl: "//openseadragon.github.io/openseadragon/images/",
    tileSources: tile_sources,
    sequenceMode: true
});

**Comment by iangilman** [comment]
Wow, that's strange! I wonder why it would be different on Safari versus Chrome. Have you seen this with any other OSD images online? If not, would you mind sharing or posting the image you made?

**Comment by iangilman** [comment]
@ozgunlu It looks like your JPGs have orientation metadata in them that causes them to rotate. This is a feature in image files used by cameras, for instance, to indicate that the camera was rotated when the picture was taken. It can be stored in the exif portion of the JPG... I'm not sure if there are other places it might appear. At any rate, I downloaded one of the tiles from the first image and opened it up in an image viewer that honors the rotation (Mac's Preview app), and sure enough it was rotated. I downloaded one of the tiles from the second image, and it was not rotated. 

The reason you're seeing this in Safari is that evidently it honors the orientation metadata, whereas the other browsers ignore it. 

The fix is to find the orientation metadata and remove it. You might be able to update the DZI script you're using to automatically do so. It is odd that it's putting it in there... Perhaps it's just passing through the metadata that it got from the original image?

**Comment by ozgunlu** [comment]
@iangilman Thank you so so so so much. I have tried everything for 4 days, i was about to go crazy :) 
I faced this exif problem when the image parsing to tiles. I used below code to avoid this problem. 
`$img->orientate(); ` 

You are really to hero for me, thanks again. I will remove exif data using some code.

**Comment by ozgunlu** [comment]
For php here is the solution;

```
$src_img = $imageManager->make($path);
      $src_img->orientate();
      // to remove exif orientation
      $profiles = $src_img->getCore()->getImageProfiles("icc", true);
      $src_img->getCore()->stripImage();
      if(!empty($profiles)) {
          $src_img->profileImage("icc", $profiles['icc']);
      }
```

**Comment by iangilman** [comment]
@ozgunlu Wonderful! I'm glad I was able to help point you in the right direction :) Thank you for sharing the solution code; that may be helpful for other people who have this issue. 

This seems like it would be a good fix to add directly into https://github.com/jeremytubbs/deepzoom... You might consider making a pull request there!
