### ISSUE TITLE
fitBoundsWithConstraints only respects constraints when called with the immediate flag

### ISSUE THREAD

**Issue by jonw-cogapp** [openseadragon/openseadragon#2292]
I [created a pen for this here](https://codepen.io/jonw-cogapp/pen/VwBNoaa) that should illustrate what I'm talking about.

Essentially it seems like when [`fitBoundsWithConstraints`](http://openseadragon.github.io/docs/OpenSeadragon.Viewport.html#fitBoundsWithConstraints) is called with a rectangle that would violate the constraints, they aren't applied correctly, allowing the image to be zoomed in beyond maxZoom.

Is this expected behaviour, or a bug / something specific to my config?

**Comment by pearcetm** [comment]
This looks like a bug to me. I think it's related to some logic I added in https://github.com/openseadragon/openseadragon/pull/2249 - it applies the boundary (pan) constraints, but doesn't take the zoom constraints into account. This is because `_applyBoundaryConstraints` is separate from `_applyZoomConstraints`, and only the constrained bounds are considered when it is not immediate.

I'll have to think more about how to fix this...
