### ISSUE TITLE
Navigator displayArea not true in  maxzoomlevel more than 80

### ISSUE THREAD

**Issue by donotloveshampo** [openseadragon/openseadragon#2314]
in this link  https://codepen.io/iangilman/pen/yrGzYZ，set maxZoomLevel = 160，

At a relatively large magnification, the visible area of ​​the navigation map has a relatively large error

**Comment by iangilman** [comment]
I see! Looks like the display area gets smaller and smaller and then starts growing again as you zoom in.

I suspect it's because of this line:

https://github.com/openseadragon/openseadragon/blob/bf06f271c6ed7d1c1e3fdaf155ca3e9ce4d02396/src/navigator.js#L405

… Along with this line:

https://github.com/openseadragon/openseadragon/blob/bf06f271c6ed7d1c1e3fdaf155ca3e9ce4d02396/src/navigator.js#L396

Eventually the area is smaller than the totalBorderWidths, so the width and height become negative, but since we get the absolute value, the result is that they grow.

The fix should be as simple as removing those two `Math.abs` calls.

Are you up for making a PR to fix it? If not, hopefully someone else will take an interest… either way, thank you for the bug report!

**Comment by MohitBansal321** [comment]
would you assign this issue to me @iangilman I will try it
