### ISSUE TITLE
Sync viewers containing images with different sizes and scales

### ISSUE THREAD

**Issue by lcl45** [openseadragon/openseadragon#2345]
Hi,

first of all thanks for the great work! 
My use case is a little bit specific: I have some wsi (whole slide images) slides which I want to show one next to each other. I want to make sure that any operation done on one image is reflected to the other one, like zooming and panning. This would seem simple enough but now I have to consider that the images are **not** always of the same size and scale.

I've found this codepen https://codepen.io/iangilman/pen/BpwBJe in which the images are the same and pan/zoom accordigly, but modifying it a little bit (https://codepen.io/lcl45/pen/PoyJwyM) gives me a strage result (for me at least): what I want to do is to pan the **same point** between the two images (or zooming). Like, if I pan clicking on the center of the left image I want the right one to pan also from the center of it. You can see the "error" in particular from the start since the two images get aligned on the top side but i want, instead, to be aligned on the center.

In all of this, I want to make also sure that the same pan is applied across images with different scales. Unfortunatly I can't manage to make it work on codepen: what I get for now, is that one image is moving faster than the other across the screen.
What I've done for now is to transform the center of the dragging one in image coordinates, which will then be re-transformed in viewport coordinates of the other image, still not solving the scale issue. I think, however, that a better solution might exist so I'm asking for a solution to this problem.

Thanks a lot!!

**Comment by iangilman** [comment]
I'm just thinking about this now, but it occurs to me what might work best for this scenario would be to lay the images out so that their viewport coordinates match up. For instance, if image A is 2:1 aspect ratio and image B is 1:2 aspect ratio, you could load them in so viewer1 has: 

```
tileSources: {
    x: -1,
    y: -0.5,
    width: 2, 
    tileSource: 'a.dzi'
}
```

... And viewer2 has:

```
tileSources: {
    x: -0.5,
    y: -1,
    width: 1, 
    tileSource: 'b.dzi'
}
```

This will line up their centers at (0,0) and make them overlap each other as much as possible.

**Comment by lcl45** [comment]
Thanks a lot! I'll give it a try as soon as possible and will let you know how it goes.

**Comment by lcl45** [comment]
Maybe I'm missing something. I'm declaring my openSeadragon instance with the following code
```js
let openSeaDragon = OpenSeadragon({
    element: containerDiv,
    animationTime: 1,
    zoomPerScroll: 1.25,
    showNavigator: true,
    showNavigationControl: false,
    tileSources: {
        height: imageHeight,
        width: imageWidth,
        tileSize: 512,
        getTileUrl: (level, x, y) => tileUrl(apImage, level, x, y),
    },
});
```
where `tileSources.height` and `tileSource.width` are the actual image sizes (that, just for the sake of the example, are 41216 and 104448). 
Setting `x` and `y` as you did doesn't do anything and the viewport still remains the same. 
What am I missing?

**Comment by iangilman** [comment]
Yeah, the `tileSources` interface can be pretty confusing! Here's some more info on it: 

https://openseadragon.github.io/examples/multi-image/

In your case, this should work: 

```
let openSeaDragon = OpenSeadragon({
    element: containerDiv,
    animationTime: 1,
    zoomPerScroll: 1.25,
    showNavigator: true,
    showNavigationControl: false,
    tileSources: {
        tileSource: {
            height: imageHeight,
            width: imageWidth,
            tileSize: 512,
            getTileUrl: (level, x, y) => tileUrl(apImage, level, x, y),
        },
        x: -imageWidth / 2,
        y: -imageHeight / 2,
        width: imageWidth
        // We don't specify height here because OSD uses the aspect ratio from the tileSource. 
    },
});
```

The entire object put in the `tileSources` is something we don't have a good name for but maybe you could call it a "open specification". It includes the actual `tileSource` but also some additional positioning information. Note that the width and height you pass into the tileSource is in image coordinates (the actual pixels of the image), whereas the x, y, and width you put in the open specification are in viewport coordinates, which are arbitrary. You can, as in this case, use the same coordinates for each, but you might not want to; for instance, if you have two images with different sizes, but the same aspect ratio, you might want them to overlap each other exactly, rather than being locked to their original sizes. 

More about coordinate systems here:

https://openseadragon.github.io/examples/viewport-coordinates/

I hope all that makes sense!

**Comment by iangilman** [comment]
@lcl45 Great! This seems like an elegant solution. Thank you for sharing your zoom level code :)
