### ISSUE TITLE
Rotate the navigator's display region instead of the navigator's image

### ISSUE THREAD

**Issue by lcl45** [openseadragon/openseadragon#2353]
Hi all!
I was wondering if it is possible to rotate the navigator's display region instead of the whole image. The image attached was obtained by simply modifying the region's css via the chrome console.

![image](https://github.com/openseadragon/openseadragon/assets/55741703/ec51b420-ccff-45eb-b5e6-68f1d5b99209)

**Comment by iangilman** [comment]
I believe it's not possible at the moment, but it seems like a good feature!

To implement this, we'll need to update the `Navigator` function `update`: 

https://github.com/openseadragon/openseadragon/blob/6981cfed0195011ed4191cde9965157388f78e69/src/navigator.js#L363

... So that it rotates the red rectangle properly. 

We already have a `navigatorRotate` option that defaults to true. If you set it to false, the navigator doesn't rotate (but neither does the red rectangle). I figure we should just rotate the red rectangle when navigatorRotate is false, since that's more accurate. 

@lcl45 Thank you for suggesting this! Let me know if you're interested in working on the feature. Otherwise, hopefully someone else will take an interest :)

**Comment by lcl45** [comment]
I rapidly tested this by adding the following lines at line 406 in the navigator's update function you mentioned and it seemed to work as I expected.
```javascript
if (!this._navigatorRotate) {
    var degrees = viewport.getRotation(true);
    _setTransformRotate(this.displayRegion, -degrees);
}
```
The `_navigatorRotate` variable was set earlier during the navigator's initialization.
At first glance it looks wrong because it rotates in the opposite direction compared to the image but in the end, focusing on the viewport's corners, it actually make sense (i hope lol). I also tested the image pan and is seems correct.
Do you think this could be enough or is there anything more to do that I'm missing (like events or something like that)?

**Comment by iangilman** [comment]
That's probably all we need! The event handling is already hooked up. Would you be up for making a PR with this change?
