### ISSUE TITLE
Performance question / issue with frame rate when tiling on 4K displays

### ISSUE THREAD

**Issue by jetic83** [openseadragon/openseadragon#2384]
I observe sever tiling issues for our pathology viewer app on 4K screens, Windows 11 and Chrome 114.0.5735.199.

We use a custom tilesource, but the effect is the same on a regular DZI tilesource.

Basically, it's about following:
- on large screens, the viewer sources 50+ tiles
- I saw that the corresponding jobs are added within 3ms.
- the jobs are not queued, but immediately started.
- the image.src tag is set to the proper tile source immedeatly.

So, the jobs for the tiles are done very quick within ms.

BUT, the queries for the tiles go out of chrome within 1-2 seconds.

I attached a video showing the tiling effect, and also how the queries have been loaded in the client (within 4 seconds).

I am puzzled since according to the jobs in OSD, the queries should go out within a few ms. why are they taking so long?

I suspect the update workflow of the canvas itself, or the requestAnimationFrame function, or similar. 

Does anyone have some idea where I could look at?

Note, that of course, I could to the tiles larger, but I query them based on how they are saved in the source file. Also, this would not explain my actual question why the tile jobs are added and executed within ms, but the queries in the browser are sent within seconds.

This might be related to #2216

https://github.com/openseadragon/openseadragon/assets/11157551/6a3cbbf6-ed0b-4076-8ba0-2ea05d56f2f2

![image](https://github.com/openseadragon/openseadragon/assets/11157551/d1f7a530-99c4-4f03-8a15-25d984261f87)

<img width="443" alt="image" src="https://github.com/openseadragon/openseadragon/assets/11157551/dca63667-1114-458b-b968-79550faae647">
The last tiles are queried 3s after the first tiles.

<img width="467" alt="image" src="https://github.com/openseadragon/openseadragon/assets/11157551/9161f8c0-045b-4795-91bb-507e8dfea946">
The queries come from the image loader, tiledimage and drawer. But where should I look closely to get queries that are immediately sent after the job is done?

**Comment by iangilman** [comment]
The update architecture for each tiled image is that every frame it looks for the best tile to load and starts loading it. Since it's firing off one request per frame, it's firing approximately 60 requests per second (or less depending on the performance of the computer). If you have 180 tiles to load, the last tile will be requested after three seconds or so. 

This design has worked well for over a decade, but it's possible it's time for us to start loading more tiles in parallel now that we have such big displays (along with internet connections that can handle big blasts). That said, regardless, using bigger tiles would definitely be a win, if you can swing it. 

Would you be interested in investigating making it possible to load tiles in parallel? If you are, or if someone else is, here are some thoughts: 

Right now, the TiledImage collects a `bestTile` during the update process and fires off a load request using `_loadTile`. I guess we just need to turn that into an array sorted by "best-ness" and fire off requests for the top N tiles. We'll want an option on the viewer that specifies how many tiles to do in parallel. 

BTW, @pearcetm has been making some big changes in `TiledImage` as part of https://github.com/openseadragon/openseadragon/pull/2310... Might be good to coordinate with him to make sure no one steps on anyone's toes.

**Comment by jetic83** [comment]
Hi @iangilman thanks for the nice explanation and potential points to look at. 

I would be happy to investigate this further (as I did already) and will coordinate with @pearcetm . It might be as easy as you said, and a quick improvement before the even more powerful webGL solution lands.

**Comment by pearcetm** [comment]
@jetic83 I don't think the changes to `TiledImage` that I've made as part of the drawer refactoring/`webgl` enhancement affect the tile request process at all - some calls just got moved around a bit. If you come up with a solution, I'll just have to figure out how to integrated it into that PR too (if it can't be merged automatically). The merging process will hopefully be straightforward, but could potentially be annoying if it touches a bunch of refactored code. If you're up for helping me figure out that part of it whenever we get to that point, that would be great!

**Comment by iangilman** [comment]
@jetic83 Great! Let me know if you need any more pointers. 

@pearcetm Thank you for weighing in... Having the two of you coordinate sounds good.

**Comment by jetic83** [comment]
Hi @pearcetm , I made few changes in tiledImage.js (_updateLevel, _updateTile and _compareTiles), and I saw that you also changed the first two functions a bit on this section.
But according to what I saw, the conflicts should be relatively easily solvable. I can help with that of course.

**Comment by iangilman** [comment]
Fixed by #2387
