### ISSUE TITLE
Viewport.getBounds reports wrong bounds

### ISSUE THREAD

**Issue by geoff-harper** [openseadragon/openseadragon#2423]
I've noticed that my `getBounds` calls are not returning with expected results. [In the repro I made](https://codesandbox.io/s/openseadragon-forked-932x5p?file=/src/index.js) you can keep your cursor still and just mouse wheel zoom to see the issue. While you zoom in the numbers will increment in one direction. On the first zoom out event, the numbers should begin decrementing but they increment one last time before then beginning to decrement on subsequent events. Visually it's fine but it seems like the viewport bounds are always a step behind (maybe the `current=false` arg isn't being respected?). It's easiest to see if your mouse wheel has large discrete steps. I can't verify that the same issue is present for panning since the steps are much smaller

**Comment by pearcetm** [comment]
The problem is the `canvas-scroll` event that you're binding to is raised before the navigation occurs. This lets you modify/cancel the event or do other things that could change viewer behavior. The `viewport-change` event might work better for you, if you're looking for the bounds after they've been modified. If you want to stick with `canvas-scroll`, you can check bounds after the event has finished like so:

```
viewer.addHandler("canvas-scroll", () =>
  window.setTimeout( () => console.log(viewer.viewport.getBounds().toString()) );
);

```

**Comment by geoff-harper** [comment]
You're right that `viewport-change` is what I want. Working much nicer now thanks
