### ISSUE TITLE
Upgrade insecure requests 

### ISSUE THREAD

**Issue by filak** [openseadragon/openseadragon#2436]
Sometimes it happens that an IIIF source returns info.json with id containing insecure URL. When accessed directly the insecure URLs might get being redirected to https.  

When using such a source in OSD it can lead to multiple problems - mixed content warnings, XHR errors etc.

It would be nice to have an option to override all the subsequent requests made by OSD to https.

**Comment by Aiosa** [comment]
I think this is a specific usecase related to invalid data origin rather than issue with OSD. If server(s) decided to redirect requests to HTTPS it should fix its data as well.

You could override the URL scheme manually, e.g. using https://openseadragon.github.io/docs/OpenSeadragon.World.html#.event:add-item
```
viewer.world.getItemAt(<index>).addHandler('add-item', e => {
       const source = e.item.source;
       //modify the source manually to change http-->https
       //check @context and @id properties 
});
```
You can hit a dev tools breakpoint on the source element and see which parts of the object need to be overridden.

**Comment by filak** [comment]
Thanks, nice tip, I will try that.
