### ISSUE TITLE
Index bigger than number of layers when loading in multilayer IIIF images

### ISSUE THREAD

**Issue by BeebBenjamin** [openseadragon/openseadragon#2457]
We are loading in manifests that contain images with multiple layers, the `index` value for example is `4` (so 5 layers). I have noticed that OSD throws an error when the `index` value is bigger than or equal to the number of layers when loading these in.  For us, this is naturally because the layers are loading in asynchronously, and the count is sometimes initially smaller when this function is called, sometimes we do not get the error on a refresh.  I have a feeling that something is not quite right.

**Comment by pearcetm** [comment]
How are you actually loading these into the viewer once the information is available asynchronously? With `viewer.addTiledImage()`? Or some other way?

**Comment by BeebBenjamin** [comment]
I will have to look at Mirador viewer and get back to you.

**Comment by BeebBenjamin** [comment]
@pearcetm Mirador uses viewer.addTiledImage() in it's `OpenSeadragonViewer` component.

**Comment by BeebBenjamin** [comment]
Here is the section:
```javascript
viewer.addTiledImage({
        error: event => reject(event),
        fitBounds: new OpenSeadragon.Rect(
          ...canvasWorld.contentResourceToWorldCoordinates(contentResource),
        ),
        index: canvasWorld.layerIndexOfImageResource(contentResource),
        opacity: canvasWorld.layerOpacityOfImageResource(contentResource),
        success: event => resolve(event),
        tileSource,
      });
```

**Comment by BeebBenjamin** [comment]
Here it is in context: https://github.com/ProjectMirador/mirador/blob/5cb692ed31480c1e130f4a8715726688cb35796d/src/components/OpenSeadragonViewer.js#L229

**Comment by pearcetm** [comment]
I can't tell just from the code what is going on. Is there a demo page that shows the behavior you're describing? What is the error message you're seeing?

OSD can add tiled images with index undefined, and doesn't have a problem if an index is greater than `viewer.world.getItemCount()+1`, and even handles negative numbers as the index.

You might try using the debugger to see what value is being returned from `canvasWorld.layerIndexOfImageResource(contentResource)` and other mirador-specific calls.

**Comment by iangilman** [comment]
> I have noticed that OSD throws an error when the index value is bigger than or equal to the number of layers when loading these in.

What index value?

**Comment by BeebBenjamin** [comment]
Sure here: https://iiif.bodleian.ox.ac.uk/iiif/mirador/?iiif-content=https://iiif.bodleian.ox.ac.uk/iiif/manifest/1fc3f35d-bbb5-4524-8fbe-a5bcb5468be2.json

**Comment by pearcetm** [comment]
Ok, so the error is being thrown from `World.setImageIndex()`. It looks like there's a mismatch between what mirador thinks the "layer index" is (or can be) versus the number of images that have actually been loaded into viewer at the time. This is because mirador (or your application) knows about all the images that will eventually be loaded, while OSD only knows about those that have already been added to the viewer. In a viewer with only one image, it doesn't make sense to tell it that the image should be at `index = 4` in the array - so OSD throws an error.

There are probably a number of ways this could be handled, but keeping track within mirador/application code of which images have actually been added to the viewer, and what index they are within the `viewer.world`, is probably the best approach.

**Comment by BeebBenjamin** [comment]
There is a bug is Mirador 3 that might related to this issue: https://github.com/ProjectMirador/mirador/issues/3585

**Comment by BeebBenjamin** [comment]
Closing this issue, becuase I think it's caused by Mirador and not OSD.
