### ISSUE TITLE
Set navigator width and height but Stay in the last position

### ISSUE THREAD

**Issue by w5c17** [openseadragon/openseadragon#2490]
Hello, I have a problem. Why is the viewport still in the same position after I modified the width and height of the navigation diagram? I tried update but it didn't work, could you please answer it for me, thank you for your reply

**Comment by iangilman** [comment]
The navigator just shows where you currently are... It doesn't pan or zoom you to a new location. What are you trying to accomplish, and what have you tried so far?

**Comment by w5c17** [comment]
For example, in the following three pictures, when my navigation chart is 200*200, it displays normally. Later, I changed the size of the navigation chart to 350*350, and the viewport seemed to be shifted due to the size of the navigation chart, and it only showed the correct position after I shifted it. I tried using `viewer.navigator.update`, but it didn't seem to work, could you please help me find out the reason, thank you

![企业微信截图_17096017056131](https://github.com/openseadragon/openseadragon/assets/47955766/b5c32393-9e76-4469-9f70-4a9c03c479e1)
![企业微信截图_17096017186347](https://github.com/openseadragon/openseadragon/assets/47955766/7dc81791-f6b7-4498-9af5-86cbae680edb)
![企业微信截图_17096017426464](https://github.com/openseadragon/openseadragon/assets/47955766/17d63dc0-ba1e-425d-bf34-70d84448fe1f)

**Comment by pearcetm** [comment]
Looks like a bug - this should automatically update when the navigator is resized. Thanks for reporting! This will be fixed by https://github.com/openseadragon/openseadragon/pull/2491 (luckily a simple fix).

In terms of an immediate fix for your own code, you were on the right track, but missing a parameter for `navigator.update()` - you need to pass in the viewer's viewport:

`viewer.navigator.update(viewer.viewport)`
