### ISSUE TITLE
When I create tiles from a tif image where the newly formed tiles are also in tif format, openseadragon does not load the images. I want to load the tiff format tiles, kindly help me out.

### ISSUE THREAD

**Issue by souravsarkarnew** [openseadragon/openseadragon#2496]

**Comment by iangilman** [comment]
According to https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Image_types only one browser supports TIFF images: Safari. Is your plan to only work on that one browser? If so, you can tell OSD to allow TIFF files using:

```
viewer.setImageFormatsSupported({ tif: true, tiff: true });
```

Depending upon your scenario, you might consider converting your TIFF tiles to JPEG for delivery in order to make your network transfers quicker. Or if you need to be lossless, PNG is supported in all browsers.

**Comment by souravsarkarnew** [comment]
Thanks for the response. I am currently on a linux machine and plan to work on this only so its either firefox, chrome or edge.

**Comment by souravsarkarnew** [comment]
I am using dzi

**Comment by iangilman** [comment]
Cool. It should be easy to convert your TIFF into a DZI with JPEG tiles then. :)

**Comment by souravsarkarnew** [comment]
I want to use tif tiles only cause that is the best quality i can get, is there any other plug in you can suggest instead of deepzoom that can support tif tiles in openseadragon in firefox or chrome in ubuntu?

**Comment by Aiosa** [comment]
You can also spin up an image server that reads TIFF and feeds JPG/PNG to the viewer, e.g. IIPImage server. https://iipimage.sourceforge.io/
