### ISSUE TITLE
tile bdys and cross-origin error with webgl default

### ISSUE THREAD

**Issue by bdrichards** [openseadragon/openseadragon#2519]
after fixing the tile bdy issue with png tiles in #2514 , I now attempt to use my new master build (which says it is 4.1.1) with a viewer that accesses Gigapan.com tile sources. This viewer has operated just fin for about ten years, but the knew (yet to be released) webgl default drawer cause this message:
"WebGL cannot be used to draw this TiledImage because it has tainted data. Does crossOriginPolicy need to be set?"
(webgldrawer.js:888 WebGL cannot be used to draw this TiledImage because it has tainted data. Does crossOriginPolicy need to be set?)

PLUS - I am seeing tile boundaries on some systems. If I revert back to OSD 3 or earlier, I am fine, but both of my viewer webpages feed from the same source directory.
The gigapan.com tilepyramid source is all jpg (no png).
If I access only locally hosted gigapan tile pyramids, all is fine. But I have another webpage that access the tilesource directly on the gigapan.com site and have had no issues since at least 2015.
Here is test link that shows message - some times it is alert, sometimes error (tile bdys show up as faint white lines only on some systems):
[https://br1.nic.edu/gpan/?id=31687&x]

I guess my question is how to set "drawer" option to force NOT webgl or how to set option to handle the warning/error - looked through options documentation, but of course nothing there yet?

**Comment by pearcetm** [comment]
As far as tainted data, try setting `crossOriginPolicy: 'Anonymous'` - if the server allows it, this should enable the WebGL drawer to use the image data correctlyl.

If you don't need WebGL you can also specify `drawer: 'canvas'`. However, other issues may arise.

>  I am seeing tile boundaries on some systems.

The link you provided does show tile borders. Will have to look further into this case.

**Comment by pearcetm** [comment]
Ok, what's happening here is that gigapan.com does not have CORS enabled, so the `webgl` drawer can't render the images (because tainted data can't be used by webgl for security reasons). Under the hood, the drawer falls back to using `canvas` - but it isn't enforcing a minimum tile overlap, and the tile source has no intrinsic overlap.

I'll be submitting a PR to make this work automatically. In the meantime, there are a couple of ways to work around this:
- For this tile source, just specify `drawer: 'canvas'` in your viewer options
- If you want to use `drawer: 'webgl'` (which is the default if you don't specify), you can add the following after the viewer is created: `viewer.drawer.minimumOverlapRequired = function(){ return this._backupCanvasDrawer }`. This will make the `TiledImage` do the positioning correctly to avoid seams when the `canvas` drawer is used as a fallback. Note that if you open multiple tile sources in the same viewer and only some of them need the canvas drawer you'll be introducing subtle artifacts into the other image(s) that use `webgl` - but if you only open a single image, it will work fine.

**Comment by bdrichards** [comment]
Thank you @pearcetm 

> ...try setting `crossOriginPolicy: 'Anonymous'`

As you relate, the gigapan.com server(s) won't allow this! And the tiles on gigapan.com server(s) are all jpg with _size: 256, overlap: 0_
> ...specify `drawer: 'canvas'` in your viewer options

Works fine all by itself (forcing the 'canvas' drawer)!

>  ...add the following after the viewer is created: `viewer.drawer.minimumOverlapRequired = function(){ return this._backupCanvasDrawer }`

Works when 'webgl' default drawer is used!
> ...Note that if you open multiple tile sources in the same viewer and only some of them need the canvas drawer...

At present, our only intent when opening two tile sources in same viewer would be to overlay two different version of same image for comparison and they will have the same drawer requirements (at least that is the idea in our early testing - not ready for prime time yet).
Thanks again for the quick reply! If you are testing more with our link, please use this one: [https://br1.nic.edu/gpan/indextmp.html?id=31687&x]
