### ISSUE TITLE
TiledImage viewportToImageCoordinates seems to ignore position of image

### ISSUE THREAD

**Issue by heatherhosler** [openseadragon/openseadragon#2593]
This is an extension / update to the following question https://github.com/openseadragon/openseadragon/issues/776

I want to click on the image and get an image coordinate (in pixels of my largest zoom level) of the click location. I believe this is the same goal as the original question above.

I tried to loop through the tiles, but the `lastDrawn` doesn't seem to be accessible any more.

When I pull out the tiled image from the viewer with:

`var tiledImage = viewer.world.getItemAt(0)`

Everything in the tiledImage object seems to ignore the fact that I've zoomed and/or dragged the image around.

I will always get the following, no matter where the image is (zoomed, dragged around etc, but my project doesn't have rotation).
```
tiledImage.getBounds(): 
$.Rect
degrees: 0
height: 1
width: 1
x: 0
y: 0

tiledImage.getClippedBounds():
$.Rect
degrees: 0
height: 1
width: 1
x: 0
y: 0
```

The `viewportToImageCoordinates` function also gives me the image coordinates, but seemingly only scaled by the pixels in the largest zoom layer of the image, if it was all displayed in the viewport, rather than where the image currently is.

**Comment by pearcetm** [comment]
You'll want to use a click handler to get the position of the click relative to the viewer element (or, more specifically, the canvas element), and then convert the position of the click into to pixel coordinates of the base image. Something like this is probably a good starting point:

```
viewer.addHandler('canvas-click', ev => { 
   ev.preventDefaultAction = true; // stop click-to-zoom
   console.log('Position of click on canvas', ev.position);
   console.log('Position in image coordinates', viewer.viewport.viewerElementToImageCoordinates(ev.position));
});

```

**Comment by iangilman** [comment]
@pearcetm's example is correct. It works because the `canvas-click` event gives its `position` in web coordinates, which change with zoom and pan. The purpose of viewport coordinates is to be consistent regardless of zoom and pan (as you've discovered). You can learn more about the coordinate systems here:

https://openseadragon.github.io/examples/viewport-coordinates/

Note that @pearcetm's example assumes you have only one image in your viewer... `viewer.viewport.viewerElementToImageCoordinates` is a shortcut to `viewer.world.getItemAt(0).viewerElementToImageCoordinates` but it gives you a warning if there is more than one image.

**Comment by msalsbery** [comment]
I have reread #776 several times, and I am convinced this is the solution that author wanted as well. If not, I'm really curious what that use case was 😄

**Comment by heatherhosler** [comment]
Thank you! The information that I was previously missing was that the web coordinates change with zoom & pan, and that viewerElementToImageCoordinates could directly take web coordinates as input. My initial tests seem to be working.
