### ISSUE TITLE
HTML needs to be escaped in comments

### ISSUE THREAD

**Issue by avandecreme** [openseadragon/openseadragon#410]
For example  a canvas element is created there: http://openseadragon.github.io/docs/OpenSeadragon.Viewer.html#event:tile-drawing

There might be other locations.

**Comment by ujjwalpandey922** [comment]
Hi,
I am new to open source and wanted to give my first contribution can you assign this issue to me.

**Comment by iangilman** [comment]
@ujjwalpandey922 Welcome! I've assigned it to you now. Let me know if you need any pointers :)

**Comment by sumitshinde-84** [comment]
i would like to work on this issue , can you please assign it to me?

**Comment by sumitshinde-84** [comment]
i would like to work on this issue , can you please assign it to me?

**Comment by iangilman** [comment]
@ujjwalpandey922 Are you still interested in working on this? 

@sumitshinde-84 If we don't hear back from @ujjwalpandey922 in the next week or so, consider it yours! Of course, there should be other issues you can tackle if you want to look around...

**Comment by sumitshinde-84** [comment]
Before diving in this issue I need more information about it .

**Comment by msalsbery** [comment]
@ujjwalpandey922 @sumitshinde-84 

The docs at https://openseadragon.github.io/docs/ are generated by jsdoc from comments in the source code.

The jsdoc settings allow HTML in the comments for formatting. So any place we want to show HTML source instead of embedding HTML element(s) in the comment text, we need to make sure to escape the brackets (eg use &lt; &gt;)

I don't know of any specific places where we've forgotten to escape the HTML...we fixed some back when this issue was active ;)

**Comment by iangilman** [comment]
@msalsbery Sure enough, I just did a search and found that there are no more un-escaped HTML bits in our doc comments (except for all the places where we want them to actually be HTML)! This issue can be closed. 

@ujjwalpandey922 @sumitshinde-84 Apologies for not cleaning this issue up earlier! If you're still interested in contributing to this project, there are a number of additional issues marked "good first issue": 

https://github.com/openseadragon/openseadragon/labels/good%20first%20issue

Just let me know what strikes your fancy!
