### ISSUE TITLE
Drag handling does not release if dragged out of viewer area

### ISSUE THREAD

**Issue by benjamind** [openseadragon/openseadragon#427]
I have my viewer inside an iframe in a page. It works great in general, but when I start to drag the view around and my mouse goes outside of the iframe area it appears the state is lost and the drag remains tied to the mouse pointer.

When I move the mouse back into the iframe area the canvas is still dragging regardless of whether or not I released the mouse button in the meantime. It also fails to recover, in that if I try and drag and release again it remains stuck.

I checked through the code of the MouseTracker but am having a hard time figuring out where this listener is failing to be released. stopTracking does not seem to correctly release it even when called directly.

**Comment by iangilman** [comment]
Now that #790 has landed, do we want to close this, or leave it open for the non-iframe scenario?

**Comment by iangilman** [comment]
Also note that #790 only applies if the iframe and the containing window are on the same domain.

**Comment by HjalmarSnoep** [comment]
I guess you could work around it, by checking if mousemove suddenly stops with near max or min values for x or y. That's the best I came up with for a similar issue after I saw, this one wasn't solved yet.. 
Well not really..
This issue helped me research, so I thought I'd give back.
Here you are.. a working solution.
https://jsfiddle.net/bukesng6/1/

**Comment by msalsbery** [comment]
@benjamind  @nagame-net 

I know this is an OLD issue, but I'm finishing up an event-handling (MouseTracker) patch and I'm curious if the new code improves the issues you're seeing (it should!). The new code uses DOM pointer capture APIs when available instead of simulating pointer capture...this should fix iframe and shadow DOM issues.

If you have a little time to try it out, I would love to hear your feedback!

[Links to Demos and Preview Builds](https://github.com/openseadragon/openseadragon/pull/1872#issuecomment-673608460)

Cheers

**Comment by msalsbery** [comment]
Fixed for v2.5.0 (#1872)

Feel free to reopen if issue persists!
