### ISSUE TITLE
slow down trackpad zoom?

### ISSUE THREAD

**Issue by jrochkind** [openseadragon/openseadragon#470]
With my pretty high resolution image, the two-finger scroll on trackpad to zoom on my macbook... goes really really fast. Like in less movement than you can easily control with your muscles, it's zoomed in our out a disorienting amount. 

Is there any way to slow this down?  Actual scroll-wheel on a mouse seems to work okay; the amount of zoom for the clickable 'zoom in' and 'zoom out' buttons is decent. It's just the two-finger-scroll-on-mac-trackpad that is disorientingly fast.

**Comment by iangilman** [comment]
For a project I recently did, I ended up setting the zoomPerScroll to 1.1 (instead of the default 1.2). Maybe it's time to make that the new default? It may make zooming a bit slow for some people, but I think too slow is probably better than too fast.

**Comment by jrochkind** [comment]
The problem I have is that the current zooming speed is about right for an actual scroll wheel on a mouse (at least the ones I've tried), but way too fast for touch actions on a Mac trackpad.  But the same parameter effects both. So I don't know if I'd want to slow down the scroll wheel mouse thing, unless I had reason to think a lot more users were using a touch pad on a mac than a scroll wheel, and I have no idea.

**Comment by iangilman** [comment]
Fair enough. The challenge is detecting the difference between the two.

**Comment by iangilman** [comment]
I'm wondering if there is anything we can learn from what they do in this plugin?

https://github.com/jquery/jquery-mousewheel

**Comment by iangilman** [comment]
To summarize this issue, it seems like the two possible approaches are to add an extra layer like @jaronkk did, or to do more to try to figure out how to detect the difference between different devices and browsers. 

I’m concerned about adding the extra layer, as it has implications for all mouse event handling in the viewer (as the new layer would capture all mouse events and they would have to be routed properly). This includes figuring out how to make sure we still get scroll events when over overlays, yet the overlays get appropriate mouse events as well. I’m also concerned we might not be able to fully hide the scroll bars that would come up (at least in some systems). 

The challenge with going with detection is that it’s a constant battle, and that some things just may not be detectable. 

A possible third option would be some sort of hybrid with the extra layer where we use it to detect at first, but then get rid of it. We’d still have the eventing issues until we get rid of the layer (which might be never, if the user doesn’t use the scroll wheel), so that’s probably no better than the straight extra layer approach.

**Comment by iangilman** [comment]
I believe this has now been fixed by #754!
