### ISSUE TITLE
Overlay not added to viewer until first animation event but should be on open. 

### ISSUE THREAD

**Issue by ORIGINALUSRNM** [openseadragon/openseadragon#507]
When instantiating a new viewer with an initial overlay, the overlay is not actually drawn until an animation event occurs ( which may not happen when the viewer initially opens).  

I was thinking the overlays should initially be drawn when the viewer has opened instead.

**Comment by sepastian** [comment]
Hello, I need this too, I am trying to bind the `mouseenter` event to overlays. Currently, this is not possible, because no overlay elements will be generated during initialization (`open`).

 When will this be merged into master? The date in the original post is almost 1 year ago...

**Comment by iangilman** [comment]
@sepastian This change is in OpenSeadragon 2.0.0, the current release. Are you having trouble making it work? You do need to wait until the `open` event fires.

**Comment by sepastian** [comment]
Thanks for the reply, @iangilman.

I used `openseadragon-rails`, which is still using openseadragon 1.2. After updating to 2.0, events are arriving - my fault.

However, now the overlays are gone, because they are too big and outside the viewer. I am using this to add overlays:

```
# coffee script
options = {
    :
    tileSources : [{
            :
            overlays: [{
                    width: 200,
                    height: 100,
                    px: 1000,
                    py: 500
            }, ... ]
    }, ... ]
}
viewer = OpenSeadragon(options)
```

Before the upgrade to 2.0.0, this would render overlays as expected (using image coordinates). After the upgrade, when inspecting the HTML, I see

```
<a style="left: 318000px; top: 875648px; position: absolute; display: block; width: 396016px; height: 75472px;" class="article-overlay article-overlay-59" id="openseadragon-overlay-8642962" href="#/overlay/openseadragon-overlay-8642962"></a>
```

The values for `left`, `top`, `height` and `width` don't seem right to me.

Do you know what I am missing?

**Comment by sepastian** [comment]
The other options are:

```
options = {
                        id                    : 'viewer',
                        panHorizontal         : true,
                        defaultZoomLevel      : 1,
                        minZoomLevel          : 0.5,
                        maxZoomLevel          : 10,
                        visibilityRatio       : 0.5,
                        showNavigator         : true,
                        showNavigationControl : true,
                        homeButton            : 'button-home',
                        fullPageButton        : 'button-fullscreen',
                        previousButton        : 'button-previous',
                        nextButton            : 'button-next',
                        sequenceMode          : true,
                        tileSources           : tile_sources
                }
```

**Comment by iangilman** [comment]
@sepastian Looks like we have a bug...because you're using `px` (image coordinates) it needs the image to already be added, but we're not waiting for that. So, where we add the overlays: 

https://github.com/openseadragon/openseadragon/blob/master/src/viewer.js#L632-L638

...needs to go into the success function at: 

https://github.com/openseadragon/openseadragon/blob/master/src/viewer.js#L607

Would you be up for making a patch for that?

**Comment by sepastian** [comment]
Thanks... sure, will look into it tomorrow and see what i can do.
