### ISSUE TITLE
Rotated images cropped in viewport

### ISSUE THREAD

**Issue by sdellis** [openseadragon/openseadragon#567]
Using setRotation(degrees) crops images in the viewport.  Perhaps a simple swap of height and width values before drawing?

See [Site-Build Issue #25](https://github.com/openseadragon/site-build/issues/25) also.

**Comment by iangilman** [comment]
Incidentally, you might try the branch on #446… I did a bit of work with rotation there; maybe I accidentally fixed this issue?

We'll hopefully be merging that branch into master soon, but we haven't yet.

**Comment by sdellis** [comment]
Thanks for the heads-up.  I tried that branch, but the problem is not fixed.  

It seems that there is a ```$.Rect.rotate(degrees)``` method that appropriately swaps the width and height when degrees is set to 90 or 270.  This gets called on setRotation().  However, I'm unsure if the Rect class has anything to do with the the actual image, or if it's only dealing with overlays.  

I thought I would be able to simply set the image dimensions, and then call forceRedraw() from setRotation(), but I can't tell where the image dimensions are being stored.  Any thoughts?

**Comment by iangilman** [comment]
Working with rotation is kind of tricky, because you need to make sure your frame of reference is correct. I think the way we're handling it is that everything inside the Viewport object remains the same regardless of rotation, except when it connects to the "real world", i.e. getting mouse coordinates, drawing to the screen, etc.

In the case of this issue, I think what needs to happen is some compensation in `fitBounds`: 

https://github.com/openseadragon/openseadragon/blob/master/src/viewport.js#L461

...as relates to the container size and aspect ratio.

**Comment by sdellis** [comment]
I'm really struggling with this one.  Are the rotated image dimensions supposed to be represented in the bounds param (aka, newBounds)?  I'm having a difficult time figuring out (even stepping through with a debugger) what is supposed to be happening [here](https://github.com/openseadragon/openseadragon/blob/master/src/viewport.js#L481-L487) but it seems like it's trying to do update the newBounds based on how the image is  oriented compared to the aspect ratio of the container?  

There is also a fitVertically method, but it never gets called.  It references  a contentAspectY variable.  Is that orphaned code?

I've been scratching my head on this for several days now.  I will try to put in some more time when I can, but it's puzzling!

**Comment by iangilman** [comment]
Looking at this again, I'm realizing the only place where rotation is taken into account is just drawing. The coordinate system is not updated at all. Even with mouseclicks, we don't take into account rotation. 

So, one approach might be to build rotation into the Viewport more fully, so that all calculations take rotation into account. Another approach would be to step up a level from fitBounds and instead modify getHomeBounds so it's returning a rectangle in the non-rotated coordinate system that will properly allow for the rotated image to all still be visible. This will basically be this calculation from the Drawer: 

https://github.com/openseadragon/openseadragon/blob/master/src/drawer.js#L400-L415

One thing to keep in mind with that approach is that the constraints will still try to keep you inside the non-rotated home bounds, so going home will work as you like, but then panning or zooming might push you away from the edges. Of course applyConstraints can be updated to include rotation as well. 

Sorry this isn't as straightforward as hoped! Btw, the code you linked to is basically figuring out whether the constraining dimension is the width or the height.

**Comment by iangilman** [comment]
Seems related to #463.

**Comment by iangilman** [comment]
@avandecreme Just to verify: this was actually fixed by #782?

**Comment by avandecreme** [comment]
Correct :)
