### ISSUE TITLE
Multi-tilesource image stacking issue

### ISSUE THREAD

**Issue by edsilv** [openseadragon/openseadragon#629]
Hi,

I've noticed a problem when loading multiple tilesources and displaying them next to each other.

In order to illustrate the problem I've created a test application:

https://github.com/edsilv/openseadragon-tests

When clicking rapidly on the prev/next buttons, occasionally the images are not cleared down correctly and you end up with something like this:

https://docs.google.com/a/unwrong.com/file/d/0ByhfAkKGrtwQV1dXNDdKRkFKYms/edit

or this:

https://docs.google.com/a/unwrong.com/file/d/0ByhfAkKGrtwQeUN6SmdKY0JtZnM/edit

I thought is was possibly my use of viewer.addHandler and viewer.removeHandler (based on a previous example I'd seen) where they were getting added and removed for every load (not sure why that's needed). I'm now only adding the handler once and seems to be no different.

The other possibility was that I needed to use viewer.world.resetItems() before every load, but this didn't help either.

Bit stuck..! Is there anything obvious that I could be doing differently?

**Comment by iangilman** [comment]
Hmm...`open` is async, so if you start a second open before the first one is done, you can probably get this effect. We should fix it so a `close` cancels any in-progress `open`, instead of just clearing what's already been loaded. 

Meanwhile, you might be able to get around it by adding an "open" event handler and not allowing (or queuing) further opens until the current one is done.

**Comment by iangilman** [comment]
Looks like fixing this might be as simple as emptying the `_loadQueue` array on open.

**Comment by iangilman** [comment]
Fixed by #734
