### ISSUE TITLE
Multi-tilesource overlay rect positioning

### ISSUE THREAD

**Issue by edsilv** [openseadragon/openseadragon#639]
Hi,

I'm trying to figure out a way to position overlay rects on a second tiledImage. Currently I'm using this method:

https://github.com/wellcomelibrary/wellcomeplayer-seadragoncenterpanel-module/blob/master/seadragonCenterPanel.ts#L47

Where I'm getting the viewer.source.dimensions for the tiledImage and positioning the rects based on that.

This was my first attempt to get the dimensions of a second tiledImage:

https://github.com/UniversalViewer/universalviewer/blob/master/src/modules/uv-seadragoncenterpanel-module/seadragonCenterPanel.ts#L567

But it seems that there is never more than one available, and anyway, it doesn't contain the original dimensions.

What I need is something like:

```
viewer.sources[1].dimensions
```

Is anything like that possible in the current api?

You can see here where I'm creating the additional tiledImage:

https://github.com/UniversalViewer/universalviewer/blob/master/src/modules/uv-seadragoncenterpanel-module/seadragonCenterPanel.ts#L341

**Comment by iangilman** [comment]
Do you need to use the image pixel coordinates? My recommendation, especially when dealing with multiple tiled images, is to always deal in viewport coordinates. Therefore, if you wanted an overlay that covered the second image exactly, you would do something like: 

```
var box = viewer.world.getItemAt(1).getBounds();
viewer.addOverlay({
  location: box
});
```

**Comment by edsilv** [comment]
I'm attempting to overlay search results as per this json:

http://wellcomelibrary.org/service/iiifsearch?within=http://wellcomelibrary.org/iiif/b18035978/manifest&q=biology

See the "on" property of every resources item.

This contains pixel coordinates. In order to be able to position the overlays, I need to know the original pixel dimensions of the image contained within the info.json for the tilesource. This is currently only available it seems for the first tileSource.

If I run this to get the additional tileSource:

https://github.com/UniversalViewer/universalviewer/blob/master/src/modules/uv-seadragoncenterpanel-module/seadragonCenterPanel.ts#L343

I get `undefined` for `this.viewer.world.getItemAt(1)`. Is this because it hasn't loaded yet? I have an open event handler here:

https://github.com/UniversalViewer/universalviewer/blob/master/src/modules/uv-seadragoncenterpanel-module/seadragonCenterPanel.ts#L218

But this only gets called for the first tileSource, not subsequent additional ones.

**Comment by iangilman** [comment]
Gotcha. How about this?

```
viewer.addTiledImage({
    tileSource: myTileSource,
    success: function(event) {
        var tiledImage = event.item;
        var location = tiledImage.imageToViewportRectangle(overlayLocationRectInImageCoordinates);
        viewer.addOverlay({
            location: location
        });

        // If you need the pixel dimensions for other purposes you can use: 
        var imagePixelDimensions = tiledImage.getContentSize();
    }
});
```

**Comment by edsilv** [comment]
Cool, I've created a quick test for that and I can retrieve the image dimensions.

I'm wondering now though if I'm taking the correct approach. I've been having a look at this: 

http://iangilman.com/osd/test/demo/m2/

Awesome work! I'm thinking it would be smarter for me to align my code with this. 

It looks like you're loading all of the tilesources in one go and setting `viewer.tileSources = tileSources` rather than calling `viewer.open` for the first tileSource and then appending each subsequent tileSource and positioning it (like me).

I'm thinking that I could perhaps use something like $.when to load each tileSource json and create a similar array to harvard-tilesources.js.

Once the tileSources are **all** opened, I can then loop through them setting their world positions.

This may also remedy the stacking issue: https://github.com/openseadragon/openseadragon/issues/629

Stepping through the code in the debugger I can't see what's triggering the open event handler though.

**Comment by iangilman** [comment]
Thanks! Glad you like the demo. :-)

Yes, if you have a whole bunch of tile sources, I think getting them altogether ahead of time is a worthwhile optimization. We certainly needed it with that demo, where there are approximately 500. 

Once you have all the tile sources together, it doesn't really matter whether you include them when creating the viewer like I do in that demo:

https://github.com/openseadragon/openseadragon/blob/master/test/demo/m2/js/main.js#L36

… or if you pass them into `open` later; either way they'll happen altogether. The key is giving the actual tile source data rather than a URL where OpenSeadragon has to go fetch the data before it can do anything.

The open event handler gets triggered after you call open when the last tile source has been successfully turned into a tiled image and added to the world.

**Comment by edsilv** [comment]
Ok, I've got the $.when loader working. The tilesources are now being opened as per your demo.

The problem now is positioning. If I do this for the right-hand-side page on open nothing happens:

    this.provider.pages[1].x = 1

(this.provider.pages is just an array of objects with a tileSource property that contains the json-ld, like your harvard-tilesources.js).

However, if I do the same thing _prior_ to opening the tilesources, the right-hand-side page appears in the correct position.

The problem with that approach is that I'm working with top-to-bottom archives as well, and some of the items in the manifests are wide and short, meaning if I do this for the bottom page:

    this.provider.pages[1].y = 1

there is a big space between them. What I need is to be able to get the exact normalised width and height of the first page _before being opened_.

Alternatively, is there something I'm missing that will allow me to position the second page on open?

I've tried this:

    this.provider.pages[1].y = this.viewer.world.getItemAt(0).normHeight

and this:

    this.viewer.world.getItemAt(1).y = this.viewer.world.getItemAt(0).normHeight

but to no avail...

**Comment by iangilman** [comment]
In the case of harvard-tilesources the data itself already has the width and height (in pixels) so it's easy to calculate ahead of time the shape of every page. Do you have that data in your provider.pages? If so, a little math will do it. I'm happy to help you with that if you want.

Otherwise, if the sizes aren't known ahead of time, then yes, you'll need to rearrange everybody once you get the `open` event. At that point there's no use to modifying your provider.pages because that data has already been used. The only option is to talk to the TiledImage directly, like so: 

```
var tiledImage0 = this.viewer.world.getItemAt(0);
var box0 = tiledImage0.getBounds(true);
var bottom0 = box0.y + box0.height;
var tiledImage1 = this.viewer.world.getItemAt(1);
var pos1 = tiledImage1.getBounds(true).getTopLeft();
pos1.y = bottom0;
tiledImage.setPosition(pos1, true);
```

All those `true` flags are to suppress the animation. 

Anyway, it's necessary to go through those functions rather than accessing the properties directly, because there is internal state to manage.

**Comment by edsilv** [comment]
I've opted to go with your on open example. Seems to be working nicely. Many thanks!

This is the $.when loader if you're interested:

https://github.com/UniversalViewer/universalviewer/blob/master/src/extensions/uv-seadragon-extension/provider.ts#L213

https://github.com/UniversalViewer/universalviewer/blob/master/src/extensions/uv-seadragon-extension/Page.ts

**Comment by iangilman** [comment]
Excellent :)
