### ISSUE TITLE
The image seems no so clear in openseadragon as its origin

### ISSUE THREAD

**Issue by songofhawk** [openseadragon/openseadragon#646]
I use openseadragon show arts in my web site, but they seem not so clear as its origin. Here's the snapshot:

![openseadragon](https://cloud.githubusercontent.com/assets/2861016/7242504/9cb9811e-e7f5-11e4-98aa-4b04cb63a571.png)

The left one is original, the right one is rendered by openseadragon, obviously the left one is sharper, and the right one is blurred.

I was thought that it caused by Deep Zoom Composer, which decreased quality when creating DZI image parts, but i was wrong. here the snapshot:

![dzi](https://cloud.githubusercontent.com/assets/2861016/7242512/ae3e2a5c-e7f5-11e4-83e6-40574d535fb6.jpg)

The left one is a part in DZI directory, the right one is orgin, they seem exactly same, and all of them are readered by a browser(IE 10).

Now the reasonable explaination  is the randering type of openseadragon cause the difference, is this a bug? or is there an option / argument which can improve rendering effect in openseadragon?

**Comment by iangilman** [comment]
Two possible issues here. Are you on an HDPI (i.e. "retina") screen? If so, there is a bug fix in master that's not on the latest release yet. 

Otherwise, it's probably the minPixelRatio. By default OpenSeadragon allows the image to not be entirely full resolution at some zoom levels, to save on bandwidth. You can modify this value by passing `minPixelRatio: 1` as one of the options when you create your viewer (the default value is 0.5).

**Comment by natelawrence** [comment]
I don't suppose this could be caused by the web browser's magnification settings being set to something larger than 100%?

SongofHawk, could you reset your IE zoom level by pressing [Ctrl]+[0] and see if anything changes?
