### ISSUE TITLE
Improve docs: addOverlay placement argument misunderstanding

### ISSUE THREAD

**Issue by crswll** [openseadragon/openseadragon#650]
The placement argument does not appear to be used in `viewer.addOverlay()`. I expect this parameter to set what corner/side the overlay should position itself from the coordinates. This example should give a clear demonstration of how I expect it should behave. 

http://crswll.github.io/sd/ ( code at https://github.com/crswll/sd for an easy clone ).

If I'm misunderstanding this I'm curious as to its actual use?

**Comment by avandecreme** [comment]
I don't remember the reason but the placement only works with locations of type Point: https://github.com/openseadragon/openseadragon/blob/master/src/overlay.js#L127

You will need to compute yourself the actual location or submit a patch to support that behavior :)

**Comment by crswll** [comment]
Hm, wonder why.

I was able to do it in the draw callback in `addOverlay`. I have no idea how to approach patching that but I'll wait to see if anyone chimes in with a reason before I even attempt it.

In case anyone needs it in the future: http://crswll.github.io/sd/

PS: Would it be possible to keep an overlay a static size?

**Comment by avandecreme** [comment]
If you want to use a static size, you should use a point instead of a rectangle for the location.

I actually now remember why the placement is only used with point. The placement corresponds to how the overlay is positioned compared to this point (not to the viewer).
So if you set TOP_LEFT, the top left corner of your overlay will be at the specified location.
With BOTTOM_RIGHT, it will be the bottom right corner at the specified location.
Such property doesn't make sense with the Rect positioning.

We definitely need to improve the documentation on this.

**Comment by crswll** [comment]
Yeah. I get lost very quick in the documentation. I'd love to see some more examples (and would be willing to help out on that for sure). Thanks for the tip using point. The more i messed around with it the more I realized a static size wouldn't help much.

Thanks again for your help!

**Comment by iangilman** [comment]
Reopening this as a documentation issue.
