### ISSUE TITLE
Possible overlays location issue

### ISSUE THREAD

**Issue by speed-of-light** [openseadragon/openseadragon#689]
We have this code snippet but:

```
  var bd = viewer.viewport.getBounds()

    viewer.addOverlay(
      element: element,
      location: new OpenSeadragon.Rect(p.x, p.y * bd.height, p.w, p.h * bd.height)
      checkResize: true
    )

```

The overlays methods is reference to the runtime overlays from the examples.
The question here is why we need to multiply the `bd.height` factor for `p.y` and `p.h` part?
I mean we have correct `x, y, w, h` values, but why we only needs to adjust the height related variable?

Thanks.

**Comment by avandecreme** [comment]
You shouldn't need to adjust anything.
How did you get the x, y, w and h values? Are they in viewport coordinates?

**Comment by iangilman** [comment]
@speed-of-light where are you getting this code from? I don't see `bd.height` on http://openseadragon.github.io/examples/ui-overlays/

**Comment by speed-of-light** [comment]
@avandecreme because the image is owned by myself, so I know the target position/size. I mean `p` is an object from database.

@iangilman from the first line, called from `viewport.getBounds()` after I create the `viewer` instance.

```
var bd = viewer.viewport.getBounds()
```

**Comment by avandecreme** [comment]
Is `p` in viewport coordinates or image coordinates?
If in image coordinates, you will need to convert it first with `viewer.viewport.imageToViewportCoordinates`

**Comment by speed-of-light** [comment]
@avandecreme nice hints :+1: , `p` is image coordinates. Because both `y, h` are affected, I'll try to use `imageToViewportRectangle` and let you know the results.

**Comment by speed-of-light** [comment]
@avandecreme the results is still not as expected. 

Here I make a draft to make sure you get my idea. For example, we want get the overlay covers the `cyan` block like below:
![image](https://cloud.githubusercontent.com/assets/2149541/8931404/f05d8682-352d-11e5-9468-bee76eab630d.png)

But without the manual correction, the result will mostly look like the `yellow semi-transparent block` below:
![image](https://cloud.githubusercontent.com/assets/2149541/8931521/d4b3695a-352e-11e5-952d-f8807936b277.png)

`imageToViewportRectangle` returned object seems to have some relations of the raw `x, y, w, h`, but I'll take more time to dig it out.

**Comment by avandecreme** [comment]
Are you displaying multiple images?
In that case you would need to use `tiledImage.imageToViewportRectangle`.
You can retrieve the tiledImage with `viewer.world.getItemAt`.

**Comment by speed-of-light** [comment]
cool! I am not sure if this counts as `multiple images`, we load one `dzi` image at a time, and may switch them from create new `OpenSeadragon` object.

I'll check to use `viewer.world.getItemAt` when possible, thanks!

**Comment by avandecreme** [comment]
Ha in that case that shouldn't be the issue.
Can you share an example reproducing the bug?

**Comment by speed-of-light** [comment]
sorry, it might took me more than a whole day. We got many hooks(open, window resize, zoom, pan ...) to calling functions from the `viewer` and `viewport` to reset, zoom, panBy ...etc, I am not sure if I removed all of them the issue will still exists or not.

We'll keep track on this issue and let you know if we have any progres, thank you.

**Comment by mertyildiran** [comment]
@iangilman that's an important issue that should be mentioned in the documents. @speed-of-light  Yes, I can confirm that you need to multiply both `top` and `height` values with `viewer.viewport.getBounds().height` otherwise the overlay shifts to bottom depending on the image dimensions.

**Comment by iangilman** [comment]
@mertyildiran Interesting! Can you share a repro of this?

**Comment by mertyildiran** [comment]
@iangilman unfortunately we are using OpenSeadragon in a closed-source project hence it's impossible for me to share the repository. But I can share the code block related to overlay drawing:

```javascript
// Get the bounds of the visible area in viewport coordinates
var bd = viewer.viewport.getBounds();

// Calculate the ratios for the face overlay
var left    =   face.face_location.left / res.results.width;
var top     =   face.face_location.top / res.results.height * bd.height;

var width   =   face.face_location.right / res.results.width - left;
var height  =   face.face_location.bottom / res.results.height * bd.height - top;

// Draw the face overlay
viewer.addOverlay({
  element: elt,
  location: new OpenSeadragon.Rect(left, top, width, height)
});
```

I'm pretty sure that the coordinates that comes from `face.face_location` are correct.

**Comment by iangilman** [comment]
Cool. So you're converting from image coordinates to viewport coordinates, looks like? `res.results.width` is the actual width of the image and `face.face_location` is in image coordinates? And you haven't done anything to change your viewport coordinates, so 0 is the left side of the image and 1 is the right side of the image? If so, I believe you just need to divide all of your coordinates by the image width, like so:

```
var left    =   face.face_location.left / res.results.width;
var top     =   face.face_location.top / res.results.width;

var width   =   face.face_location.right / res.results.width - left;
var height  =   face.face_location.bottom / res.results.width - top;
```

**Comment by mertyildiran** [comment]
@iangilman why would I divide `y` values by `res.results.width` it does not make sense. To my knowledge we did not mess with any configuration related to `viewport`.

**Comment by iangilman** [comment]
To convert from one coordinate system to another you need to divide both axes by a common value; if you divide your x value by 5 and your y value by 2, the result will be distorted. In the case of the default viewport coordinates, the single common value we choose to divide the image coordinates (both x and y) is the width of the image. For more on viewport coordinates, check out: 

http://openseadragon.github.io/examples/viewport-coordinates/

... especially:

> By default, a single image will be placed with its left side at viewport x = 0 and its right side at viewport x = 1. The default top is at at viewport y = 0 and its bottom is wherever is appropriate for the image's aspect ratio. For instance, the bottom of a square image would be at y = 1, but the bottom of an image that's twice as wide as it is tall would be at y = 0.5.

Does that make sense now?

**Comment by mertyildiran** [comment]
@iangilman I'm sorry but still I'm unable grasp how is that the correct behaviour. I have created a simple drawing the explain what are the values correspond to:

![](https://i.ibb.co/qWPJNwJ/Open-Seadragon-Issue.jpg)

Because there might be a misunderstanding...

**Comment by iangilman** [comment]
No worries... we'll get to the bottom of this! 

So, in your diagram, all of those values are in image coordinates, right? In other words, they are based on the actual pixels of the image? Also, I assume 0, 0  is the upper left corner of the image? 

When putting the overlays on, you need to do that in viewport coordinates, which is not the same as image coordinates, so you need to convert between the two. By default viewport coordinates also start with 0, 0 in the upper left corner of the image and go to 1 on the right side of the image (the bottom coordinate is based on the aspect ratio). Because the origins of the two coordinate systems are the same, and since we're just scaling between the two, we just need to find out what the ratio is between the two in order to convert any of the coordinates. In the case of the default, with viewport X of the right side of the image being 1, that ratio is 1 / image width. Once you have that ratio you can multiply any of the above image coordinates by it to find out the viewport coordinate version. 

Does that make sense? If not, which part doesn't make sense? 

I realize dealing with different coordinate systems can be challenging, but unfortunately it's a necessary part of any kind of zooming system.

BTW, we've been focusing on just one strategy, but there are lots of ways to handle the conversion. At the risk of confusing things more, here are a few:

* Viewport coordinates are arbitrary, so you can set them to something different just by laying your image out differently. For instance you could specify the width of your image in viewport coordinates to be the same as its width in image coordinates. There's an example of this on http://openseadragon.github.io/examples/multi-image/ but I can give more detail if you want. 
* When you specify your overlays you can specify them in image coordinates by using `px` and `py` instead of `x` and `y`. This is mentioned on http://openseadragon.github.io/examples/ui-overlays/ but probably not prominently enough.
* Instead of manually converting between coordinates by finding the ratio you can have OSD do it for you using Viewport's `imageToViewportRectangle` (unless you are using multiple image in the same viewer, in which case you need to use the TiledImage's version).
