### ISSUE TITLE
Openseadragon and overlaid elements

### ISSUE THREAD

**Issue by carbontracking** [openseadragon/openseadragon#718]
Hello,

I'm looking for an existing solution to allow the viewing book pages in JPEG format (each page a separate jpeg file) with the possibility of "drawing" on each image. The kind of items to draw are lines / boxes / arrows / text.

Are you aware of any project that has done something like this ? I came to openseadragon via annotorious, http://annotorious.github.io/demos/openseadragon-preview.html,  but I need the overlaid elements to be permanently visible (and zoomable with the original image).

The goal is to allow students with low-vision to read and write on their scanned textbooks.

Best regards,

Colm OGAIRBHITH

**Comment by iangilman** [comment]
Yes, you could add an SVG overlay with https://github.com/openseadragon/svg-overlay. You would have to handle the drawing mechanism and the storage/retrieval of the overlays. 

By the way, if you're using OpenSeadragon to display single jpg images (rather than tile pyramids), you can use the LegacyTileSource with just a single level: 

http://openseadragon.github.io/examples/tilesource-legacy/
