### ISSUE TITLE
Loading message?

### ISSUE THREAD

**Issue by humbertorodrigues** [openseadragon/openseadragon#723]
There is something from OSD to be used if I want to show a loading message do my users while the image is being loaded?

**Comment by avandecreme** [comment]
There is no built in message mechanism but you can use the tile-drawn event as described on #648 to detect when the first tile has been drawn.

**Comment by humbertorodrigues** [comment]
This event is fired even if the image is loading yet. Can I get the images URL using this event to check with JS if image is fully loaded? I couldn't find which images were loaded when "tile-drawn" is fired

**Comment by avandecreme** [comment]
>This event is fired even if the image is loading yet.

Do you want to detect when all the necessary tiles have been drawn? I think we are missing such event.
Maybe we could create a new event for that.

>Can I get the images URL using this event to check with JS if image is fully loaded? I couldn't find which images were loaded when "tile-drawn" is fired

I am not sure whether you want the URL of the tile or of the tiled image but you can get both:
```javascript
viewer.addHandler("tile-drawn", function(event) {
   var tileUrl = event.tile.url;
   
   // Supposing your tile source has an URL.
   // For example for DZI images, it would be the .dzi file
   var tileImageUrl = event.tiledImage.source.url; 
});
```

**Comment by humbertorodrigues** [comment]
Yes, that is what I need! Can you give me a tip about where can I start to develop such event? I'm not very familiar with OSD code yet, but I could try. I'm trying to identify the images loading progress manipulating the drawCanvas function. I'm not sure this is the best way to get such information

>I am not sure whether you want the URL of the tile or of the tiled image but you can get both:

My idea was to get the image URL and check is JS if this image is already loaded. I'm not sure this is possible, but was my best shot! =)

**Comment by avandecreme** [comment]
>Yes, that is what I need! Can you give me a tip about where can I start to develop such event? I'm not very familiar with OSD code yet, but I could try. I'm trying to identify the images loading progress manipulating the drawCanvas function. I'm not sure this is the best way to get such information

You probably need to raise the event when `_needsDraw` is set to false here https://github.com/openseadragon/openseadragon/blob/master/src/tiledimage.js#L132

But I am thinking we actually need 2 events:
- when a tiled image is entirely drawn
- when the world is entirely drawn
I would wait on @iangilman thought on that.

>My idea was to get the image URL and check is JS if this image is already loaded. I'm not sure this is possible, but was my best shot! =)

Could you clarify what you mean by image? Tile (which has a specific URL) or entire image (TiledImage) which doesn't necessary have a URL depending on the tile source used?

**Comment by humbertorodrigues** [comment]
>Could you clarify what you mean by image? Tile (which has a specific URL) or entire image (TiledImage) which doesn't necessary have a URL depending on the tile source used?
I mean the tile

>But I am thinking we actually need 2 events:

>*when a tiled image is entirely drawn
>*when the world is entirely drawn I would wait on @iangilman thought on that.

I will try to follow this way. I will kepp you updated. I'll be pleasured to make my first commit to this amazing project with such event.

**Comment by iangilman** [comment]
Yes, we've definitely been wanting this event! I think even starting with the one for TiledImage would be a good start. @avandecreme is correct in pointing out the key flag (_needsDraw). I'm thinking if you checked to see if it was false right after the updateViewport call here: 

https://github.com/openseadragon/openseadragon/blob/master/src/tiledimage.js#L240

...that would do it. You'd want to only fire it once, though (otherwise you'd get flooded with these events), so you need to keep track of whether you've fired it yet. 

I'm a little up in the air as to whether the new event should be fired on behalf of TiledImage (like `bounds-change`) or on behalf of the Viewer (like `tile-drawing`). I think I'm leaning toward firing it on behalf of the Viewer. This would make it easy for people who just have a single tiled image (still the most common use case) but still make it possible for us to build a version for the whole World (i.e. all tiled images have finished loading the necessary tiles for the initial view) at some point.

**Comment by malDuffin** [comment]
Has this event been completed yet, or is it available for testing?  I'm more than happy to try it out.

Having an event fired when the current image with a drawer has fully completed loading would be excellent for my current task, in order to ensure that when I capture a snapshot of the canvas image, it's correct and complete.

**Comment by iangilman** [comment]
@malDuffin no, this still needs to be done; looks like @humbertorodrigues has perhaps moved on to other things. Would you like to take your hand at writing the patch?

**Comment by malDuffin** [comment]
Hi Ian,
I can certainly give it a go.

What would you suggest is the best way to detect when this event should be raised?  I'm assuming there is a way to detect the total number of tiles to be loaded for that current drawer ( X ), and then when X tile-drawn events are detected, the loading is complete?

**Comment by iangilman** [comment]
I think it may be as simple as adding an  `else` clause to:

https://github.com/openseadragon/openseadragon/blob/master/src/tiledimage.js#L800-L802

… and firing it then. You'd want to only fire it once, though (otherwise you'd get flooded with these events), so you need to keep track of whether you've fired it yet for that TiledImage.

**Comment by homerjam** [comment]
+1

I could really do with this event!

**Comment by iangilman** [comment]
Ok, I've made a start here: 

https://github.com/openseadragon/openseadragon/pull/837

Feedback welcome!

**Comment by iangilman** [comment]
#837 has landed, with support for this at the TiledImage level. In the future we might want to add one at the World or Viewer level that pays attention to all of the tiled images, or maybe this is good enough. At any rate, closing this issue.
