### ISSUE TITLE
Source file for the icons

### ISSUE THREAD

**Issue by hendriklammers** [openseadragon/openseadragon#747]
Is the source file (e.g. Photoshop) for the button images available somewhere? I need to design some icons for an Openseadragon plugin my collegae created, but it would be nice to keep them exactly in the same style of the original buttons.

**Comment by iangilman** [comment]
Sadly those images are something like 8 years old...if the original Photoshop file exists, it's probably on a disused machine somewhere on the Microsoft campus. 

If you do come up with an icon-free version while you're making your new buttons, it would be great if you could share it here! Also note the alternative icon pack here: 

http://openseadragon.github.io/#plugins

**Comment by hendriklammers** [comment]
The notification I got when you closed this issue acted as a reminder for me that I do have a psd and and some icon-free png's available. Shall I add them to to images folder and create a pull request?

**Comment by iangilman** [comment]
It would be great if you could share your icon set!

I'd actually prefer for you to publish them from your account as an icon pack, like this one: 

https://github.com/peterthomet/openseadragon-flat-toolbar-icons

...and then update here:

https://github.com/openseadragon/site-build/blob/master/www/index.html#L174

...to add it in.

Sound good? Hopefully we can get some good variety of icons.

**Comment by hendriklammers** [comment]
Ok, but what I'm talking about is not really an icon pack. It's just an empty version of the buttons already used in the Openseadragon viewer plus a psd file. Something to be used in case anyone might create a custom plugin and needs to add a button in the same style of the default viewer buttons.

![openseadragon-buttons](https://cloud.githubusercontent.com/assets/754556/22779000/4f5560d8-eeb9-11e6-9bd5-91d0b0cc9b39.png)

**Comment by iangilman** [comment]
Ah, I see; wonderful! Well, it might still be good to link to them from the "Plugins" section of the homepage, but I agree that it also makes sense to have them here in this repository. The blank icon png files could be useful in the "images" folder, so people can use them directly by adding their own icon on top directly in the HTML/CSS. 

The PSD would be useful for people who want to really integrate their icons for the best results. It shouldn't go in the "images" folder, though, because that folder becomes part of the distribution. I suppose it could just go in the root level of the repository here, or it can go in a new folder on the root level or something. 

Or maybe the PNGs could go in the "images" folder of this repository and the PSD could go in the "site-build" repository so it's just linked from the webpage. I'm not sure what's best, so I'm open to whatever you think... 

Anyway, thank you for putting these together!

**Comment by iangilman** [comment]
@hendriklammers Sorry if my indecision put you off... how about the PNGs go in the images folder and the PSD goes in the root and we call it good?

**Comment by hendriklammers** [comment]
Ah sorry not at all, just a bit busy at the moment.. I did manage to make the pull request though 😉

**Comment by tirendel** [comment]
Is there a way to unsubscribe from all these emails?  When I click on “mute the thread” I am asked for a github account but I don’t recall ever having one.  However, I am being inundated by these emails and I would like to avoid that.  Also, I don’t recall ever registering or accepting to receive such notifications.

Regards,

Joe Roberts
Sr Staff Product Security Leader
GE Energy Connections

T: 404-625-2347
E: joe.roberts@ge.com<mailto:joe.roberts@ge.com>

2018 Powers Ferry Rd
Atlanta GA 30339
USA

GE Imagination at work


Ah sorry not at all, just a bit busy at the moment.. I did manage to make the pull request though 😉

**Comment by iangilman** [comment]
@hendriklammers Thank you!

@tirendel (Joe) I'll e-mail you separately about unsubscribing...

**Comment by iangilman** [comment]
Fixed by #1135
