### ISSUE TITLE
page jumps when interacting with OSD

### ISSUE THREAD

**Issue by fgrs** [openseadragon/openseadragon#769]
is it possible to disable this? can be seen on example pages

**Comment by iangilman** [comment]
@fgrs I'm not sure what you're talking about. Can you describe your repro steps and what occurs, as well as what browser you're using?

**Comment by fgrs** [comment]
this is a good example https://openseadragon.github.io/ without clicking anywhere scroll down the page so you can see only a small portion of the image now click the image like you would normally do to zoom in, on chrome page jumps right to the top of the image

**Comment by iangilman** [comment]
Interesting! Looks like it's because the `openseadragon-canvas` div has a `tabindex` attribute. I believe we use this to support keyboard interaction, which is definitely a feature we want to keep. 

tabindex was added with #577, and it's settable via the `tabIndex` option when creating the viewer. It looks like if you set a tabindex to an empty string, Chrome won't pop you to it like that. Unfortunately we're currently just testing to see if the given tabIndex option is falsy, so there's no way to set an empty string. It would be an easy enough fix here, though: 

https://github.com/openseadragon/openseadragon/blob/master/src/viewer.js#L237

@fgrs Would you like to write a patch for it? 

cc @msalsbery who wrote #577 in case he has additional thoughts.
