### ISSUE TITLE
Add index.js for npm 

### ISSUE THREAD

**Issue by iangilman** [openseadragon/openseadragon#785]
As @homerjam mentioned: 

https://github.com/openseadragon/openseadragon/pull/781#discussion_r46175896

> In fact the "new" standard is to include an index.js file which requires the modules main dist file and dependencies. I believe webpack and browserify promote this way of doing things.

**Comment by leesei** [comment]
There's actually no need for `index.js` as long as we have the `main` field.
http://browsenpm.org/package.json#main
https://docs.npmjs.com/files/package.json#main

`index.js` is the default value of `require()` algorithm.
https://nodejs.org/docs/latest/api/modules.html#modules_all_together

**Comment by iangilman** [comment]
Our `main` is `"build/openseadragon/openseadragon.js"`...does that work?

**Comment by homerjam** [comment]
@iangilman yes that will work.

I think the idea behind the `index.js` approach is that it allows you to include js/css/img etc which can then be intelligently managed by your build tool. Alternatively The `main` field can be an array but support of this varies by package manager/build tool. Whilst the information in the npm docs is obviously correct its aimed at nodejs modules rather than browser modules.

All this said I'm struggling to find the resources I used to base this on!

**Comment by leesei** [comment]
Actually @homerjam's comment is a bit off as the bundlers (webpack and browserify) are adhering to the `package.json` spec and Node.js's `require()` algorithm.
They are not in anyway "promoting" `index.js`.

I think the current `package.json` is fine for the js code part, there is no standard way to handle assets (the images) other than js and css anyway.

**Comment by iangilman** [comment]
Ok, sounds like we can close this issue then. Thank you both for the insights!
