### ISSUE TITLE
Timeout issues for Deep Zoom

### ISSUE THREAD

**Issue by terenceingram** [openseadragon/openseadragon#795]
Has anyone encountered a problem where super large images being served up by Deep Zoom timeout? Can you increase the period before it times out?

I currently have IIP serving up the tiles for Deep Zoom. It works perfectly, however now that extremely large files (originally over a gb as TIFF) are now converted in JPX files it takes a while for the IIP Server to stream the tiles. 

This is our use of openseadragon: http://nla.gov.au/nla.obj-229851455
This URL just serves up a JPG image: http://nla.gov.au/nla.obj-229851455/image?WID=500

Any thoughts?

**Comment by avandecreme** [comment]
Nice website :+1: 
I don't see any timeout issue.
According to [this](http://stackoverflow.com/questions/5798707/browser-timeouts) browsers timeouts are very high compared to the server ones.
Are you that the issue is client side?

One option would be to prebuild the pyramids with one of those tools: http://openseadragon.github.io/examples/creating-zooming-images/
