### ISSUE TITLE
Deep Zoom Tile Errors on Firefox but not on Chrome

### ISSUE THREAD

**Issue by terenceingram** [openseadragon/openseadragon#822]
We have an interesting problem with "some" of our images being served using Deep Zoom. When looking at the Javascript console, errors are being thrown where some of the tiles are not being returned by the server (IIP Server). What is weird is that Chrome seems to handle or swallow these errors and still renders the image. However, Firefox and Safari can't handle these errors and consequently don't display the image at all because Openseadragon throws an error saying that the Object is no longer usable. 

For example: http://nla.gov.au/nla.obj-138483108

View it in Chrome and look at the Javascript console. HTTP 500 Errors being thrown "GET http://nla.gov.au/nla.obj-138483108/dzi?tile=9/1_1.jpg 500 (http://nailgun.nla.gov.au:24646/ImageController/DeepZoom/nla.obj-138483108?tile=9/1_1.jpg)" 

But the image is still visible.

View the same url in Firefox or Safari and the image does not display at all. You get a similar HTTP 500 error but then following error is thrown in the log:

InvalidStateError: An attempt was made to use an object that is not, or is no longer, usable - openseadragon.js (line 14775)
    context.drawImage(

We are trying to workout why the tile does not exist or why an error is thrown from the IIP Server side. However as we have almost a million images it will be impractical to fix thousands. 

So how or what can be changed so that when a tile is not found the image overall still loads. In other words make the other browsers work the same way Chrome does.

**Comment by terenceingram** [comment]
@josephcurtis

**Comment by josephcurtis** [comment]
Also, as far as I have been able to tell these tile requests that result in a 500 error are always for coordinates outside of the grid of tiles for the image.  In the above example, at zoom level 9 (as in the request) that image only has two tiles, 0x0 and 0x1, yet a request for tile 1x1 is being initiated by the viewer.

Is this expected behaviour, or is the main issue that these requests for non-existent tiles should never be made in the first place?

**Comment by iangilman** [comment]
Interesting. Seems like we're trying to draw an image that hasn't loaded, but if the image doesn't load, it should know better than to try to draw it. The full statement that's causing the exception is: 

```
        context.drawImage(
            rendered.canvas,
            0,
            0,
            rendered.canvas.width,
            rendered.canvas.height,
            position.x * $.pixelDensityRatio,
            position.y * $.pixelDensityRatio,
            size.x * $.pixelDensityRatio,
            size.y * $.pixelDensityRatio
        );
```

The "unusable object" from the error could be either `context` or `rendered`; I think it's `rendered`, since `context` is the main canvas for the Drawer. 

Typically if we get a 400 we do a fine job of not trying to use the image...I wonder if there's something about the 500 that's putting it in some sort of partial state. It would be great to get to the bottom of. Of course the quick hack is just to wrap that statement in a `try` block. 

As for the original cause of the 500s, it looks like you are indeed missing tiles you should have. A DZI with the specs of yours: 

```
<Image xmlns="http://schemas.microsoft.com/deepzoom/2008" TileSize="256" Overlap="0" Format="jpg">
<Size Width="4097" Height="5681"></Size>
</Image>
```

...should have a `9/1_1.jpg` (it should be 1 pixel wide and 100 pixels tall). Obviously that one pixel strip doesn't contribute much to the overall look of the image, but it's necessary for completeness. Is there any way you can fix your server to produce the required tile?

**Comment by josephcurtis** [comment]
It turns out that this bug was caused by a minor modification we made to the library.  The unadulterated version works fine.

**Comment by iangilman** [comment]
Good to hear...thanks for letting us know!
