### ISSUE TITLE
Can't reach the top and bottom of wide slide after rotation (in landscape mode)

### ISSUE THREAD

**Issue by itsmepetrov** [openseadragon/openseadragon#833]
Hi guys! Thanks a lot for this awesome library.

I got version from master branch and I found a problem with scrolling to top and bottom after rotate slide.
But if I used latest version (2.1.0) from npm - everything is ok.

For example:

* Master branch: [jsfiddle](https://jsfiddle.net/itsmepetrov/0dLzwj9r/3/), [video](https://monosnap.com/file/BWciCwNfOK4CPF1XaQjpuq1AAcYUHt)
* 2.1.0 version: [jsfiddle](https://jsfiddle.net/itsmepetrov/0dLzwj9r/4/), [video](https://monosnap.com/file/8QW6DoFWH5Wtj65BhIVjvrHK0DBblG)

**Comment by avandecreme** [comment]
Thanks for reporting this. It looks like I missed something in this patch: https://github.com/openseadragon/openseadragon/commit/1d04ceadffc7213634e513f9fe4a4cf2dbc20547

**Comment by AlexSmelov** [comment]
Faced with the same issue, could you fix it please?

**Comment by r3nya** [comment]
+1

**Comment by iangilman** [comment]
@avandecreme Are you planning on looking into this, or should we see if one of the other fine folks on this thread would like to take a whack at it?

**Comment by avandecreme** [comment]
I had a quick look a while ago.
From what I remember, the issue is around `viewport._applyBoundaryConstraints` and some mix up with `this.bounds` and `newBounds` which sometimes account for rotation and sometimes not.
I will try to look at it again but if anyone want to look into it, please go ahead (just let me know here).
