### ISSUE TITLE
How to do multiple animation in sequence?

### ISSUE THREAD

**Issue by SpecialM2580** [openseadragon/openseadragon#834]
Hi,
I'm a newbee^-^. I want to do span and then zoom(after spanning).My thought is:
```
viewer.viewport.panTo();
viewer.addHandler("animation-finish",function(event){
    viewer.viewport.zoomTo();
});
viewer.viewport.applyConstraints();
```
but I already have a global handler on "animation-finish" event,and I really should't remove it(by using removeHandler())...
Can it be one time thing rather than a handler for all times?
Am i missing something  in API docs?

**Comment by avandecreme** [comment]
To have a handler called just once, you can do:

```javascript
viewer.addHandler("animation-finish", function animationFinishHandler(event){
    viewer.removeHandler("animation-finish", animationFinishHandler);
    viewer.viewport.zoomTo();
});
```

@iangilman What do you think about adding a `addOneTimeHandler` to the `EventSource` class?
Ha, just noticed we actually have a comment about it: https://github.com/openseadragon/openseadragon/blob/master/src/eventsource.js#L59

**Comment by iangilman** [comment]
Yeah, seems like a reasonable addition. 

@SpecialM2580 Another option would be to use a timeout. The default animation time is 1.2 seconds, so you could do: 

```
setTimeout(function() {
  viewer.viewport.zoomTo();
}, 1200);
```

**Comment by SpecialM2580** [comment]
Nice, the timeout thing works without removing the handler. Actually my Initial idea was to pan and zoom to a certain point at the same time,  like 'focus' on a point:
```
var point=new OpenSeadragon.Point(x,y);
viewer.viewport.zoomTo(point);
viewer.viewport.panTo(point);
```
But it seems the animation didn't act like i thought, it ended up in somewhere else. So i guess maybe i must do next animation after the last one. That's why I raise this issue. Is there any chance to do it smoothly without waiting for the last animation finish? pan and zoom at the same time?

**Comment by dwrogers** [comment]
Pazoom? ☺

--
David W. Rogers
Software Developer / Collaborative Data Services / 206.667.7089 / drogers@fredhutch.org / Fred Hutch / Cures Start Here

**Comment by SpecialM2580** [comment]
Perhaps my request is too specific to my situation...(｡・`ω´･) if it is, just ignore me...‘Pazoom’ is a nice touch LOL

**Comment by dwrogers** [comment]
It would definitely be a sexy feature! It would give you a cool visual when you pazoomed to some region of interest (ROI) In my application of marking up whole slide images, it would be great for this. Rather than just bounce to an ROI, the image would pazoom to it, leaving the observer with a clear idea of the context of the resulting image within the original.

David
--
David W. Rogers
Software Developer / Collaborative Data Services / 206.667.7089 / drogers@fredhutch.org / Fred Hutch / Cures Start Here

**Comment by sdellis** [comment]
aka, "The Ken Burns Effect" 

:+1:

**Comment by avandecreme** [comment]
> Nice, the timeout thing works without removing the handler. Actually my Initial idea was to pan and zoom to a certain point at the same time, like 'focus' on a point:
> ```javascript
> var point=new OpenSeadragon.Point(x,y);
> viewer.viewport.zoomTo(point);
> viewer.viewport.panTo(point);
> ```
> But it seems the animation didn't act like i thought, it ended up in somewhere else. So i guess maybe i must do next animation after the last one. That's why I raise this issue. Is there any chance to do it smoothly without waiting for the last animation finish? pan and zoom at the same time?

This is actually supported. However, the [doc for zoomTo](http://openseadragon.github.io/docs/OpenSeadragon.Viewport.html#zoomTo) is incomplete which I guess caused your confusion.
As you can see [here](http://openseadragon.github.io/docs/openseadragon.js.html#line16967), it is expecting a zoom value and a refPoint.
The zoom value is a viewport zoom. You can convert from [image zoom to viewport zoom](http://openseadragon.github.io/examples/viewport-coordinates/) if necessary.
The refPoint is where you want to zoom to so that should just be the point you were using.

**Comment by avandecreme** [comment]
> It would definitely be a sexy feature! It would give you a cool visual when you pazoomed to some region of interest (ROI) In my application of marking up whole slide images, it would be great for this. Rather than just bounce to an ROI, the image would pazoom to it, leaving the observer with a clear idea of the context of the resulting image within the original.

If you want to use a ROI instead of a point+zoom, you can use [`Viewport.fitBounds`](http://openseadragon.github.io/docs/OpenSeadragon.Viewport.html#fitBounds) (or fitBoundsWithConstraints).
It takes a rectangle in viewport coordinates. See how to convert from image to viewport coordinates [here](http://openseadragon.github.io/examples/viewport-coordinates/).

**Comment by dwrogers** [comment]
Thank you. This newbie appreciates all of the tips and tricks he can get.

--
David W. Rogers
Software Developer / Collaborative Data Services / 206.667.7089 / drogers&#64;fredhutch.org / Fred Hutch / Cures Start Here

**Comment by SpecialM2580** [comment]
@avandecreme 
Yes !
fitBoundsWithConstraints is the effect i want, thanks so much...I knew I missed something >w< sorry for wasting your time~

**Comment by iangilman** [comment]
All's well that ends well...we're happy to help! 

Closing this question. If anyone wants to file a new issue for adding `addOneTimeHandler`, go for it.
