### ISSUE TITLE
MouseTracker only works on canvas?

### ISSUE THREAD

**Issue by joris-rotteveel** [openseadragon/openseadragon#868]
Hi,

When instantiating a new MouseTracker, the constructor takes  an element. However, the events only fire when they happen on the canvas. I would like to use the Mousetracker to also detect my touches outside of the canvas as my canvas isn't 100% of the whole screen.

This [codepen]( http://codepen.io/anon/pen/eZYaNN) demonstrates the issue:

I expected the element given to the constructor to be the element where the tracker registers for events.

**Comment by iangilman** [comment]
Hmm; looks like there is something weird with key events and CodePen. I can't even get this to work: 

```
  $('#container').on('keyup', function() {
    console.log('keyup');
  });
```

...whereas in your example if you change `keyUpHandler` to `clickHandler` it works just fine when you click outside the viewer. I've also verified it with the key handler by adding this to test/demo/basic.html: 

```
var mouseTracker = new OpenSeadragon.MouseTracker({
    element: $('body')[0],
    keyUpHandler: function (e) {
        console.log('key up detected.');
    }
});
```

**Comment by joris-rotteveel** [comment]
You are right, `clickHandler` seems to work,both on my local project and codePen.

**Comment by AsmaAq** [comment]
How can I add "mouseup" and "mousedown" events on openSeadragon canvas? I tried to add listener directly to canvas using this in javascript but didn't work: 

canvas.addEventListener("mousedown", mouseDown, false);

I used the same way for "mousemove" and it worked. don't know why its different for mouseup and mousedown?

also I can't find a way to add inside MouseTracker?

Any help?

**Comment by iangilman** [comment]
@AsmaAq OpenSeadragon does extensive work with pointer events, so you're better off using either the events the viewer produces or using another MouseTracker. In the case of mousedown/mouseup, using the viewer it would be: 

```
viewer.addHandler('canvas-press', mousedownHandler);
viewer.addHandler('canvas-release', mouseupHandler);
```

**Comment by AsmaAq** [comment]
Okay Great they worked! 

What about mousemove? I used "canvas-drag" instead of "mousemove" subscription because it was not always called. or there is something better for it? 

So I ended up with these:

viewer.addHandler('canvas-drag', function(target, info){
   mouseMove();
});

  viewer.addHandler('canvas-press', function(target, info) {
         mouseDown();
  });

   viewer.addHandler('canvas-release', function(target, info) {
          mouseUp();
   });

This works like "mousedown" "mousemove" "mouseup" Sequence? 

Thanks!

**Comment by iangilman** [comment]
Yes, that should work great, as long as you only want to know about mouse movements while the button is held down. If you also want to know about mouse movements while the button is up, you'll have to create a fresh MouseTracker and use that.

**Comment by Medwar** [comment]
In the [codepen](http://codepen.io/anon/pen/eZYaNN) by joris-rotteveel above,
if we change `moveHandler` for `clickHandler` or `pinchHandler`,
we will get the console message from the custom handler only if the event is targeted outside the viewer.
Looks like the canvas "swallows" all the events that it handles, and they disappear. 
Is there an option to add a new mousetracker to the whole `<body>`, in such a way that it will be able to track pinch events even if one finger is inside the viewer and one is not?

**Comment by iangilman** [comment]
Yes, the canvas does swallow the events it handles. This is due to the complexity of handling mouse, touch, and pen events together. You can listen for those events from the viewer, though.

That said, I don't know how you would handle pinch events where one finger is in and the other is out just using OpenSeadragon's events tools… May I ask why you're trying to do that? I suppose at that point maybe you need to disable OpenSeadragon's event handling and implement your own thing.
