### ISSUE TITLE
Question - Why does Viewport.zoomTo not apply maxZoom/minZoom constraints?

### ISSUE THREAD

**Issue by adgoncal** [openseadragon/openseadragon#881]
The zoom event is raised even when already at minZoom or maxZoom. Additionally, by adding some breakpoints I see that the zoom does occur, but is followed by another zoom event that sets it back to the constrained value. Wouldn't it be better to prevent the zoom event from being raised when the zoomTo value is smaller/greater than min/max zoom?

The multiple 'zoom' events raised make it confusing to use a zoom event handler.

Suggestion: 

``` javaScript
  // $.Viewport.zoomTo

  zoomTo: function( zoom, refPoint, immediately ) {
    // check zoom constraints
    var minZoom = this.getMinZoom();
    var maxZoom = this.getMaxZoom();
    if ( zoom < minZoom || zoom > maxZoom ) {
      // zooming beyond constraints, quit early and do not raise zoom event
      return this;
    }

    this.zoomPoint = refPoint instanceof $.Point &&
      !isNaN(refPoint.x) &&
      !isNaN(refPoint.y) ?
      refPoint :
      null;

    // ...
```

**Comment by iangilman** [comment]
Yes, currently zoomTo does not apply any constraints itself... that means you can manually zoom beyond the constraints. The constraints are applied at the UI level (i.e. when you hit a button). If we change that behavior, it's possible we could break someone's app, but it's still worth considering... maybe calling zoomTo should be able to apply constraints; I'm open to thoughts on that. If we do put constraints directly into zoomTo, we'll need to also be able to disable them, since the constraints code itself may call zoomTo.

Of course for your scenario it sounds like continuing to apply the constraints at the UI level would be fine, as long as we applied them ahead of time rather than after the zoom call. That seems reasonable, but keep in mind that there are also pan constraints that could be triggered by zooming (e.g. if zooming out reveals too much empty space). Perhaps it's okay to ignore those with the preflight check and just focus on min/max zoom, though.

Also, if we do min/max zoom constraints like this, the logic should be more like: 

```
var newZoom = Math.max(this.getMinZoom(), Math.min(this.getMaxZoom(), zoom));
if (newZoom === this.zoomSpring.target.value && (!immediately || newZoom === this.zoomSpring.current.value)) {
    return this;
}
```

... so that you won't abort zooms that should at least partially happen. 

Anyway, I guess the short answer is that doing the constraints afterwards cuts down on code complexity, but I'm open to ways to improve the situation.
