### ISSUE TITLE
Navigator image

### ISSUE THREAD

**Issue by hossam707** [openseadragon/openseadragon#903]
I have only one dzi level (e.g. 17) and I want to show the image in the navigator but I know navigator will need some lower dzi level than the one I have so my question if there is some work around for this problem.

**Comment by iangilman** [comment]
Out of curiosity, why only the one level? Might be worth filling out the rest of your DZI. 

Of course the navigator is going to want a specific level... one option would be to recreate just that level. Even creating the largest level that fits on a single tile would be a good start. The navigator can make do with smaller levels than it needs, but it won't try larger levels, which is why it's not using level 17.

We don't have a mechanism to create a navigator from a different tile source than the main viewer, though presumably you could hack something like that together if you wanted to. Even then, you'd still need a single tile of your image to use, so maybe starting with a single tile smaller level for your DZI would be a good first step.

**Comment by hossam707** [comment]
Actually I have one level only or two because I am using dicom pathology files with one resolution or more which corresponds to one dzi level or more.

How can I use another tile source for navigator only if it is possible?

**Comment by iangilman** [comment]
Interesting, good to know. You could still reconstruct other levels by putting level 17 back together into a single image and scaling it as appropriate. 

Using another tile source for the navigator isn't something the navigator supports... you'd have to hack into it.  Here's a first attempt (I haven't tested this code):

```
viewer.addHandler('open', function() {
    var originalImage = viewer.world.getItemAt(0);
    var oldNavigatorImage = viewer.navigator.world.getItemAt(0);
    viewer.navigator.world.removeItem(oldNavigatorImage);
    viewer.navigator.addTiledImage({
        tileSource: ...,
        originalTiledImage: originalImage
    });
});
```

That's assuming you just have a  single image that you load at startup, and that you don't have any special positioning options.
