### ISSUE TITLE
Feature request: Mirroring / flip images.

### ISSUE THREAD

**Issue by O-Zone** [openseadragon/openseadragon#916]
Hi guys and girls.

I miss an option to mirror an image in openSeadragon.

I use an IIIF image server as image source, and in IIIF land, mirroring an image is as simple as prefixing an exclamation mark to the rotation degree. Unfortunately the openSeadragon "degrees" configuration option can't cope with that. There would also be need of a mirroring button in the control panel.

I regret that I don't have the time to implement this myself right now, but in order not to forget it, I post this feature request instead.

/O-Zone

**Comment by iangilman** [comment]
Interesting idea! It looks like flipping an image when drawing to canvas is as simple as `context.scale(-1, 1)`. Trickier (or at least more involved) would be flipping around all the tile math, as well as all the conversion routines for coordinates. Also, I suppose we'd need to think about whether we flip just individual images or the entire viewport, and what anchor point do we flip things around. 

@avandecreme has done a lot with the rotation code... any thoughts about the implications of mirroring?

**Comment by avandecreme** [comment]
I can't think of any issue involving mirroring and rotation.
I can think of one with clipping however. Should just the clipped region be mirrored? If so, in place or relative to the entire image?

If flipping per image, the easiest implementation would be to just draw normally in the sketchCanvas and then draw the sketch canvas in the main canvas with mirroring.

**Comment by iangilman** [comment]
> I can't think of any issue involving mirroring and rotation.

Cool. I guess I was thinking of mirroring as being similar to rotation, so maybe there are issues you ran into with rotation that we'll also have to deal with in mirroring.

> I can think of one with clipping however. Should just the clipped region be mirrored? If so, in place or relative to the entire image? 

I suppose this would only be a question if we mirrored the image rather than the whole world. That said, mirroring the image is probably what we want.

I think in general I want clipping to not change the geometry of the image... it should just be a visual difference. So no, the whole image should be mirrored and then it should be clipped after that. Of course, if you can specify the point around which the image is mirrored, you can take the clipping into account if you want to. 

> ~~If flipping per image, the easiest implementation would be to just draw normally in the sketchCanvas and then draw the sketch canvas in the main canvas with mirroring.~~
> Hum, actually not. Only works if the image is entirely visible.

I went through that exact thought process!

**Comment by Ivan-Feofanov** [comment]
I need mirror/flip instrument too.

**Comment by regisrob** [comment]
+1

**Comment by ernoaapa** [comment]
We would need this also. We could contribute to the project, but not really familiar with the library internally so some guidance and ideas would come handy. 

Quickly prototyped and flipping the image is the easy part but navigation is more tricky. Managed to get zoom-in with scroll to work (so that it doesn't zoom to opposite direction) by adding logic `height - point.y` here and there, but I bet there might be some easier way.

**Comment by iangilman** [comment]
@ernoaapa Great!

Sounds like you're working on flipping the entire world, not individual images, is that correct? I assume that's what your use case requires? Have you thought about the pros and cons of each approach?

We're happy to help with guidance... if you want you could start a "work in progress" pull request so we can be looking at the same code. Anyway, do you have specific questions? For more general guidance, perhaps @avandecreme could weigh in with lessons learned from his recent rotation patch (#1006).

**Comment by ernoaapa** [comment]
I'm sorry actually I realised that I don't need flipping, rotating is enough. Would be nice to have flipping support though, but maybe later when more familiar with openseadragon.

**Comment by aeschylus** [comment]
We have a similar usecase here: https://github.com/ProjectMirador/mirador/pull/1296

We don't actually need openseadragon to flip anything, but we are using CSS to invert the element and need a way to intercept mouse events so they map correctly to the flipped version. Perhaps clipping one of OSD's generated container elements might also fix it. Any ideas for either catching events to re-write them for osd before they're interpreted, or for inverting a specific target element, for instance?

**Comment by iangilman** [comment]
@aeschylus Neat! 

We don't really have a mechanism for this exactly, but looks like it's fairly easy to monkey patch:

```
var originalDragHandler = viewer.innerTracker.dragHandler;
viewer.innerTracker.dragHandler = OpenSeadragon.delegate(viewer, function(event) {
    event.delta.x = -event.delta.x;
    originalDragHandler(event);
});
```

See here for other handlers you might want to patch:

https://github.com/openseadragon/openseadragon/blob/master/src/viewer.js#L276-L289

**Comment by aeschylus** [comment]
Thanks @iangilman. We'll give this a try.

**Comment by nelsonn3c** [comment]
I made a fork from the master and the Mirror feature is already done. There are only a few code cleaning to do. =) Later I will submit a merge request.

**Comment by nelsonn3c** [comment]
Code cleaning done and already available ;)

**Comment by iangilman** [comment]
@nelsonn3c Wow, this is great! It's a major new feature :)

Looks like you went for flipping the entire world rather than flipping individual images. Did you give some thought to the pros and cons of each? Can you tell us about how you ended up going the way you did? 

How about the other folks on this thread? Any new thoughts on flipping world versus flipping individual images?

I think my bias is toward flipping individual images, as that gives the most flexibility. It's probably more complicated to implement, and creates a more complicated API, though.

In the case of rotation, we've ended up with both being possible... Maybe that's where we should head with flipping as well?

**Comment by nelsonn3c** [comment]
I made a briefly study on both approaches and chose the "easiest" way.
The individual tile flipping seems to demand some processing costs to invert each image and stick all together back in the right place. The input controls should also be inverted which I think, would lead to the same outcome. Using styling properties, makes it instantaneously and virtually costless.

**Comment by iangilman** [comment]
Okay, sounds reasonable. Let's continue the conversation over in #1441... Anyone else from this thread who wants to weigh in can come over there.

**Comment by nelsonn3c** [comment]
shouldn't this issue be already closed?
#1441

**Comment by iangilman** [comment]
Indeed, good catch!
