### ISSUE TITLE
Image tile redundant downloading

### ISSUE THREAD

**Issue by Kampii** [openseadragon/openseadragon#917]
I just recently noticed that when I drag my deep zoom image around for a while, and then go back to the same area I was before (without changing the zoom level), I notice that the tiles in that area are blurry and they get downloaded again. Is there some kind of setting that I am missing? And it is not tied to a particular area of the image.

My thinking was that if I drag the image around at a certain zoom level so that all the tiles get shown, then these tiles should not get blurry and get downloaded again.

**Comment by avandecreme** [comment]
There is a maxImageCacheCount (default is 200) parameter that you can try to increase.
It will of course consume more memory.

That might not be enough because if you noticed that the image get downloaded again that means that the browser removed it from it own (file system) cache. That would mean that already a lot of data is stored in cache.

**Comment by Kampii** [comment]
I will play with this setting, thanks! I assumed that the tiles get downloaded again as when I drag to the area I visited before the first thing I see is sort of bury/pixelated area which then becomes clear and readable.

The original image (when not sliced) it self is around 7 pixels, does that strike as too much data for the browser?

**Comment by iangilman** [comment]
Seven pixels is a pretty small image! Do you mean gigapixels? :)

**Comment by Kampii** [comment]
Please pardon my spelling.

All the tiles for this image weight up to 7.7MB. In [this link](https://www.dropbox.com/sh/fhniivvlvw4vbum/AAA_6pPBIfJValwI55F2YSO4a?dl=0) you can see all the 14 folders with tiles for this single image.

To better illustrate the issue I have created [this (click here) video](https://youtu.be/w76ewaV1_90) where you can see that tiles have become blurry when I drag to the area I was in moments ago. Do you have any idea of what is causing this?

**Comment by iangilman** [comment]
I expect those tiles will be a lot bigger in memory, but even so, I don't see why they should be getting flushed. 

Can you get the same thing to happen in the viewer on http://openseadragon.github.io? Have you tried in multiple browsers? Do you have a link to the actual page you can share? What options are you using when you create the viewer?

**Comment by Kampii** [comment]
It is a very basic viewer. Please see the [page here](http://www.c-ev.com/osdragon/redundantdownloadtest.html). I tested this on Chrome, Safari and Firefox - all of them have the same problem.

**Comment by iangilman** [comment]
Thanks for the link! I get the same behavior on that page. I think it probably is just the maxImageCacheCount. Just opening that page on my browser downloads 122 tiles. Zooming into it loads another 40, getting me close to the default 200. 

Can you easily rebuild the image? It seems to me like probably the best fix would be to make your tiles bigger (so there are fewer of them). In the past, we've defaulted to 254px tiles, but with modern screens and bandwidth, we can easily do bigger than that. Also, since your image is black and white, it compresses very well. I'd try 510 or even 1022.

**Comment by Kampii** [comment]
"Rebuild the image" - meaning slice into larger tiles? Yes - I'll try that. I will also play with the maxImageCacheCount and see what happens.

**Comment by Kampii** [comment]
How did you check that by opening the page alone downloads 122 tiles? When I look at the Net tab in my Firefox Firebug I see total of 48 requests including the images.

**Comment by iangilman** [comment]
Yes, I used the Net tab. I'm on a large HDPI screen, so it's probably loading more tiles because of that.

And yes, I meant slice into larger tiles :)

**Comment by Kampii** [comment]
I did not go through the whole process of changing the tile size, but I did change the maxImageCacheCount to 2000 which did the trick. Thanks!
