### ISSUE TITLE
[Q] 360 panorama examples

### ISSUE THREAD

**Issue by peterlitvak** [openseadragon/openseadragon#936]
Are there any good examples of 360 panoramas with OpenSeadragon?
I know there is a bug #555 that affects that functionality so I was wondering if anyone is using OSD for 360 panoramas regardless of it, maybe with some workarounds?

**Comment by avandecreme** [comment]
As mentionned in #555, there are some here (check the 360 annotated ones) http://alexbartl.de/alex/panorama.html
There is also http://www.in2white.com/

There might be other in http://openseadragon.github.io/examples/in-the-wild/ that I don't remember.

For a workaround, you could try to generate a pyramid which have all tiles of the same size (including the last tile of each row). That would mean your would choose a tile with so that it is a divisor of your whole image width.

**Comment by peterlitvak** [comment]
thank you
