### ISSUE TITLE
Can OSD be used for viewing PDF?

### ISSUE THREAD

**Issue by SandeepThomas** [openseadragon/openseadragon#955]
If yes, can someone please provide the basic config for base64 encoded pdf.

If not, is there any alternative solution for viewing base64 pdf with zoom/tilt support?

Thanks a lot.

**Comment by iangilman** [comment]
As far as I know PDF is still not supported directly by browsers; you can't just add a PDF as part of a webpage. For that reason, OpenSeadragon does not support directly viewing PDF. 

One option is to convert your PDF to one of the formats OpenSeadragon does support, such as DZI. You can get the full benefit of high resolution and zooming. Unfortunately you would lose the ability to select and search text within (unless you also added a text overlay, but that would be a bit of work).

It would be cool if we could support PDF, so I'd love to hear ideas on how to do so!

**Comment by eriksjolund** [comment]
Maybe the PDF document could converted with
[PDF.js](https://mozilla.github.io/pdf.js/) to a single-file file format ( https://github.com/openseadragon/openseadragon/issues/944 ).
The file format conversion would probably take long time, but when that step has completed the viewing would be very fast and have low memory consumption.

An interesting question is if it is possible to keep the memory consumption low during the file format conversion step. I have never used PDF.js so I don't know how much memory it requires but it would be nice if the PDF.js-rendered image tiles would be written one by one to the output file in a streaming fashion.

Instead of converting the whole PDF to single-file file format another idea is 
to have PDF.js render only what is needed. When the zooming or panning changes so that OpenSeadragon needs a new image tile, PDF.js would render the new image tile on the fly. For such a solution having the non-URL interface ( 
https://github.com/openseadragon/openseadragon/issues/1038 )
in place would be nice.

**Comment by avandecreme** [comment]
Interesting, does PDF.js support rendering only part of the PDF at a given resolution?

**Comment by eriksjolund** [comment]
I would guess so. If I zoom in quickly in their online demo
https://mozilla.github.io/pdf.js/web/viewer.html
it takes about 5-10 seconds before the text get rid of the blurriness. 
I haven't checked their API yet, though.

I noticed that the pre-rendering idea is not new.
In 2013 Benjamin Gudehus sent an email with the subject
"Serialize data of pdf pages to improve load speed"
to  the dev-pdf-js@lists.mozilla.org mailing list: 
https://groups.google.com/d/msg/mozilla.dev.pdf-js/JzTDWGt1tmA/NZGlbmMp4ysJ
