### ISSUE TITLE
[Question]   How to control the loading order of multiple images in openseadragon

### ISSUE THREAD

**Issue by osk386** [openseadragon/openseadragon#971]
In my situation, I have 10 images **previous** loaded in a viewer all these with the same bounds in the **same position**. Each image is arranged one behind other.

```
// source is an array of url images.

for(i=0;i < source.length-1;i++){
        this.viewer.addTiledImage({
                tileSource: source[i],
                index: i,
                opacity:0
            });
}
```

My intention is to control opacity of each image using a slider (range input), the slider set the correspondent image opacity to 1, and let the others with no opacity. This works well.

The idea is preload images and change images smoothly.

The problem

All **tiles** are downloaded at same order when zooming or panning,  I want to control the download tile order and give priority to the selected image tiles by the slider which should be the first to load.

How can I do that? I can't find any method to pause the loading of tiles.

Thanks for your help.

**Edited in bold**

**Comment by iangilman** [comment]
No loading happens for images with 0 opacity, but loading does happen as soon as the opacity is greater than zero, even slightly. You can control the loading in that way.

**Comment by osk386** [comment]
In this example I show how this looks, when I use a client on local intranet. (Just look the left side.)

https://www.youtube.com/watch?v=G93dYjYAYsE

This works well, on intranet

But outside from internet, when I go fast from the 0 image to the last, is notorious that it tries to load all the images, visible and invisible,  so is slower to see the current image.

I want to give priority to download tiles of current image selected. (download first all tiles needed, from desired image )

**Comment by osk386** [comment]
Thanks a lot for your answer iangilman, I think is a good way to solve this.

**Comment by iangilman** [comment]
Excellent. By the way, when flipping quickly through a bunch of images, even if you manage the opacity as you go, you may find that so many tiles are being requested that it takes a while to settle on the image that you eventually land on. This is because it's waiting for all of the intermediary tiles to be loaded first. One way to deal with that is set the `imageLoaderLimit` in your options... by limiting it to something like 4 it'll only load 4 images before reevaluating the load order. Anyway, something to experiment with.
