### ISSUE TITLE
Include dist folder for npm installation

### ISSUE THREAD

**Issue by edsilv** [openseadragon/openseadragon#976]
I tried adding osd as an npm package using the github URI: 

    "openseadragon": "git://github.com/openseadragon/openseadragon.git",

However, there is no `/dist` folder containing the build. Are there any plans to include this?

On npmjs.com the latest version is 2.2.0 not 2.2.1. I prefer to bypass the npm registry whenever possible though.

**Comment by iangilman** [comment]
Thanks for the reminder to publish 2.2.1 on npm!

If you want a built dist, you should get that from the site-build repository:

https://github.com/openseadragon/site-build/tree/master/built-openseadragon/openseadragon

...as that's the official checked in location for the latest release.

**Comment by iangilman** [comment]
2.2.1 is now published on npm as well.

**Comment by edsilv** [comment]
Great, many thanks!

**Comment by dlong500** [comment]
The only problem with the site-build repo is that it is just a static copy of the latest official release.  It would be really nice to be able to fork the main openseadragon repo, make changes, and then install from that github fork via npm/yarn and have things *just work*.  Maybe it could be accomplished by using npm's new `prepare` directive(which also is supported now in yarn)?  The `prepare` directive replaces the `prepublish` directive, and supposedly is compatible with installs via github.  I'll take a stab at testing it out and see if I can get something working.

**Comment by dlong500** [comment]
@iangilman Should I create a new issue for this?

I believe I actually got this to work with minimal modification.  If the `prepublish` directive is replaced with `prepare`, and git-describe is removed from the grunt build tasks (because the resultant folder when installed is not a git repository) then the grunt build process successfully runs *after* the files are fetched through a git source in npm/yarn.

What is great about this (assuming I have correct info) is that the `prepare` directive should perform what `prepublish` was doing when a developer publishes to the npm registry, so if the git-describe task could have a simply check before running to make sure the folder is actually a git repo then it should work as it already does now for npm publishing but also will work for someone who simply:
1) Forks openseadragon to username/openseadragon
2) Installs the forked version with `npm install git://github.com/username/openseadragon.git#master` or `yarn add git://github.com/username/openseadragon.git#master`

This would make it much easier to test changes/branches and such especially for those of us that use bundlers like webpack as the latest code will automatically get pulled in and we won't have to maintain and manually update static files.

**Comment by iangilman** [comment]
@dlong500 Sounds good to me! Would you be up for making a patch to do this? 

My concern with adding a `dist` was that I don't want a built copy to reside in this repository (which would be error prone and noisy), but setting it up so it'll build after fetch is a great solution. 

We'd probably want to update the documentation somewhere to illustrate this use case. Maybe in the download section on the home page?

**Comment by dlong500** [comment]
See PR #1258
