### ISSUE TITLE
How to use OpenSeadragon with Angular-pan-zoom

### ISSUE THREAD

**Issue by AliceBump** [openseadragon/openseadragon#982]
Hi guys, I need to use these two libraries together.
Basically I need to use multiple OpenSeadragon viewports in one panzoom directive of angular-pan-zoom library. The reason why I need to do this is that I need to wrap the dzi image with HTML tags which also need to be zoom-in/out. But when I tried to put OpenSeadragon div inside that directive, nothing showed up.
Did anyone do this kind of things before? The plugin I refereed to is this: https://github.com/mvindahl/angular-pan-zoom

**Comment by avandecreme** [comment]
It seems like a duplication to have both and I wouldn't be surprised that they conflict.

Can't your html tags be [OpenSeadragon overlays](http://openseadragon.github.io/examples/ui-overlays/)?

**Comment by AliceBump** [comment]
Hi Avandecreme,
I know that OpenSeadragon overlays to add text. The question is that our project requires some effect like the collection mode but also each image can rotate individually and switch position. As far as I know, we can't do it with tilesources but can only do such things to viewports. So I'm trying to put OpenSeadragon divs into panzoom directive so that each image can rotate individually and divs can switch position meanwhile the div itself can zoom in/out.

**Comment by iangilman** [comment]
@AliceBump How big are your images? Do you really need OpenSeadragon for them? Just trying to think through the requirements here.

Of course it would be great if individual images could rotate in OSD. That issue is #978, but no one has taken it on yet. You're welcome to tackle it if you'd like.

Short of that, I suppose one possibility (depending on how many objects you have) would be to layer viewers on top of each other, each filling the full display space, and coordinating between them; whenever the topmost viewer zooms, tell all the others to zoom too. I have no idea how well this would perform, but it's something to try.

**Comment by AliceBump** [comment]
@iangilman My images are pretty big. They are digital microscope images. I think OpenSeadragon is the best tool. 
I think your idea is pretty interesting. I have about 10-20 objects and they have to load dynamically. I don't know if it will work but I'll try it. Thanks.
Do you have any idea why these two libraries conflict with each other? It 'll be great if they can cooperate.

**Comment by iangilman** [comment]
I don't know enough about the other library to say for sure, but it doesn't surprise me that they would conflict.

How are you using them? Laying out a bunch of OSD viewers and zooming the result? What if you want the contents of the viewer to zoom as well? I'm having a hard time visualizing the combination. If it's just because you want to add the HTML tags to the scene, I still think overlays are the best approach for that.

Regarding OSD plus Angular in general, perhaps there is some useful information in #370.

**Comment by AliceBump** [comment]
@iangilman Thanks for your answer. I did manage to use them together but as you said, the zoom issue exists. So I think using OpenseaDragon multi-image is a good choice. The thing is, I need to do some reorder and rotation on the tiles. I'll follow up with #978. Do you have any idea if the reorder thing is doable in multi-image mode? I want some reorder functionality like in this link:
http://james2doyle.github.io/zepto-dragswap/
Here is some sketch showing what we need to implement:
![scratch](https://cloud.githubusercontent.com/assets/8366607/17790714/94c4f76a-654c-11e6-913d-a69c79f12de8.png)
I saw you have an example at http://iangilman.com/openseadragon/flickr/ which allows the tiles moving around. Is this a feature of Flickr API or we can make it work easily with OpenseaDragon?
Thanks a lot.

**Comment by iangilman** [comment]
Yes, dragging images is definitely possible in OpenSeadragon, though it's not built in. Here's some code that does it:

http://codepen.io/iangilman/pen/bZJaGQ

Regarding #978, I presume you've seen that #1006 is in the works... I'm sure @avandecreme would appreciate an early adopter to help test it!

**Comment by AliceBump** [comment]
@iangilman Thanks Ian!
